// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const bs_width : i32 = 1024;
const bs_half_w : i32 = 512;
const bs_half_h : i32 = 384;
fn bs_fall(px : i32, py : i32, cx : i32, cy : i32) -> f32 {
  let dx = f32(f32((px - cx)));
  let dy = f32(f32((py - cy)));
  let d2 = ((dx * dx) + (dy * dy));
  let inten = max(bitcast<f32>(0u), (bitcast<f32>(1065353216u) - (d2 / bitcast<f32>(1166229504u))));
  return ((inten * inten) * inten);
}
@group(0) @binding(0) var<storage, read_write> bloom_scene_step_outb_buf : array<i32>;
struct U_bloom_scene_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_bloom_scene_step : U_bloom_scene_step;
@compute @workgroup_size(64)
fn bloom_scene_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_bloom_scene_step.frame;
  let px = (gid - ((gid / bs_width) * bs_width));
  let py = (gid / bs_width);
  let f = (f32(f32(frame)) / bitcast<f32>(1107296256u));
  let x0 = (bs_half_w + i32((cos(f) * bitcast<f32>(1133903872u))));
  let y0 = (bs_half_h + i32((sin(f) * bitcast<f32>(1127153664u))));
  let x1 = (bs_half_w + i32((cos(((f * bitcast<f32>(1067869798u)) + bitcast<f32>(1074161254u))) * bitcast<f32>(1131413504u))));
  let y1 = (bs_half_h + i32((sin(((f * bitcast<f32>(1067869798u)) + bitcast<f32>(1074161254u))) * bitcast<f32>(1132068864u))));
  let x2 = (bs_half_w + i32((cos(((f * bitcast<f32>(1061997772u)) + bitcast<f32>(1082549862u))) * bitcast<f32>(1134886912u))));
  let y2 = (bs_half_h + i32((sin(((f * bitcast<f32>(1061997772u)) + bitcast<f32>(1082549862u))) * bitcast<f32>(1125515264u))));
  let a = bs_fall(px, py, x0, y0);
  let b = bs_fall(px, py, x1, y1);
  let c = bs_fall(px, py, x2, y2);
  let r = (((a * bitcast<f32>(1132396544u)) + (b * bitcast<f32>(1116471296u))) + (c * bitcast<f32>(1119092736u)));
  let g = (((a * bitcast<f32>(1116471296u)) + (b * bitcast<f32>(1132396544u))) + (c * bitcast<f32>(1121714176u)));
  let bl = (((a * bitcast<f32>(1114636288u)) + (b * bitcast<f32>(1123024896u))) + (c * bitcast<f32>(1132396544u)));
  let ri = i32(min(bitcast<f32>(1132396544u), (r + bitcast<f32>(1086324736u))));
  let gi = i32(min(bitcast<f32>(1132396544u), (g + bitcast<f32>(1088421888u))));
  let bi = i32(min(bitcast<f32>(1132396544u), (bl + bitcast<f32>(1093664768u))));
  bloom_scene_step_outb_buf[gid] = (((ri * 65536) + (gi * 256)) + bi);
}