// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const cp_grav : i32 = 60;
@group(0) @binding(0) var<storage, read_write> cp_step_inb_buf : array<i32>;
@group(0) @binding(1) var<storage, read_write> cp_step_outb_buf : array<i32>;
struct U_cp_step {
  frame : i32,
}
@group(0) @binding(2) var<uniform> u_cp_step : U_cp_step;
@compute @workgroup_size(64)
fn cp_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_cp_step.frame;
  let px = cp_step_inb_buf[(gid * 4)];
  let py = cp_step_inb_buf[((gid * 4) + 1)];
  let vx = cp_step_inb_buf[((gid * 4) + 2)];
  let vy = cp_step_inb_buf[((gid * 4) + 3)];
  let nvy = (vy + cp_grav);
  let mx = (px + vx);
  let my = (py + nvy);
  let off = select(select(select(0, 1, (mx > 16384)), 1, (mx < 0)), 1, (my > 12288));
  let seed = ((gid * 2657) + (frame * 131));
  let h1 = (seed - ((seed / 131) * 131));
  let h2 = ((seed * 7) - (((seed * 7) / 173) * 173));
  let h3 = ((seed * 17) - (((seed * 17) / 97) * 97));
  let rpx = select(mx, (8192 + ((h1 - 65) * 20)), (off == 1));
  let rpy = select(my, 12200, (off == 1));
  let rvx = select(vx, ((h2 - 86) * 9), (off == 1));
  let rvy = select(nvy, (0 - (760 + (h3 * 5))), (off == 1));
  cp_step_outb_buf[(gid * 4)] = rpx;
  cp_step_outb_buf[((gid * 4) + 1)] = rpy;
  cp_step_outb_buf[((gid * 4) + 2)] = rvx;
  cp_step_outb_buf[((gid * 4) + 3)] = rvy;
}