// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const cm_width : i32 = 1024;
const cm_half_w : i32 = 512;
const cm_half_h : i32 = 384;
fn cm_clamp01(x : f32) -> f32 {
  return max(bitcast<f32>(0u), min(bitcast<f32>(1065353216u), x));
}
fn cm_pack(r : f32, g : f32, b : f32) -> i32 {
  return (((i32((cm_clamp01(r) * bitcast<f32>(1132396544u))) * 65536) + (i32((cm_clamp01(g) * bitcast<f32>(1132396544u))) * 256)) + i32((cm_clamp01(b) * bitcast<f32>(1132396544u))));
}
fn cm_noise(x : f32, z : f32) -> f32 {
  return (((sin((x * bitcast<f32>(1063675494u))) * cos((z * bitcast<f32>(1061997772u)))) + ((sin(((x * bitcast<f32>(1072902963u)) + bitcast<f32>(1067869798u))) * cos((z * bitcast<f32>(1074161254u)))) * bitcast<f32>(1056964608u))) + (sin(((x * bitcast<f32>(1079194419u)) - (z * bitcast<f32>(1068708659u)))) * bitcast<f32>(1048576000u)));
}
fn cm_cloud(dx : f32, dz : f32, dy : f32, frame : i32) -> f32 {
  let t = (bitcast<f32>(1067869798u) / dy);
  let cx = (((dx * t) * bitcast<f32>(1068708659u)) + (f32(f32(frame)) / bitcast<f32>(1109917696u)));
  let cz = ((dz * t) * bitcast<f32>(1068708659u));
  let n = cm_noise(cx, cz);
  return (cm_clamp01(((n - bitcast<f32>(1039516303u)) * bitcast<f32>(1067869798u))) * cm_clamp01((dy * bitcast<f32>(1084227584u))));
}
fn cm_sun(d : f32) -> f32 {
  if ((d <= bitcast<f32>(0u))) {
  return bitcast<f32>(0u);
  } else {
  let d2 = (d * d);
  let d4 = (d2 * d2);
  return (((d4 * d4) * d4) * d2);
  }
}
fn cm_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / cm_width) * cm_width));
  let py = (gid / cm_width);
  let fx = (f32(f32((px - cm_half_w))) / bitcast<f32>(1140850688u));
  let fy = (f32(f32((cm_half_h - py))) / bitcast<f32>(1136656384u));
  let yaw = (f32(f32(frame)) / bitcast<f32>(1114636288u));
  let ca = cos(yaw);
  let sa = sin(yaw);
  let rl = sqrt((((fx * fx) + (fy * fy)) + bitcast<f32>(1065353216u)));
  let dx0 = (fx / rl);
  let dy = (fy / rl);
  let dz0 = (bitcast<f32>(1065353216u) / rl);
  let dx = ((dx0 * ca) + (dz0 * sa));
  let dz = ((bitcast<f32>(0u) - (dx0 * sa)) + (dz0 * ca));
  let sund = (((dx * bitcast<f32>(1054280253u)) + (dy * bitcast<f32>(1051595898u))) - (dz * bitcast<f32>(1062668861u)));
  let glow = (cm_sun(sund) * bitcast<f32>(1060320051u));
  let disk = select(bitcast<f32>(0u), bitcast<f32>(1070386380u), (sund > bitcast<f32>(1065294495u)));
  if ((dy < (bitcast<f32>(0u) - bitcast<f32>(1017370378u)))) {
  return cm_pack((bitcast<f32>(1036831948u) - (dy * bitcast<f32>(1028443340u))), (bitcast<f32>(1035489771u) - (dy * bitcast<f32>(1025758986u))), bitcast<f32>(1034147594u));
  } else {
  let cloudv = select(bitcast<f32>(0u), cm_cloud(dx, dz, dy, frame), (dy > bitcast<f32>(1022739087u)));
  let base_r = (bitcast<f32>(1050253721u) + (dy * bitcast<f32>(1036831948u)));
  let base_g = (bitcast<f32>(1056964608u) + (dy * bitcast<f32>(1050253721u)));
  let base_b = (bitcast<f32>(1062333317u) + (dy * bitcast<f32>(1041865113u)));
  let skr = ((base_r + (glow * bitcast<f32>(1063675494u))) + disk);
  let skg = ((base_g + (glow * bitcast<f32>(1061662228u))) + disk);
  let skb = ((base_b + (glow * bitcast<f32>(1055286886u))) + disk);
  return cm_pack(((skr * (bitcast<f32>(1065353216u) - cloudv)) + cloudv), ((skg * (bitcast<f32>(1065353216u) - cloudv)) + cloudv), ((skb * (bitcast<f32>(1065353216u) - cloudv)) + cloudv));
  }
}
@group(0) @binding(0) var<storage, read_write> cubemap_step_outb_buf : array<i32>;
struct U_cubemap_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_cubemap_step : U_cubemap_step;
@compute @workgroup_size(64)
fn cubemap_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_cubemap_step.frame;
  cubemap_step_outb_buf[gid] = cm_render(gid, frame);
}