// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const cu_width : i32 = 1024;
const cu_half_w : i32 = 512;
const cu_half_h : i32 = 384;
fn cu_clamp01(x : f32) -> f32 {
  return max(bitcast<f32>(0u), min(bitcast<f32>(1065353216u), x));
}
fn cu_pack(r : f32, g : f32, b : f32) -> i32 {
  let ri = i32((cu_clamp01(r) * bitcast<f32>(1132396544u)));
  let gi = i32((cu_clamp01(g) * bitcast<f32>(1132396544u)));
  let bi = i32((cu_clamp01(b) * bitcast<f32>(1132396544u)));
  return (((ri * 65536) + (gi * 256)) + bi);
}
fn cu_bg(py : i32) -> i32 {
  let h = (f32(f32(py)) / bitcast<f32>(1145044992u));
  return cu_pack((bitcast<f32>(1025758986u) + (h * bitcast<f32>(1028443340u))), (bitcast<f32>(1028443340u) + (h * bitcast<f32>(1034147594u))), (bitcast<f32>(1035489771u) + (h * bitcast<f32>(1042536202u))));
}
fn cu_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / cu_width) * cu_width));
  let py = (gid / cu_width);
  let fx = (f32(f32((px - cu_half_w))) / bitcast<f32>(1136656384u));
  let fy = (f32(f32((cu_half_h - py))) / bitcast<f32>(1136656384u));
  let rl = sqrt((((fx * fx) + (fy * fy)) + bitcast<f32>(1076090634u)));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (bitcast<f32>(1070386380u) / rl);
  let ay = (f32(f32(frame)) / bitcast<f32>(1107820544u));
  let ax = (f32(f32(frame)) / bitcast<f32>(1112276992u));
  let cy = cos(ay);
  let sy = sin(ay);
  let cx = cos(ax);
  let sx = sin(ax);
  let oz0 = (bitcast<f32>(0u) - bitcast<f32>(1079613849u));
  let oxa = (oz0 * sy);
  let oza = (oz0 * cy);
  let oxb = oxa;
  let oyb = (oza * sx);
  let ozb = (oza * cx);
  let dxa = ((dx * cy) + (dz * sy));
  let dza = ((bitcast<f32>(0u) - (dx * sy)) + (dz * cy));
  let dxb = dxa;
  let dyb = ((dy * cx) + (dza * sx));
  let dzb = ((bitcast<f32>(0u) - (dy * sx)) + (dza * cx));
  let t1x = (((bitcast<f32>(0u) - bitcast<f32>(1065353216u)) - oxb) / dxb);
  let t2x = ((bitcast<f32>(1065353216u) - oxb) / dxb);
  let nxr = min(t1x, t2x);
  let fxr = max(t1x, t2x);
  let t1y = (((bitcast<f32>(0u) - bitcast<f32>(1065353216u)) - oyb) / dyb);
  let t2y = ((bitcast<f32>(1065353216u) - oyb) / dyb);
  let nyr = min(t1y, t2y);
  let fyr = max(t1y, t2y);
  let t1z = (((bitcast<f32>(0u) - bitcast<f32>(1065353216u)) - ozb) / dzb);
  let t2z = ((bitcast<f32>(1065353216u) - ozb) / dzb);
  let nzr = min(t1z, t2z);
  let fzr = max(t1z, t2z);
  let tmin = max(nxr, max(nyr, nzr));
  let tmax = min(fxr, min(fyr, fzr));
  if ((tmin > tmax)) {
  return cu_bg(py);
  } else {
  if ((tmax < bitcast<f32>(981668462u))) {
  return cu_bg(py);
  } else {
  let nlx = select(bitcast<f32>(0u), select(bitcast<f32>(1065353216u), (bitcast<f32>(0u) - bitcast<f32>(1065353216u)), (dxb > bitcast<f32>(0u))), ((nxr >= nyr) & (nxr >= nzr)));
  let nly = select(bitcast<f32>(0u), select(bitcast<f32>(1065353216u), (bitcast<f32>(0u) - bitcast<f32>(1065353216u)), (dyb > bitcast<f32>(0u))), ((nyr >= nxr) & (nyr >= nzr)));
  let nlz = select(bitcast<f32>(0u), select(bitcast<f32>(1065353216u), (bitcast<f32>(0u) - bitcast<f32>(1065353216u)), (dzb > bitcast<f32>(0u))), ((nzr >= nxr) & (nzr >= nyr)));
  let br = select(select(select(select(select(bitcast<f32>(1063675494u), bitcast<f32>(1048576000u), (nlz > bitcast<f32>(1056964608u))), bitcast<f32>(1050253721u), (nly < (bitcast<f32>(0u) - bitcast<f32>(1056964608u)))), bitcast<f32>(1051931443u), (nly > bitcast<f32>(1056964608u))), bitcast<f32>(1062836633u), (nlx < (bitcast<f32>(0u) - bitcast<f32>(1056964608u)))), bitcast<f32>(1064514355u), (nlx > bitcast<f32>(1056964608u)));
  let bg = select(select(select(select(select(bitcast<f32>(1061997772u), bitcast<f32>(1057803468u), (nlz > bitcast<f32>(1056964608u))), bitcast<f32>(1057803468u), (nly < (bitcast<f32>(0u) - bitcast<f32>(1056964608u)))), bitcast<f32>(1062836633u), (nly > bitcast<f32>(1056964608u))), bitcast<f32>(1061158912u), (nlx < (bitcast<f32>(0u) - bitcast<f32>(1056964608u)))), bitcast<f32>(1051931443u), (nlx > bitcast<f32>(1056964608u)));
  let bb = select(select(select(select(select(bitcast<f32>(1050253721u), bitcast<f32>(1063675494u), (nlz > bitcast<f32>(1056964608u))), bitcast<f32>(1062836633u), (nly < (bitcast<f32>(0u) - bitcast<f32>(1056964608u)))), bitcast<f32>(1055286886u), (nly > bitcast<f32>(1056964608u))), bitcast<f32>(1051931443u), (nlx < (bitcast<f32>(0u) - bitcast<f32>(1056964608u)))), bitcast<f32>(1050253721u), (nlx > bitcast<f32>(1056964608u)));
  let lx = bitcast<f32>(1053609164u);
  let ly = bitcast<f32>(1060655595u);
  let lz = (bitcast<f32>(0u) - bitcast<f32>(1057971240u));
  let ndl = max(bitcast<f32>(0u), (((nlx * lx) + (nly * ly)) + (nlz * lz)));
  let sh = (bitcast<f32>(1048576000u) + (ndl * bitcast<f32>(1062836633u)));
  return cu_pack((br * sh), (bg * sh), (bb * sh));
  }
  }
}
@group(0) @binding(0) var<storage, read_write> cube_step_outb_buf : array<i32>;
struct U_cube_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_cube_step : U_cube_step;
@compute @workgroup_size(64)
fn cube_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_cube_step.frame;
  cube_step_outb_buf[gid] = cu_render(gid, frame);
}