// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
fn fw_wrap(a : i32) -> i32 {
  let m = (a - ((a / 6283) * 6283));
  if ((m < 0)) {
  return (m + 6283);
  } else {
  return m;
  }
}
fn fw_sin_core(x : i32) -> i32 {
  let x2 = ((x * x) / 1000);
  let x3 = ((x2 * x) / 1000);
  let x5 = ((x3 * x2) / 1000);
  return ((x - (x3 / 6)) + (x5 / 120));
}
fn fw_sin(raw : i32) -> i32 {
  let a = fw_wrap(raw);
  if ((a <= 1570)) {
  return fw_sin_core(a);
  } else {
  if ((a <= 3141)) {
  return fw_sin_core((3141 - a));
  } else {
  if ((a <= 4712)) {
  return (0 - fw_sin_core((a - 3141)));
  } else {
  return (0 - fw_sin_core((6283 - a)));
  }
  }
  }
}
fn fw_cos(raw : i32) -> i32 {
  return fw_sin((raw + 1570));
}
fn fw_jit_speed(gid : i32) -> i32 {
  return (260 + ((gid * 37) - (((gid / 29) * 29) * 37)));
}
@group(0) @binding(0) var<storage, read_write> fw_burst_spark_out_buf : array<i32>;
struct U_fw_burst_spark {
  cx : i32,
  cy : i32,
  frame : i32,
  nspark : i32,
}
@group(0) @binding(1) var<uniform> u_fw_burst_spark : U_fw_burst_spark;
@compute @workgroup_size(64)
fn fw_burst_spark_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let cx = u_fw_burst_spark.cx;
  let cy = u_fw_burst_spark.cy;
  let frame = u_fw_burst_spark.frame;
  let nspark = u_fw_burst_spark.nspark;
  let ang = fw_wrap(((gid * 6283) / nspark));
  let spd = fw_jit_speed(gid);
  let vx = ((fw_cos(ang) * spd) / 1000);
  let vy = ((fw_sin(ang) * spd) / 1000);
  let px = (cx + ((vx * frame) / 256));
  let py = ((cy + ((vy * frame) / 256)) + (((20 * frame) * frame) / 512));
  let life = (200 - frame);
  let bright = select(((life * 255) / 200), 0, (life < 0));
  let packed = (((bright * 16777216) + (px * 4096)) + py);
  fw_burst_spark_out_buf[gid] = packed;
}
@group(0) @binding(0) var<storage, read_write> fw_integrate_state_buf : array<i32>;
@group(0) @binding(1) var<storage, read_write> fw_integrate_out_buf : array<i32>;
struct U_fw_integrate {
  frame : i32,
  grav : i32,
}
@group(0) @binding(2) var<uniform> u_fw_integrate : U_fw_integrate;
@compute @workgroup_size(64)
fn fw_integrate_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_fw_integrate.frame;
  let grav = u_fw_integrate.grav;
  let px0 = fw_integrate_state_buf[(gid * 4)];
  let py0 = fw_integrate_state_buf[((gid * 4) + 1)];
  let vx = fw_integrate_state_buf[((gid * 4) + 2)];
  let vy = fw_integrate_state_buf[((gid * 4) + 3)];
  let px = (px0 + ((vx * frame) / 256));
  let py = ((py0 + ((vy * frame) / 256)) + (((grav * frame) * frame) / 512));
  let packed = ((px * 65536) + py);
  fw_integrate_out_buf[gid] = packed;
}