// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const gb_width : i32 = 1024;
const gb_half_w : i32 = 512;
const gb_half_h : i32 = 384;
const gb_count : i32 = 8;
const gb_miss : i32 = 8000000;
fn gb_cx(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(0u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1064514355u);
  } else {
  if ((i == 2)) {
  return (bitcast<f32>(0u) - bitcast<f32>(1062836633u));
  } else {
  if ((i == 3)) {
  return bitcast<f32>(1051931443u);
  } else {
  if ((i == 4)) {
  return (bitcast<f32>(0u) - bitcast<f32>(1055286886u));
  } else {
  if ((i == 5)) {
  return bitcast<f32>(1057803468u);
  } else {
  if ((i == 6)) {
  return (bitcast<f32>(0u) - bitcast<f32>(1058642329u));
  } else {
  return bitcast<f32>(1041865113u);
  }
  }
  }
  }
  }
  }
  }
}
fn gb_cy(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(0u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1051931443u);
  } else {
  if ((i == 2)) {
  return bitcast<f32>(1048576000u);
  } else {
  if ((i == 3)) {
  return (bitcast<f32>(0u) - bitcast<f32>(1061997772u));
  } else {
  if ((i == 4)) {
  return (bitcast<f32>(0u) - bitcast<f32>(1058642329u));
  } else {
  if ((i == 5)) {
  return bitcast<f32>(1061158912u);
  } else {
  if ((i == 6)) {
  return bitcast<f32>(1060320051u);
  } else {
  return bitcast<f32>(1036831948u);
  }
  }
  }
  }
  }
  }
  }
}
fn gb_cz(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(0u);
  } else {
  if ((i == 1)) {
  return (bitcast<f32>(0u) - bitcast<f32>(1045220556u));
  } else {
  if ((i == 2)) {
  return bitcast<f32>(1036831948u);
  } else {
  if ((i == 3)) {
  return bitcast<f32>(1045220556u);
  } else {
  if ((i == 4)) {
  return (bitcast<f32>(0u) - bitcast<f32>(1050253721u));
  } else {
  if ((i == 5)) {
  return bitcast<f32>(1050253721u);
  } else {
  if ((i == 6)) {
  return (bitcast<f32>(0u) - bitcast<f32>(1036831948u));
  } else {
  return bitcast<f32>(1061997772u);
  }
  }
  }
  }
  }
  }
  }
}
fn gb_rad(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1063675494u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1058977873u);
  } else {
  if ((i == 2)) {
  return bitcast<f32>(1058642329u);
  } else {
  if ((i == 3)) {
  return bitcast<f32>(1057803468u);
  } else {
  if ((i == 4)) {
  return bitcast<f32>(1056964608u);
  } else {
  if ((i == 5)) {
  return bitcast<f32>(1056964608u);
  } else {
  if ((i == 6)) {
  return bitcast<f32>(1055622430u);
  } else {
  return bitcast<f32>(1056964608u);
  }
  }
  }
  }
  }
  }
  }
}
fn gb_cr(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1062836633u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1063675494u);
  } else {
  if ((i == 2)) {
  return bitcast<f32>(1048576000u);
  } else {
  if ((i == 3)) {
  return bitcast<f32>(1060320051u);
  } else {
  if ((i == 4)) {
  return bitcast<f32>(1051931443u);
  } else {
  if ((i == 5)) {
  return bitcast<f32>(1050253721u);
  } else {
  if ((i == 6)) {
  return bitcast<f32>(1064514355u);
  } else {
  return bitcast<f32>(1063675494u);
  }
  }
  }
  }
  }
  }
  }
}
fn gb_cg(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1061158912u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1050253721u);
  } else {
  if ((i == 2)) {
  return bitcast<f32>(1061997772u);
  } else {
  if ((i == 3)) {
  return bitcast<f32>(1051931443u);
  } else {
  if ((i == 4)) {
  return bitcast<f32>(1061997772u);
  } else {
  if ((i == 5)) {
  return bitcast<f32>(1055286886u);
  } else {
  if ((i == 6)) {
  return bitcast<f32>(1057803468u);
  } else {
  return bitcast<f32>(1055286886u);
  }
  }
  }
  }
  }
  }
  }
}
fn gb_cb(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1055286886u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1049582632u);
  } else {
  if ((i == 2)) {
  return bitcast<f32>(1061158912u);
  } else {
  if ((i == 3)) {
  return bitcast<f32>(1063675494u);
  } else {
  if ((i == 4)) {
  return bitcast<f32>(1053609164u);
  } else {
  if ((i == 5)) {
  return bitcast<f32>(1063675494u);
  } else {
  if ((i == 6)) {
  return bitcast<f32>(1050253721u);
  } else {
  return bitcast<f32>(1059481190u);
  }
  }
  }
  }
  }
  }
  }
}
fn gb_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, i : i32) -> f32 {
  let lx = (ox - gb_cx(i));
  let ly = (oy - gb_cy(i));
  let lz = (oz - gb_cz(i));
  let b = (((dx * lx) + (dy * ly)) + (dz * lz));
  let r = gb_rad(i);
  let c = ((((lx * lx) + (ly * ly)) + (lz * lz)) - (r * r));
  let disc = ((b * b) - c);
  if ((disc < bitcast<f32>(0u))) {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  } else {
  let t = ((bitcast<f32>(0u) - b) - sqrt(disc));
  if ((t > bitcast<f32>(981668462u))) {
  return t;
  } else {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  }
  }
}
fn gb_nearest(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, best_id__a : i32, best_t__a : f32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var best_id = best_id__a;
  var best_t = best_t__a;
  loop {
    if ((i >= gb_count)) {
    return best_id;
    } else {
    let t = gb_hit(ox, oy, oz, dx, dy, dz, i);
    let take = select(0, select(select(0, 1, (t < best_t)), 1, (best_t < bitcast<f32>(0u))), (t > bitcast<f32>(981668462u)));
    if ((take == 1)) {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = i;
    let _mv8 = t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = best_id;
    let _mv8 = best_t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    }
    }
  }
}
fn gb_nbyte(n : f32) -> i32 {
  return i32(((n + bitcast<f32>(1065353216u)) * bitcast<f32>(1123942400u)));
}
@group(0) @binding(0) var<storage, read_write> gbuf_step_galb_buf : array<i32>;
@group(0) @binding(1) var<storage, read_write> gbuf_step_gnrm_buf : array<i32>;
@group(0) @binding(2) var<storage, read_write> gbuf_step_gdep_buf : array<i32>;
@compute @workgroup_size(64)
fn gbuf_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let px = (gid - ((gid / gb_width) * gb_width));
  let py = (gid / gb_width);
  let fx = (f32(f32((px - gb_half_w))) / bitcast<f32>(1136656384u));
  let fy = (f32(f32((gb_half_h - py))) / bitcast<f32>(1136656384u));
  let rl = sqrt((((fx * fx) + (fy * fy)) + bitcast<f32>(1078942760u)));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (bitcast<f32>(1072064102u) / rl);
  let ox = bitcast<f32>(0u);
  let oy = bitcast<f32>(0u);
  let oz = (bitcast<f32>(0u) - bitcast<f32>(1084227584u));
  let id = gb_nearest(ox, oy, oz, dx, dy, dz, 0, (0 - 1), (bitcast<f32>(0u) - bitcast<f32>(1065353216u)));
  let t = select(gb_hit(ox, oy, oz, dx, dy, dz, id), bitcast<f32>(0u), (id < 0));
  let hx = (ox + (dx * t));
  let hy = (oy + (dy * t));
  let hz = (oz + (dz * t));
  let nx = select(((hx - gb_cx(id)) / gb_rad(id)), bitcast<f32>(0u), (id < 0));
  let ny = select(((hy - gb_cy(id)) / gb_rad(id)), bitcast<f32>(1065353216u), (id < 0));
  let nz = select(((hz - gb_cz(id)) / gb_rad(id)), bitcast<f32>(0u), (id < 0));
  let albv = select((((i32((gb_cr(id) * bitcast<f32>(1132396544u))) * 65536) + (i32((gb_cg(id) * bitcast<f32>(1132396544u))) * 256)) + i32((gb_cb(id) * bitcast<f32>(1132396544u)))), 0, (id < 0));
  let nrmv = (((gb_nbyte(nx) * 65536) + (gb_nbyte(ny) * 256)) + gb_nbyte(nz));
  let depv = select(i32((t * bitcast<f32>(1132462080u))), gb_miss, (id < 0));
  gbuf_step_galb_buf[gid] = albv;
  gbuf_step_gnrm_buf[gid] = nrmv;
  gbuf_step_gdep_buf[gid] = depv;
}