// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const gr_width : i32 = 1024;
fn gr_atan2(y : f32, x : f32) -> f32 {
  let ax = select(x, (bitcast<f32>(0u) - x), (x < bitcast<f32>(0u)));
  let ay = select(y, (bitcast<f32>(0u) - y), (y < bitcast<f32>(0u)));
  let mn = min(ax, ay);
  let mx = max(ax, ay);
  let a = select(bitcast<f32>(0u), (mn / mx), (mx > bitcast<f32>(0u)));
  let a2 = (a * a);
  let base = ((a * (bitcast<f32>(1121058816u) + (bitcast<f32>(1113325568u) * a2))) / (bitcast<f32>(1121058816u) + (a2 * (bitcast<f32>(1119092736u) + (bitcast<f32>(1091567616u) * a2)))));
  let r1 = select(base, (bitcast<f32>(1070141402u) - base), (ay > ax));
  let r2 = select(r1, (bitcast<f32>(1078530010u) - r1), (x < bitcast<f32>(0u)));
  if ((y < bitcast<f32>(0u))) {
  return (bitcast<f32>(0u) - r2);
  } else {
  return r2;
  }
}
fn gr_gear(px : f32, py : f32, cx : f32, cy : f32, teeth : f32, rtip : f32, spin : f32) -> f32 {
  let dx = (px - cx);
  let dy = (py - cy);
  let r = sqrt(((dx * dx) + (dy * dy)));
  if ((r > rtip)) {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  } else {
  if ((r < (rtip * bitcast<f32>(1046562734u)))) {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  } else {
  let a = (gr_atan2(dy, dx) + spin);
  let k = i32((((a * teeth) / bitcast<f32>(1078530010u)) + bitcast<f32>(1157234688u)));
  let toothon = (k - ((k / 2) * 2));
  let rroot = (rtip * bitcast<f32>(1061997772u));
  let outer = select(rroot, rtip, (toothon == 0));
  if ((r > outer)) {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  } else {
  if ((r < (rtip * bitcast<f32>(1051595898u)))) {
  return bitcast<f32>(1058977873u);
  } else {
  if ((r < (rtip * bitcast<f32>(1054280253u)))) {
  return bitcast<f32>(1050253721u);
  } else {
  return (bitcast<f32>(1057803468u) + ((r / rtip) * bitcast<f32>(1055286886u)));
  }
  }
  }
  }
  }
}
fn gr_pack(lit : f32, r : f32, g : f32, b : f32) -> i32 {
  let ri = i32(min(bitcast<f32>(1132396544u), ((lit * r) * bitcast<f32>(1132396544u))));
  let gi = i32(min(bitcast<f32>(1132396544u), ((lit * g) * bitcast<f32>(1132396544u))));
  let bi = i32(min(bitcast<f32>(1132396544u), ((lit * b) * bitcast<f32>(1132396544u))));
  return (((ri * 65536) + (gi * 256)) + bi);
}
fn gr_render(gid : i32, frame : i32) -> i32 {
  let px = f32(f32((gid - ((gid / gr_width) * gr_width))));
  let py = f32(f32((gid / gr_width)));
  let f = (f32(f32(frame)) / bitcast<f32>(1106247680u));
  let g0 = gr_gear(px, py, bitcast<f32>(1137508352u), bitcast<f32>(1136656384u), bitcast<f32>(1094713344u), bitcast<f32>(1126170624u), f);
  let g1 = gr_gear(px, py, bitcast<f32>(1143177216u), bitcast<f32>(1133903872u), bitcast<f32>(1090519040u), bitcast<f32>(1121452032u), (bitcast<f32>(0u) - (f * bitcast<f32>(1069547520u))));
  let g2 = gr_gear(px, py, bitcast<f32>(1139474432u), bitcast<f32>(1125908480u), bitcast<f32>(1092616192u), bitcast<f32>(1124073472u), (bitcast<f32>(0u) - (f * bitcast<f32>(1067030937u))));
  if ((g2 >= bitcast<f32>(0u))) {
  return gr_pack(g2, bitcast<f32>(1057803468u), bitcast<f32>(1060655595u), bitcast<f32>(1064514355u));
  } else {
  if ((g1 >= bitcast<f32>(0u))) {
  return gr_pack(g1, bitcast<f32>(1064514355u), bitcast<f32>(1061158912u), bitcast<f32>(1051931443u));
  } else {
  if ((g0 >= bitcast<f32>(0u))) {
  return gr_pack(g0, bitcast<f32>(1062836633u), bitcast<f32>(1051931443u), bitcast<f32>(1050253721u));
  } else {
  let h = (py / bitcast<f32>(1145044992u));
  return gr_pack(bitcast<f32>(1065353216u), (bitcast<f32>(1025758986u) + (h * bitcast<f32>(1025758986u))), (bitcast<f32>(1028443340u) + (h * bitcast<f32>(1031127695u))), (bitcast<f32>(1035489771u) + (h * bitcast<f32>(1036831948u))));
  }
  }
  }
}
@group(0) @binding(0) var<storage, read_write> gears_step_outb_buf : array<i32>;
struct U_gears_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_gears_step : U_gears_step;
@compute @workgroup_size(64)
fn gears_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_gears_step.frame;
  gears_step_outb_buf[gid] = gr_render(gid, frame);
}