// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const in_width : i32 = 1024;
const in_half_w : i32 = 512;
const in_half_h : i32 = 384;
const in_count : i32 = 25;
const in_cols : i32 = 5;
fn in_gx(i : i32) -> f32 {
  return (f32(f32(((i - ((i / in_cols) * in_cols)) - 2))) * bitcast<f32>(1067450368u));
}
fn in_gz(i : i32) -> f32 {
  return (f32(f32(((i / in_cols) - 2))) * bitcast<f32>(1067450368u));
}
const in_half : f32 = bitcast<f32>(1054280253u);
fn in_col_r(i : i32) -> f32 {
  return (bitcast<f32>(1057803468u) + (f32(f32((i - ((i / in_cols) * in_cols)))) * bitcast<f32>(1035489771u)));
}
fn in_col_g(i : i32) -> f32 {
  return (bitcast<f32>(1055286886u) + (f32(f32((i / in_cols))) * bitcast<f32>(1036831948u)));
}
fn in_col_b(i : i32) -> f32 {
  return (bitcast<f32>(1062836633u) - (f32(f32((i - ((i / in_cols) * in_cols)))) * bitcast<f32>(1031127695u)));
}
fn in_box_t(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32) -> f32 {
  let s = in_half;
  let t1x = (((bitcast<f32>(0u) - s) - ox) / dx);
  let t2x = ((s - ox) / dx);
  let nx = min(t1x, t2x);
  let fx = max(t1x, t2x);
  let t1y = (((bitcast<f32>(0u) - s) - oy) / dy);
  let t2y = ((s - oy) / dy);
  let ny = min(t1y, t2y);
  let fy = max(t1y, t2y);
  let t1z = (((bitcast<f32>(0u) - s) - oz) / dz);
  let t2z = ((s - oz) / dz);
  let nz = min(t1z, t2z);
  let fz = max(t1z, t2z);
  let tmin = max(nx, max(ny, nz));
  let tmax = min(fx, min(fy, fz));
  if ((tmin > tmax)) {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  } else {
  if ((tmax < bitcast<f32>(981668462u))) {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  } else {
  if ((tmin < bitcast<f32>(981668462u))) {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  } else {
  return tmin;
  }
  }
  }
}
fn in_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, i : i32) -> f32 {
  return in_box_t((ox - in_gx(i)), oy, (oz - in_gz(i)), dx, dy, dz);
}
fn in_nearest(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, best_id__a : i32, best_t__a : f32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var best_id = best_id__a;
  var best_t = best_t__a;
  loop {
    if ((i >= in_count)) {
    return best_id;
    } else {
    let t = in_hit(ox, oy, oz, dx, dy, dz, i);
    let take = select(0, select(select(0, 1, (t < best_t)), 1, (best_t < bitcast<f32>(0u))), (t > bitcast<f32>(981668462u)));
    if ((take == 1)) {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = i;
    let _mv8 = t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = best_id;
    let _mv8 = best_t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    }
    }
  }
}
fn in_clamp01(x : f32) -> f32 {
  return max(bitcast<f32>(0u), min(bitcast<f32>(1065353216u), x));
}
fn in_pack(r : f32, g : f32, b : f32) -> i32 {
  let ri = i32((in_clamp01(r) * bitcast<f32>(1132396544u)));
  let gi = i32((in_clamp01(g) * bitcast<f32>(1132396544u)));
  let bi = i32((in_clamp01(b) * bitcast<f32>(1132396544u)));
  return (((ri * 65536) + (gi * 256)) + bi);
}
fn in_bg(py : i32) -> i32 {
  let h = (f32(f32(py)) / bitcast<f32>(1145044992u));
  return in_pack((bitcast<f32>(1028443340u) + (h * bitcast<f32>(1031127695u))), (bitcast<f32>(1031127695u) + (h * bitcast<f32>(1035489771u))), (bitcast<f32>(1036831948u) + (h * bitcast<f32>(1043878379u))));
}
fn in_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / in_width) * in_width));
  let py = (gid / in_width);
  let fx = (f32(f32((px - in_half_w))) / bitcast<f32>(1136656384u));
  let fy = (f32(f32((in_half_h - py))) / bitcast<f32>(1136656384u));
  let rl = sqrt((((fx * fx) + ((fy - bitcast<f32>(1051931443u)) * (fy - bitcast<f32>(1051931443u)))) + bitcast<f32>(1074790400u)));
  let dx0 = (fx / rl);
  let dy0 = ((fy - bitcast<f32>(1051931443u)) / rl);
  let dz0 = (bitcast<f32>(1069547520u) / rl);
  let ay = (f32(f32(frame)) / bitcast<f32>(1109393408u));
  let cy = cos(ay);
  let sy = sin(ay);
  let ox0 = bitcast<f32>(0u);
  let oy0 = bitcast<f32>(1074580684u);
  let oz0 = (bitcast<f32>(0u) - bitcast<f32>(1086744166u));
  let ox = ((ox0 * cy) + (oz0 * sy));
  let oz = ((bitcast<f32>(0u) - (ox0 * sy)) + (oz0 * cy));
  let dx = ((dx0 * cy) + (dz0 * sy));
  let dz = ((bitcast<f32>(0u) - (dx0 * sy)) + (dz0 * cy));
  let id = in_nearest(ox, oy0, oz, dx, dy0, dz, 0, (0 - 1), (bitcast<f32>(0u) - bitcast<f32>(1065353216u)));
  if ((id < 0)) {
  return in_bg(py);
  } else {
  let lx = (ox - in_gx(id));
  let lz = (oz - in_gz(id));
  let t = in_box_t(lx, oy0, lz, dx, dy0, dz);
  let hx = (lx + (dx * t));
  let hy = (oy0 + (dy0 * t));
  let hz = (lz + (dz * t));
  let ax = select(hx, (bitcast<f32>(0u) - hx), (hx < bitcast<f32>(0u)));
  let aay = select(hy, (bitcast<f32>(0u) - hy), (hy < bitcast<f32>(0u)));
  let az = select(hz, (bitcast<f32>(0u) - hz), (hz < bitcast<f32>(0u)));
  let nlx = select(bitcast<f32>(0u), select((bitcast<f32>(0u) - bitcast<f32>(1065353216u)), bitcast<f32>(1065353216u), (hx > bitcast<f32>(0u))), ((ax >= aay) & (ax >= az)));
  let nly = select(bitcast<f32>(0u), select((bitcast<f32>(0u) - bitcast<f32>(1065353216u)), bitcast<f32>(1065353216u), (hy > bitcast<f32>(0u))), ((aay >= ax) & (aay >= az)));
  let nlz = select(bitcast<f32>(0u), select((bitcast<f32>(0u) - bitcast<f32>(1065353216u)), bitcast<f32>(1065353216u), (hz > bitcast<f32>(0u))), ((az >= ax) & (az >= aay)));
  let ndl = max(bitcast<f32>(0u), (((nlx * bitcast<f32>(1053609164u)) + (nly * bitcast<f32>(1061662228u))) + (nlz * (bitcast<f32>(0u) - bitcast<f32>(1056293519u)))));
  let sh = (bitcast<f32>(1046562734u) + (ndl * bitcast<f32>(1063339950u)));
  return in_pack((in_col_r(id) * sh), (in_col_g(id) * sh), (in_col_b(id) * sh));
  }
}
@group(0) @binding(0) var<storage, read_write> instancing_step_outb_buf : array<i32>;
struct U_instancing_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_instancing_step : U_instancing_step;
@compute @workgroup_size(64)
fn instancing_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_instancing_step.frame;
  instancing_step_outb_buf[gid] = in_render(gid, frame);
}