// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const ms_width : i32 = 1024;
const ms_half_w : i32 = 512;
const ms_half_h : i32 = 384;
fn ms_ring(cx : f32, cy : f32, phase : f32) -> f32 {
  let r2 = ((cx * cx) + (cy * cy));
  if ((sin(((r2 * bitcast<f32>(980151802u)) + phase)) > bitcast<f32>(0u))) {
  return bitcast<f32>(1065353216u);
  } else {
  return bitcast<f32>(0u);
  }
}
fn ms_super(cx__a : f32, cy__a : f32, phase__a : f32, s__a : i32, acc__a : f32) -> f32 {
  var cx = cx__a;
  var cy = cy__a;
  var phase = phase__a;
  var s = s__a;
  var acc = acc__a;
  loop {
    if ((s >= 16)) {
    return acc;
    } else {
    let sxi = (s - ((s / 4) * 4));
    let syi = (s / 4);
    let ddx = ((f32(f32(sxi)) * bitcast<f32>(1048576000u)) - bitcast<f32>(1052770304u));
    let ddy = ((f32(f32(syi)) * bitcast<f32>(1048576000u)) - bitcast<f32>(1052770304u));
    let _mv0 = cx;
    let _mv1 = cy;
    let _mv2 = phase;
    let _mv3 = (s + 1);
    let _mv4 = (acc + ms_ring((cx + ddx), (cy + ddy), phase));
    cx = _mv0;
    cy = _mv1;
    phase = _mv2;
    s = _mv3;
    acc = _mv4;
    continue;
    }
  }
}
fn ms_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / ms_width) * ms_width));
  let py = (gid / ms_width);
  let cx = f32(f32((px - ms_half_w)));
  let cy = f32(f32((py - ms_half_h)));
  let phase = (f32(f32(frame)) / bitcast<f32>(1101004800u));
  let v = select((ms_super(cx, cy, phase, 0, bitcast<f32>(0u)) / bitcast<f32>(1098907648u)), ms_ring(cx, cy, phase), (px < ms_half_w));
  let edge = select(0, 1, ((px > (ms_half_w - 2)) & (px < (ms_half_w + 2))));
  if ((edge == 1)) {
  return (((40 * 65536) + (90 * 256)) + 130);
  } else {
  let tint_r = select(bitcast<f32>(1057803468u), bitcast<f32>(1061158912u), (px < ms_half_w));
  let tint_g = select(bitcast<f32>(1061997772u), bitcast<f32>(1058642329u), (px < ms_half_w));
  let tint_b = bitcast<f32>(1063675494u);
  let ir = i32(((v * tint_r) * bitcast<f32>(1132396544u)));
  let ig = i32(((v * tint_g) * bitcast<f32>(1132396544u)));
  let ib = i32(((v * tint_b) * bitcast<f32>(1132396544u)));
  return (((ir * 65536) + (ig * 256)) + ib);
  }
}
@group(0) @binding(0) var<storage, read_write> multisample_step_outb_buf : array<i32>;
struct U_multisample_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_multisample_step : U_multisample_step;
@compute @workgroup_size(64)
fn multisample_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_multisample_step.frame;
  multisample_step_outb_buf[gid] = ms_render(gid, frame);
}