// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const om_width : i32 = 1024;
const om_half_w : i32 = 512;
const om_half_h : i32 = 384;
const om_count : i32 = 5;
fn om_cx(i : i32) -> f32 {
  return (cos((f32(f32(i)) * bitcast<f32>(1067505732u))) * bitcast<f32>(1071225241u));
}
fn om_cz(i : i32) -> f32 {
  return (sin((f32(f32(i)) * bitcast<f32>(1067505732u))) * bitcast<f32>(1071225241u));
}
fn om_colr(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1063675494u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1051931443u);
  } else {
  if ((i == 2)) {
  return bitcast<f32>(1053609164u);
  } else {
  if ((i == 3)) {
  return bitcast<f32>(1063675494u);
  } else {
  return bitcast<f32>(1058642329u);
  }
  }
  }
  }
}
fn om_colg(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1056964608u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1061997772u);
  } else {
  if ((i == 2)) {
  return bitcast<f32>(1062836633u);
  } else {
  if ((i == 3)) {
  return bitcast<f32>(1061997772u);
  } else {
  return bitcast<f32>(1056964608u);
  }
  }
  }
  }
}
fn om_colb(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1051931443u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1057803468u);
  } else {
  if ((i == 2)) {
  return bitcast<f32>(1056964608u);
  } else {
  if ((i == 3)) {
  return bitcast<f32>(1051931443u);
  } else {
  return bitcast<f32>(1063675494u);
  }
  }
  }
  }
}
fn om_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, i : i32) -> f32 {
  let lx = (ox - om_cx(i));
  let lz = (oz - om_cz(i));
  let b = (((dx * lx) + (dy * (oy + bitcast<f32>(1053609164u)))) + (dz * lz));
  let c = ((((lx * lx) + ((oy + bitcast<f32>(1053609164u)) * (oy + bitcast<f32>(1053609164u)))) + (lz * lz)) - bitcast<f32>(1052266987u));
  let disc = ((b * b) - c);
  if ((disc < bitcast<f32>(0u))) {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  } else {
  let t = ((bitcast<f32>(0u) - b) - sqrt(disc));
  if ((t > bitcast<f32>(981668462u))) {
  return t;
  } else {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  }
  }
}
fn om_nearest(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, bid__a : i32, bt__a : f32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var bid = bid__a;
  var bt = bt__a;
  loop {
    if ((i >= om_count)) {
    return bid;
    } else {
    let t = om_hit(ox, oy, oz, dx, dy, dz, i);
    let take = select(0, select(select(0, 1, (t < bt)), 1, (bt < bitcast<f32>(0u))), (t > bitcast<f32>(981668462u)));
    if ((take == 1)) {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = i;
    let _mv8 = t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    bid = _mv7;
    bt = _mv8;
    continue;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = bid;
    let _mv8 = bt;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    bid = _mv7;
    bt = _mv8;
    continue;
    }
    }
  }
}
fn om_shadow(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, maxt__a : f32, i__a : i32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var maxt = maxt__a;
  var i = i__a;
  loop {
    if ((i >= om_count)) {
    return 0;
    } else {
    let t = om_hit(ox, oy, oz, dx, dy, dz, i);
    if ((t > bitcast<f32>(1017370378u))) {
    if ((t < maxt)) {
    return 1;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = maxt;
    let _mv7 = (i + 1);
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    maxt = _mv6;
    i = _mv7;
    continue;
    }
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = maxt;
    let _mv7 = (i + 1);
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    maxt = _mv6;
    i = _mv7;
    continue;
    }
    }
  }
}
fn om_checker(hx : f32, hz : f32) -> f32 {
  let ix = i32((hx + bitcast<f32>(1115684864u)));
  let iz = i32((hz + bitcast<f32>(1115684864u)));
  if ((((ix + iz) - (((ix + iz) / 2) * 2)) == 0)) {
  return bitcast<f32>(1051931443u);
  } else {
  return bitcast<f32>(1058642329u);
  }
}
fn om_pack(r : f32, g : f32, b : f32) -> i32 {
  return (((i32((max(bitcast<f32>(0u), min(bitcast<f32>(1065353216u), r)) * bitcast<f32>(1132396544u))) * 65536) + (i32((max(bitcast<f32>(0u), min(bitcast<f32>(1065353216u), g)) * bitcast<f32>(1132396544u))) * 256)) + i32((max(bitcast<f32>(0u), min(bitcast<f32>(1065353216u), b)) * bitcast<f32>(1132396544u))));
}
@group(0) @binding(0) var<storage, read_write> omnishadow_step_outb_buf : array<i32>;
struct U_omnishadow_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_omnishadow_step : U_omnishadow_step;
@compute @workgroup_size(64)
fn omnishadow_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_omnishadow_step.frame;
  let px = (gid - ((gid / om_width) * om_width));
  let py = (gid / om_width);
  let fx = (f32(f32((px - om_half_w))) / bitcast<f32>(1136656384u));
  let fy = ((f32(f32((om_half_h - py))) / bitcast<f32>(1136656384u)) - bitcast<f32>(1049582632u));
  let rl = sqrt((((fx * fx) + (fy * fy)) + bitcast<f32>(1076090634u)));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (bitcast<f32>(1070386380u) / rl);
  let oy = bitcast<f32>(1075419545u);
  let oz = (bitcast<f32>(0u) - bitcast<f32>(1085276160u));
  let la = (f32(f32(frame)) / bitcast<f32>(1109393408u));
  let lgx = (cos(la) * bitcast<f32>(1061997772u));
  let lgy = bitcast<f32>(1066192076u);
  let lgz = (sin(la) * bitcast<f32>(1061997772u));
  let sid = om_nearest(bitcast<f32>(0u), oy, oz, dx, dy, dz, 0, (0 - 1), (bitcast<f32>(0u) - bitcast<f32>(1065353216u)));
  let st = select(om_hit(bitcast<f32>(0u), oy, oz, dx, dy, dz, sid), bitcast<f32>(1148846080u), (sid < 0));
  let ft = select((bitcast<f32>(0u) - bitcast<f32>(1065353216u)), (((bitcast<f32>(0u) - bitcast<f32>(1065353216u)) - oy) / dy), (dy < (bitcast<f32>(0u) - bitcast<f32>(953267991u))));
  let usefloor = select(0, select(select(0, 1, (ft < st)), 1, (sid < 0)), (ft > bitcast<f32>(981668462u)));
  let hitany = select(select(0, 1, (sid >= 0)), 1, (usefloor == 1));
  if ((hitany == 0)) {
  _ = (((10 * 65536) + (12 * 256)) + 22);
  } else {
  let t = select(st, ft, (usefloor == 1));
  let hx = (dx * t);
  let hy = (oy + (dy * t));
  let hz = (oz + (dz * t));
  let nx = select(((hx - om_cx(sid)) / bitcast<f32>(1058642329u)), bitcast<f32>(0u), (usefloor == 1));
  let ny = select(((hy + bitcast<f32>(1053609164u)) / bitcast<f32>(1058642329u)), bitcast<f32>(1065353216u), (usefloor == 1));
  let nz = select(((hz - om_cz(sid)) / bitcast<f32>(1058642329u)), bitcast<f32>(0u), (usefloor == 1));
  let ldx = (lgx - hx);
  let ldy = (lgy - hy);
  let ldz = (lgz - hz);
  let ldist = sqrt((((ldx * ldx) + (ldy * ldy)) + (ldz * ldz)));
  let ux = (ldx / ldist);
  let uy = (ldy / ldist);
  let uz = (ldz / ldist);
  let sh = om_shadow((hx + (ux * bitcast<f32>(1017370378u))), (hy + (uy * bitcast<f32>(1017370378u))), (hz + (uz * bitcast<f32>(1017370378u))), ux, uy, uz, (ldist - bitcast<f32>(1036831948u)), 0);
  let ndl = max(bitcast<f32>(0u), (((nx * ux) + (ny * uy)) + (nz * uz)));
  let atten = (bitcast<f32>(1080033280u) / (bitcast<f32>(1058642329u) + (ldist * ldist)));
  let vis = select(bitcast<f32>(1065353216u), bitcast<f32>(1039516303u), (sh == 1));
  let lit = (bitcast<f32>(1041194024u) + (((ndl * atten) * vis) * bitcast<f32>(1074580684u)));
  let chk = select(bitcast<f32>(0u), om_checker(hx, hz), (usefloor == 1));
  let ar = select(om_colr(sid), chk, (usefloor == 1));
  let ag = select(om_colg(sid), chk, (usefloor == 1));
  let ab = select(om_colb(sid), chk, (usefloor == 1));
  omnishadow_step_outb_buf[gid] = om_pack((ar * lit), (ag * lit), (ab * lit));
  }
}