// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const pa_width : i32 = 1024;
const pa_half_w : i32 = 512;
const pa_half_h : i32 = 384;
fn pa_height(u : f32, v : f32) -> f32 {
  let iv = i32((v / bitcast<f32>(1116471296u)));
  let off = select(bitcast<f32>(1115815936u), bitcast<f32>(0u), ((iv - ((iv / 2) * 2)) == 0));
  let uu = (u + off);
  let iu = i32((uu / bitcast<f32>(1124204544u)));
  let fu = (uu - (f32(f32(iu)) * bitcast<f32>(1124204544u)));
  let fv = (v - (f32(f32(iv)) * bitcast<f32>(1116471296u)));
  let du = min(fu, (bitcast<f32>(1124204544u) - fu));
  let dv = min(fv, (bitcast<f32>(1116471296u) - fv));
  let d = min(du, dv);
  return min(bitcast<f32>(1065353216u), max(bitcast<f32>(0u), ((d - bitcast<f32>(1082130432u)) / bitcast<f32>(1091567616u))));
}
fn pa_clamp01(x : f32) -> f32 {
  return max(bitcast<f32>(0u), min(bitcast<f32>(1065353216u), x));
}
fn pa_pack(r : f32, g : f32, b : f32) -> i32 {
  let ri = i32((pa_clamp01(r) * bitcast<f32>(1132396544u)));
  let gi = i32((pa_clamp01(g) * bitcast<f32>(1132396544u)));
  let bi = i32((pa_clamp01(b) * bitcast<f32>(1132396544u)));
  return (((ri * 65536) + (gi * 256)) + bi);
}
fn pa_render(gid : i32, frame : i32) -> i32 {
  let px = f32(f32((gid - ((gid / pa_width) * pa_width))));
  let py = f32(f32((gid / pa_width)));
  let vdx = ((px - f32(f32(pa_half_w))) / bitcast<f32>(1146388480u));
  let vdy = ((py - f32(f32(pa_half_h))) / bitcast<f32>(1146388480u));
  let h0 = pa_height(px, py);
  let up = (px + ((vdx * h0) * bitcast<f32>(1108344832u)));
  let vp = (py + ((vdy * h0) * bitcast<f32>(1108344832u)));
  let h = pa_height(up, vp);
  let hu1 = pa_height((up + bitcast<f32>(1073741824u)), vp);
  let hu0 = pa_height((up - bitcast<f32>(1073741824u)), vp);
  let hv1 = pa_height(up, (vp + bitcast<f32>(1073741824u)));
  let hv0 = pa_height(up, (vp - bitcast<f32>(1073741824u)));
  let nx = ((hu0 - hu1) * bitcast<f32>(1088421888u));
  let ny = ((hv0 - hv1) * bitcast<f32>(1088421888u));
  let nl = sqrt((((nx * nx) + (ny * ny)) + bitcast<f32>(1065353216u)));
  let ux = (nx / nl);
  let uy = (ny / nl);
  let uz = (bitcast<f32>(1065353216u) / nl);
  let ang = (f32(f32(frame)) / bitcast<f32>(1105199104u));
  let lx = (cos(ang) * bitcast<f32>(1058642329u));
  let ly = (sin(ang) * bitcast<f32>(1058642329u));
  let lz = bitcast<f32>(1058977873u);
  let ll = sqrt((((lx * lx) + (ly * ly)) + (lz * lz)));
  let ndl = max(bitcast<f32>(0u), ((((ux * lx) / ll) + ((uy * ly) / ll)) + ((uz * lz) / ll)));
  let ivp = i32((vp / bitcast<f32>(1116471296u)));
  let offp = select(bitcast<f32>(1115815936u), bitcast<f32>(0u), ((ivp - ((ivp / 2) * 2)) == 0));
  let iup = i32(((up + offp) / bitcast<f32>(1124204544u)));
  let hue = ((iup * 2) + (ivp * 3));
  let hm = (hue - ((hue / 3) * 3));
  let br = select((bitcast<f32>(1058306785u) + (f32(f32(hm)) * bitcast<f32>(1031127695u))), bitcast<f32>(1051595898u), (h < bitcast<f32>(1048576000u)));
  let bg = select(bitcast<f32>(1048911544u), bitcast<f32>(1051260354u), (h < bitcast<f32>(1048576000u)));
  let bb = select(bitcast<f32>(1045220556u), bitcast<f32>(1050924810u), (h < bitcast<f32>(1048576000u)));
  let sh = (bitcast<f32>(1046562734u) + (ndl * bitcast<f32>(1064011038u)));
  return pa_pack((br * sh), (bg * sh), (bb * sh));
}
@group(0) @binding(0) var<storage, read_write> parallax_step_outb_buf : array<i32>;
struct U_parallax_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_parallax_step : U_parallax_step;
@compute @workgroup_size(64)
fn parallax_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_parallax_step.frame;
  parallax_step_outb_buf[gid] = pa_render(gid, frame);
}