// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const pa_width : i32 = 1024;
const pa_height : i32 = 768;
fn pa_wrap(a : i32) -> i32 {
  let m = (a - ((a / 6283) * 6283));
  if ((m < 0)) {
  return (m + 6283);
  } else {
  return m;
  }
}
fn pa_sin_core(x : i32) -> i32 {
  let x2 = ((x * x) / 1000);
  let x3 = ((x2 * x) / 1000);
  let x5 = ((x3 * x2) / 1000);
  return ((x - (x3 / 6)) + (x5 / 120));
}
fn pa_sin(raw : i32) -> i32 {
  let a = pa_wrap(raw);
  if ((a <= 1570)) {
  return pa_sin_core(a);
  } else {
  if ((a <= 3141)) {
  return pa_sin_core((3141 - a));
  } else {
  if ((a <= 4712)) {
  return (0 - pa_sin_core((a - 3141)));
  } else {
  return (0 - pa_sin_core((6283 - a)));
  }
  }
  }
}
fn pa_cos(raw : i32) -> i32 {
  return pa_sin((raw + 1570));
}
fn pa_ax0(frame : i32) -> i32 {
  return (512 + ((pa_cos((frame * 34)) * 270) / 1000));
}
fn pa_ay0(frame : i32) -> i32 {
  return (384 + ((pa_sin((frame * 34)) * 180) / 1000));
}
fn pa_ax1(frame : i32) -> i32 {
  return (512 - ((pa_cos((frame * 34)) * 270) / 1000));
}
fn pa_ay1(frame : i32) -> i32 {
  return (384 - ((pa_sin((frame * 34)) * 180) / 1000));
}
fn pa_acc(px : i32, py : i32, ax : i32, ay : i32) -> i32 {
  let dx = (ax - px);
  let dy = (ay - py);
  let d2 = ((dx * dx) + (dy * dy));
  let inv = (260000 / ((d2 / 256) + 500));
  return ((dx * inv) / 11000);
}
fn pa_acc_y(px : i32, py : i32, ax : i32, ay : i32) -> i32 {
  let dx = (ax - px);
  let dy = (ay - py);
  let d2 = ((dx * dx) + (dy * dy));
  let inv = (260000 / ((d2 / 256) + 500));
  return ((dy * inv) / 11000);
}
fn pa_wrap_pos(v : i32, m : i32) -> i32 {
  let r = (v - ((v / m) * m));
  if ((r < 0)) {
  return (r + m);
  } else {
  return r;
  }
}
@group(0) @binding(0) var<storage, read_write> particles_step_inb_buf : array<i32>;
@group(0) @binding(1) var<storage, read_write> particles_step_outb_buf : array<i32>;
struct U_particles_step {
  frame : i32,
}
@group(0) @binding(2) var<uniform> u_particles_step : U_particles_step;
@compute @workgroup_size(64)
fn particles_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_particles_step.frame;
  let px = particles_step_inb_buf[(gid * 4)];
  let py = particles_step_inb_buf[((gid * 4) + 1)];
  let vx = particles_step_inb_buf[((gid * 4) + 2)];
  let vy = particles_step_inb_buf[((gid * 4) + 3)];
  let ax0 = pa_ax0(frame);
  let ay0 = pa_ay0(frame);
  let ax1 = pa_ax1(frame);
  let ay1 = pa_ay1(frame);
  let accx = (pa_acc(px, py, ax0, ay0) + pa_acc(px, py, ax1, ay1));
  let accy = (pa_acc_y(px, py, ax0, ay0) + pa_acc_y(px, py, ax1, ay1));
  let nvx = ((vx - (vx / 48)) + accx);
  let nvy = ((vy - (vy / 48)) + accy);
  let npx = pa_wrap_pos((px + (nvx / 16)), pa_width);
  let npy = pa_wrap_pos((py + (nvy / 16)), pa_height);
  particles_step_outb_buf[(gid * 4)] = npx;
  particles_step_outb_buf[((gid * 4) + 1)] = npy;
  particles_step_outb_buf[((gid * 4) + 2)] = nvx;
  particles_step_outb_buf[((gid * 4) + 3)] = nvy;
}