// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const pi_width : i32 = 1024;
const pi_half_w : i32 = 512;
const pi_half_h : i32 = 384;
const pi_count : i32 = 6;
fn pi_env_r(dy : f32) -> f32 {
  if ((dy > bitcast<f32>(0u))) {
  return (bitcast<f32>(1046562734u) + (dy * bitcast<f32>(1048576000u)));
  } else {
  return (bitcast<f32>(1049582632u) - (dy * bitcast<f32>(1036831948u)));
  }
}
fn pi_env_g(dy : f32) -> f32 {
  if ((dy > bitcast<f32>(0u))) {
  return (bitcast<f32>(1052938076u) + (dy * bitcast<f32>(1053609164u)));
  } else {
  return (bitcast<f32>(1047904911u) - (dy * bitcast<f32>(1031127695u)));
  }
}
fn pi_env_b(dy : f32) -> f32 {
  if ((dy > bitcast<f32>(0u))) {
  return (bitcast<f32>(1058977873u) + (dy * bitcast<f32>(1051931443u)));
  } else {
  return (bitcast<f32>(1042536202u) - (dy * bitcast<f32>(1017370378u)));
  }
}
fn pi_sun(dx : f32, dy : f32, dz : f32) -> f32 {
  let d = (((dx * bitcast<f32>(1058642329u)) + (dy * bitcast<f32>(1059984506u))) + (dz * (bitcast<f32>(0u) - bitcast<f32>(1059984506u))));
  if ((d > bitcast<f32>(0u))) {
  let p = (d * d);
  return (((p * p) * p) * p);
  } else {
  return bitcast<f32>(0u);
  }
}
fn pi_cx(i : i32) -> f32 {
  return ((f32(f32(i)) * bitcast<f32>(1066611507u)) - bitcast<f32>(1077516697u));
}
fn pi_rough(i : i32) -> f32 {
  return (bitcast<f32>(1025758986u) + (f32(f32(i)) * bitcast<f32>(1043207290u)));
}
fn pi_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, i : i32) -> f32 {
  let lx = (ox - pi_cx(i));
  let b = (((dx * lx) + (dy * oy)) + (dz * oz));
  let c = ((((lx * lx) + (oy * oy)) + (oz * oz)) - bitcast<f32>(1049260510u));
  let disc = ((b * b) - c);
  if ((disc < bitcast<f32>(0u))) {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  } else {
  let t = ((bitcast<f32>(0u) - b) - sqrt(disc));
  if ((t > bitcast<f32>(981668462u))) {
  return t;
  } else {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  }
  }
}
fn pi_nearest(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, bid__a : i32, bt__a : f32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var bid = bid__a;
  var bt = bt__a;
  loop {
    if ((i >= pi_count)) {
    return bid;
    } else {
    let t = pi_hit(ox, oy, oz, dx, dy, dz, i);
    let take = select(0, select(select(0, 1, (t < bt)), 1, (bt < bitcast<f32>(0u))), (t > bitcast<f32>(981668462u)));
    if ((take == 1)) {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = i;
    let _mv8 = t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    bid = _mv7;
    bt = _mv8;
    continue;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = bid;
    let _mv8 = bt;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    bid = _mv7;
    bt = _mv8;
    continue;
    }
    }
  }
}
fn pi_clamp01(x : f32) -> f32 {
  return max(bitcast<f32>(0u), min(bitcast<f32>(1065353216u), x));
}
fn pi_pack(r : f32, g : f32, b : f32) -> i32 {
  return (((i32((pi_clamp01(r) * bitcast<f32>(1132396544u))) * 65536) + (i32((pi_clamp01(g) * bitcast<f32>(1132396544u))) * 256)) + i32((pi_clamp01(b) * bitcast<f32>(1132396544u))));
}
fn pi_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / pi_width) * pi_width));
  let py = (gid / pi_width);
  let fx = (f32(f32((px - pi_half_w))) / bitcast<f32>(1136656384u));
  let fy = (f32(f32((pi_half_h - py))) / bitcast<f32>(1136656384u));
  let rl = sqrt((((fx * fx) + (fy * fy)) + bitcast<f32>(1082130432u)));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (bitcast<f32>(1073741824u) / rl);
  let oz = (bitcast<f32>(0u) - bitcast<f32>(1084227584u));
  let id = pi_nearest(bitcast<f32>(0u), bitcast<f32>(0u), oz, dx, dy, dz, 0, (0 - 1), (bitcast<f32>(0u) - bitcast<f32>(1065353216u)));
  if ((id < 0)) {
  return pi_pack((pi_env_r(dy) + pi_sun(dx, dy, dz)), (pi_env_g(dy) + pi_sun(dx, dy, dz)), (pi_env_b(dy) + pi_sun(dx, dy, dz)));
  } else {
  let t = pi_hit(bitcast<f32>(0u), bitcast<f32>(0u), oz, dx, dy, dz, id);
  let hx = (dx * t);
  let hy = (dy * t);
  let hz = (oz + (dz * t));
  let nx = ((hx - pi_cx(id)) / bitcast<f32>(1057300152u));
  let ny = (hy / bitcast<f32>(1057300152u));
  let nz = (hz / bitcast<f32>(1057300152u));
  let vd = (((dx * nx) + (dy * ny)) + (dz * nz));
  let rx = (dx - ((bitcast<f32>(1073741824u) * vd) * nx));
  let ry = (dy - ((bitcast<f32>(1073741824u) * vd) * ny));
  let rz = (dz - ((bitcast<f32>(1073741824u) * vd) * nz));
  let rough = pi_rough(id);
  let er = (pi_env_r(ry) + pi_sun(rx, ry, rz));
  let eg = (pi_env_g(ry) + pi_sun(rx, ry, rz));
  let eb = (pi_env_b(ry) + pi_sun(rx, ry, rz));
  let mr = ((er * (bitcast<f32>(1065353216u) - rough)) + (bitcast<f32>(1054280253u) * rough));
  let mg = ((eg * (bitcast<f32>(1065353216u) - rough)) + (bitcast<f32>(1055622430u) * rough));
  let mb = ((eb * (bitcast<f32>(1065353216u) - rough)) + (bitcast<f32>(1057803468u) * rough));
  let fres = (bitcast<f32>(1034147594u) + ((bitcast<f32>(1064011038u) * pi_clamp01((bitcast<f32>(1065353216u) + vd))) * pi_clamp01((bitcast<f32>(1065353216u) + vd))));
  let tint_r = bitcast<f32>(1064514355u);
  let tint_g = bitcast<f32>(1061662228u);
  let tint_b = bitcast<f32>(1055286886u);
  return pi_pack(((mr * tint_r) * (bitcast<f32>(1056964608u) + (fres * bitcast<f32>(1058642329u)))), ((mg * tint_g) * (bitcast<f32>(1056964608u) + (fres * bitcast<f32>(1058642329u)))), ((mb * tint_b) * (bitcast<f32>(1056964608u) + (fres * bitcast<f32>(1058642329u)))));
  }
}
@group(0) @binding(0) var<storage, read_write> pbribl_step_outb_buf : array<i32>;
struct U_pbribl_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_pbribl_step : U_pbribl_step;
@compute @workgroup_size(64)
fn pbribl_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_pbribl_step.frame;
  pbribl_step_outb_buf[gid] = pi_render(gid, frame);
}