// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const pb_width : i32 = 1024;
const pb_half_w : i32 = 512;
const pb_half_h : i32 = 384;
const pb_count : i32 = 7;
fn pb_cx(i : i32) -> f32 {
  return ((f32(f32(i)) * bitcast<f32>(1066611507u)) - bitcast<f32>(1079823564u));
}
fn pb_rough(i : i32) -> f32 {
  return (bitcast<f32>(1031127695u) + (f32(f32(i)) * bitcast<f32>(1041529569u)));
}
const pb_rad : f32 = bitcast<f32>(1057300152u);
fn pb_sphere_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, i : i32) -> f32 {
  let lx = (ox - pb_cx(i));
  let ly = oy;
  let lz = oz;
  let b = (((dx * lx) + (dy * ly)) + (dz * lz));
  let c = ((((lx * lx) + (ly * ly)) + (lz * lz)) - (pb_rad * pb_rad));
  let disc = ((b * b) - c);
  if ((disc < bitcast<f32>(0u))) {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  } else {
  let t = ((bitcast<f32>(0u) - b) - sqrt(disc));
  if ((t > bitcast<f32>(981668462u))) {
  return t;
  } else {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  }
  }
}
fn pb_nearest(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, best_id__a : i32, best_t__a : f32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var best_id = best_id__a;
  var best_t = best_t__a;
  loop {
    if ((i >= pb_count)) {
    return best_id;
    } else {
    let t = pb_sphere_hit(ox, oy, oz, dx, dy, dz, i);
    let take = select(0, select(select(0, 1, (t < best_t)), 1, (best_t < bitcast<f32>(0u))), (t > bitcast<f32>(981668462u)));
    if ((take == 1)) {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = i;
    let _mv8 = t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = best_id;
    let _mv8 = best_t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    }
    }
  }
}
fn pb_clamp01(x : f32) -> f32 {
  return max(bitcast<f32>(0u), min(bitcast<f32>(1065353216u), x));
}
fn pb_pow5(x : f32) -> f32 {
  let x2 = (x * x);
  return ((x2 * x2) * x);
}
fn pb_ggx(ndh : f32, a : f32) -> f32 {
  let a2 = (a * a);
  let d = (((ndh * ndh) * (a2 - bitcast<f32>(1065353216u))) + bitcast<f32>(1065353216u));
  return (a2 / ((d * d) + bitcast<f32>(953267991u)));
}
fn pb_g1(nx : f32, k : f32) -> f32 {
  return (nx / (((nx * (bitcast<f32>(1065353216u) - k)) + k) + bitcast<f32>(953267991u)));
}
fn pb_pack(r : f32, g : f32, b : f32) -> i32 {
  let ri = i32((pb_clamp01(r) * bitcast<f32>(1132396544u)));
  let gi = i32((pb_clamp01(g) * bitcast<f32>(1132396544u)));
  let bi = i32((pb_clamp01(b) * bitcast<f32>(1132396544u)));
  return (((ri * 65536) + (gi * 256)) + bi);
}
fn pb_bg(py : i32) -> i32 {
  let h = (f32(f32(py)) / bitcast<f32>(1145044992u));
  return pb_pack((bitcast<f32>(1022739087u) + (h * bitcast<f32>(1028443340u))), (bitcast<f32>(1025758986u) + (h * bitcast<f32>(1031127695u))), (bitcast<f32>(1031127695u) + (h * bitcast<f32>(1036831948u))));
}
fn pb_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / pb_width) * pb_width));
  let py = (gid / pb_width);
  let fx = (f32(f32((px - pb_half_w))) / bitcast<f32>(1136656384u));
  let fy = (f32(f32((pb_half_h - py))) / bitcast<f32>(1136656384u));
  let rl = sqrt((((fx * fx) + (fy * fy)) + bitcast<f32>(1082130432u)));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (bitcast<f32>(1073741824u) / rl);
  let ox = bitcast<f32>(0u);
  let oy = bitcast<f32>(0u);
  let oz = (bitcast<f32>(0u) - bitcast<f32>(1084227584u));
  let id = pb_nearest(ox, oy, oz, dx, dy, dz, 0, (0 - 1), (bitcast<f32>(0u) - bitcast<f32>(1065353216u)));
  if ((id < 0)) {
  return pb_bg(py);
  } else {
  let t = pb_sphere_hit(ox, oy, oz, dx, dy, dz, id);
  let hx = (ox + (dx * t));
  let hy = (oy + (dy * t));
  let hz = (oz + (dz * t));
  let nx = ((hx - pb_cx(id)) / pb_rad);
  let ny = (hy / pb_rad);
  let nz = (hz / pb_rad);
  let ang = (f32(f32(frame)) / bitcast<f32>(1109393408u));
  let lx0 = ((cos(ang) * bitcast<f32>(1056964608u)) + bitcast<f32>(1050253721u));
  let ly0 = bitcast<f32>(1060320051u);
  let lz0 = ((sin(ang) * bitcast<f32>(1056964608u)) - bitcast<f32>(1056964608u));
  let ll = sqrt((((lx0 * lx0) + (ly0 * ly0)) + (lz0 * lz0)));
  let lx = (lx0 / ll);
  let ly = (ly0 / ll);
  let lz = (lz0 / ll);
  let vx = (bitcast<f32>(0u) - dx);
  let vy = (bitcast<f32>(0u) - dy);
  let vz = (bitcast<f32>(0u) - dz);
  let hlx = (lx + vx);
  let hly = (ly + vy);
  let hlz = (lz + vz);
  let hl = (sqrt((((hlx * hlx) + (hly * hly)) + (hlz * hlz))) + bitcast<f32>(953267991u));
  let hnx = (hlx / hl);
  let hny = (hly / hl);
  let hnz = (hlz / hl);
  let ndl = max(bitcast<f32>(0u), (((nx * lx) + (ny * ly)) + (nz * lz)));
  let ndv = max(bitcast<f32>(0u), (((nx * vx) + (ny * vy)) + (nz * vz)));
  let ndh = max(bitcast<f32>(0u), (((nx * hnx) + (ny * hny)) + (nz * hnz)));
  let vdh = max(bitcast<f32>(0u), (((vx * hnx) + (vy * hny)) + (vz * hnz)));
  let rough = pb_rough(id);
  let a = (rough * rough);
  let k = (a * bitcast<f32>(1056964608u));
  let dggx = pb_ggx(ndh, a);
  let gsm = (pb_g1(ndv, k) * pb_g1(ndl, k));
  let fres = (bitcast<f32>(1025758986u) + (bitcast<f32>(1064682127u) * pb_pow5((bitcast<f32>(1065353216u) - vdh))));
  let spec = (((dggx * gsm) * fres) / (((bitcast<f32>(1082130432u) * ndv) * ndl) + bitcast<f32>(1008981770u)));
  let kd = (bitcast<f32>(1065353216u) - fres);
  let dr = (bitcast<f32>(1063675494u) * kd);
  let dg = (bitcast<f32>(1060655595u) * kd);
  let db = (bitcast<f32>(1050253721u) * kd);
  let sr = (((dr + spec) * ndl) + bitcast<f32>(1028443340u));
  let sg = (((dg + spec) * ndl) + bitcast<f32>(1031127695u));
  let sb = (((db + spec) * ndl) + bitcast<f32>(1034147594u));
  return pb_pack(sr, sg, sb);
  }
}
@group(0) @binding(0) var<storage, read_write> pbr_step_outb_buf : array<i32>;
struct U_pbr_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_pbr_step : U_pbr_step;
@compute @workgroup_size(64)
fn pbr_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_pbr_step.frame;
  pbr_step_outb_buf[gid] = pb_render(gid, frame);
}