// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const pt_width : i32 = 1024;
const pt_half_w : i32 = 512;
const pt_half_h : i32 = 384;
fn pt_tex_r(iu : i32, iv : i32) -> f32 {
  let m = (((iu * 3) + (iv * 5)) - ((((iu * 3) + (iv * 5)) / 4) * 4));
  return (bitcast<f32>(1055286886u) + (f32(f32(m)) * bitcast<f32>(1039516303u)));
}
fn pt_tex_g(iu : i32, iv : i32) -> f32 {
  let m = ((iu + (iv * 2)) - (((iu + (iv * 2)) / 3) * 3));
  return (bitcast<f32>(1053609164u) + (f32(f32(m)) * bitcast<f32>(1042536202u)));
}
fn pt_clamp01(x : f32) -> f32 {
  return max(bitcast<f32>(0u), min(bitcast<f32>(1065353216u), x));
}
fn pt_pack(r : f32, g : f32, b : f32) -> i32 {
  return (((i32((pt_clamp01(r) * bitcast<f32>(1132396544u))) * 65536) + (i32((pt_clamp01(g) * bitcast<f32>(1132396544u))) * 256)) + i32((pt_clamp01(b) * bitcast<f32>(1132396544u))));
}
fn pt_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / pt_width) * pt_width));
  let py = (gid / pt_width);
  let fx = (f32(f32((px - pt_half_w))) / bitcast<f32>(1136656384u));
  let fy = (f32(f32((pt_half_h - py))) / bitcast<f32>(1136656384u));
  let rl = sqrt((((fx * fx) + (fy * fy)) + bitcast<f32>(1082130432u)));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (bitcast<f32>(1073741824u) / rl);
  let oz = (bitcast<f32>(0u) - bitcast<f32>(1082130432u));
  let b = (dz * oz);
  let c = ((oz * oz) - bitcast<f32>(1070386380u));
  let disc = ((b * b) - c);
  if ((disc < bitcast<f32>(0u))) {
  let h = pt_clamp01(((dy * bitcast<f32>(1056964608u)) + bitcast<f32>(1056964608u)));
  return pt_pack((bitcast<f32>(1028443340u) + (h * bitcast<f32>(1028443340u))), (bitcast<f32>(1031127695u) + (h * bitcast<f32>(1034147594u))), (bitcast<f32>(1036831948u) + (h * bitcast<f32>(1041865113u))));
  } else {
  let t = ((bitcast<f32>(0u) - b) - sqrt(disc));
  let hx = (dx * t);
  let hy = (dy * t);
  let hz = (oz + (dz * t));
  let nx = (hx / bitcast<f32>(1067576197u));
  let ny = (hy / bitcast<f32>(1067576197u));
  let nz = (hz / bitcast<f32>(1067576197u));
  let spin = (f32(f32(frame)) / bitcast<f32>(1109393408u));
  let u = ((((cos(spin) * nx) + (sin(spin) * nz)) * bitcast<f32>(1056964608u)) + bitcast<f32>(1056964608u));
  let v = ((ny * bitcast<f32>(1056964608u)) + bitcast<f32>(1056964608u));
  let iu = i32((u * bitcast<f32>(1094713344u)));
  let iv = i32((v * bitcast<f32>(1090519040u)));
  let fu = ((u * bitcast<f32>(1094713344u)) - f32(f32(iu)));
  let fv = ((v * bitcast<f32>(1090519040u)) - f32(f32(iv)));
  let grout = select(select(0, 1, (fv < bitcast<f32>(1034147594u))), 1, (fu < bitcast<f32>(1034147594u)));
  let ar = select(pt_tex_r(iu, iv), bitcast<f32>(1041194024u), (grout == 1));
  let ag = select(pt_tex_g(iu, iv), bitcast<f32>(1041194024u), (grout == 1));
  let ab = select(bitcast<f32>(1057803468u), bitcast<f32>(1042536202u), (grout == 1));
  let la = (f32(f32(frame)) / bitcast<f32>(1106247680u));
  let lx = (cos(la) * bitcast<f32>(1058642329u));
  let ly = bitcast<f32>(1060320051u);
  let lz = ((sin(la) * bitcast<f32>(1058642329u)) - bitcast<f32>(1050253721u));
  let ll = sqrt((((lx * lx) + (ly * ly)) + (lz * lz)));
  let ux = (lx / ll);
  let uy = (ly / ll);
  let uz = (lz / ll);
  let hlx = (ux - dx);
  let hly = (uy - dy);
  let hlz = (uz - dz);
  let hl = (sqrt((((hlx * hlx) + (hly * hly)) + (hlz * hlz))) + bitcast<f32>(981668462u));
  let ndh = max(bitcast<f32>(0u), ((((nx * hlx) / hl) + ((ny * hly) / hl)) + ((nz * hlz) / hl)));
  let ndl = max(bitcast<f32>(0u), (((nx * ux) + (ny * uy)) + (nz * uz)));
  let a2 = bitcast<f32>(1035489771u);
  let dd = (((ndh * ndh) * (a2 - bitcast<f32>(1065353216u))) + bitcast<f32>(1065353216u));
  let spec = ((a2 / ((dd * dd) + bitcast<f32>(981668462u))) * bitcast<f32>(1053609164u));
  let sh = (bitcast<f32>(1041865113u) + (ndl * bitcast<f32>(1062836633u)));
  return pt_pack(((ar * sh) + spec), ((ag * sh) + spec), ((ab * sh) + spec));
  }
}
@group(0) @binding(0) var<storage, read_write> pbrtex_step_outb_buf : array<i32>;
struct U_pbrtex_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_pbrtex_step : U_pbrtex_step;
@compute @workgroup_size(64)
fn pbrtex_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_pbrtex_step.frame;
  pbrtex_step_outb_buf[gid] = pt_render(gid, frame);
}