// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const pl_width : i32 = 1024;
const pl_half_w : i32 = 512;
const pl_half_h : i32 = 384;
const pl_count : i32 = 6;
fn pl_cx(i : i32) -> f32 {
  return ((f32(f32(i)) * bitcast<f32>(1067030937u)) - bitcast<f32>(1077936128u));
}
fn pl_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, i : i32) -> f32 {
  let lx = (ox - pl_cx(i));
  let b = (((dx * lx) + (dy * oy)) + (dz * oz));
  let c = ((((lx * lx) + (oy * oy)) + (oz * oz)) - bitcast<f32>(1050337607u));
  let disc = ((b * b) - c);
  if ((disc < bitcast<f32>(0u))) {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  } else {
  let t = ((bitcast<f32>(0u) - b) - sqrt(disc));
  if ((t > bitcast<f32>(981668462u))) {
  return t;
  } else {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  }
  }
}
fn pl_nearest(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, bid__a : i32, bt__a : f32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var bid = bid__a;
  var bt = bt__a;
  loop {
    if ((i >= pl_count)) {
    return bid;
    } else {
    let t = pl_hit(ox, oy, oz, dx, dy, dz, i);
    let take = select(0, select(select(0, 1, (t < bt)), 1, (bt < bitcast<f32>(0u))), (t > bitcast<f32>(981668462u)));
    if ((take == 1)) {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = i;
    let _mv8 = t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    bid = _mv7;
    bt = _mv8;
    continue;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = bid;
    let _mv8 = bt;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    bid = _mv7;
    bt = _mv8;
    continue;
    }
    }
  }
}
fn pl_clamp01(x : f32) -> f32 {
  return max(bitcast<f32>(0u), min(bitcast<f32>(1065353216u), x));
}
fn pl_pack(r : f32, g : f32, b : f32) -> i32 {
  return (((i32((pl_clamp01(r) * bitcast<f32>(1132396544u))) * 65536) + (i32((pl_clamp01(g) * bitcast<f32>(1132396544u))) * 256)) + i32((pl_clamp01(b) * bitcast<f32>(1132396544u))));
}
fn pl_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / pl_width) * pl_width));
  let py = (gid / pl_width);
  let fx = (f32(f32((px - pl_half_w))) / bitcast<f32>(1136656384u));
  let fy = (f32(f32((pl_half_h - py))) / bitcast<f32>(1136656384u));
  let rl = sqrt((((fx * fx) + (fy * fy)) + bitcast<f32>(1082130432u)));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (bitcast<f32>(1073741824u) / rl);
  let oz = (bitcast<f32>(0u) - bitcast<f32>(1084227584u));
  let id = pl_nearest(bitcast<f32>(0u), bitcast<f32>(0u), oz, dx, dy, dz, 0, (0 - 1), (bitcast<f32>(0u) - bitcast<f32>(1065353216u)));
  if ((id < 0)) {
  let h = pl_clamp01(((dy * bitcast<f32>(1056964608u)) + bitcast<f32>(1056964608u)));
  return pl_pack((bitcast<f32>(1028443340u) + (h * bitcast<f32>(1028443340u))), (bitcast<f32>(1031127695u) + (h * bitcast<f32>(1034147594u))), (bitcast<f32>(1036831948u) + (h * bitcast<f32>(1041194024u))));
  } else {
  let t = pl_hit(bitcast<f32>(0u), bitcast<f32>(0u), oz, dx, dy, dz, id);
  let hx = (dx * t);
  let hy = (dy * t);
  let hz = (oz + (dz * t));
  let nx = ((hx - pl_cx(id)) / bitcast<f32>(1057803468u));
  let ny = (hy / bitcast<f32>(1057803468u));
  let nz = (hz / bitcast<f32>(1057803468u));
  let la = (f32(f32(frame)) / bitcast<f32>(1106247680u));
  let lx = (cos(la) * bitcast<f32>(1056964608u));
  let ly = bitcast<f32>(1060320051u);
  let lz = ((sin(la) * bitcast<f32>(1056964608u)) - bitcast<f32>(1053609164u));
  let ll = sqrt((((lx * lx) + (ly * ly)) + (lz * lz)));
  let ndl = max(bitcast<f32>(0u), ((((nx * lx) / ll) + ((ny * ly) / ll)) + ((nz * lz) / ll)));
  let vdn = (bitcast<f32>(0u) - (((dx * nx) + (dy * ny)) + (dz * nz)));
  let hlx = ((lx / ll) - dx);
  let hly = ((ly / ll) - dy);
  let hlz = ((lz / ll) - dz);
  let hl = (sqrt((((hlx * hlx) + (hly * hly)) + (hlz * hlz))) + bitcast<f32>(981668462u));
  let spec = max(bitcast<f32>(0u), ((((nx * hlx) / hl) + ((ny * hly) / hl)) + ((nz * hlz) / hl)));
  let s2 = (spec * spec);
  let s8 = (((s2 * s2) * s2) * s2);
  if ((id == 0)) {
  return pl_pack(bitcast<f32>(1057803468u), bitcast<f32>(1051931443u), bitcast<f32>(1061158912u));
  } else {
  if ((id == 1)) {
  return pl_pack((bitcast<f32>(1050253721u) * (bitcast<f32>(1045220556u) + ndl)), (bitcast<f32>(1058642329u) * (bitcast<f32>(1045220556u) + ndl)), (bitcast<f32>(1063675494u) * (bitcast<f32>(1045220556u) + ndl)));
  } else {
  if ((id == 2)) {
  return pl_pack(((bitcast<f32>(1062836633u) * ndl) + s8), ((bitcast<f32>(1056964608u) * ndl) + s8), ((bitcast<f32>(1050253721u) * ndl) + s8));
  } else {
  if ((id == 3)) {
  let band = select(select(select(bitcast<f32>(1043878379u), bitcast<f32>(1052938076u), (ndl > bitcast<f32>(1041865113u))), bitcast<f32>(1059481190u), (ndl > bitcast<f32>(1053609164u))), bitcast<f32>(1065353216u), (ndl > bitcast<f32>(1061158912u)));
  return pl_pack((bitcast<f32>(1063675494u) * band), (bitcast<f32>(1057803468u) * band), (bitcast<f32>(1051931443u) * band));
  } else {
  if ((id == 4)) {
  return pl_pack(((nx * bitcast<f32>(1056964608u)) + bitcast<f32>(1056964608u)), ((ny * bitcast<f32>(1056964608u)) + bitcast<f32>(1056964608u)), ((nz * bitcast<f32>(1056964608u)) + bitcast<f32>(1056964608u)));
  } else {
  let fres = pl_clamp01((bitcast<f32>(1065353216u) - vdn));
  let f5 = ((((fres * fres) * fres) * fres) * fres);
  return pl_pack((bitcast<f32>(1036831948u) + (f5 * bitcast<f32>(1063675494u))), (bitcast<f32>(1041865113u) + (f5 * bitcast<f32>(1062836633u))), (bitcast<f32>(1048576000u) + (f5 * bitcast<f32>(1061158912u))));
  }
  }
  }
  }
  }
  }
}
@group(0) @binding(0) var<storage, read_write> pipelines_step_outb_buf : array<i32>;
struct U_pipelines_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_pipelines_step : U_pipelines_step;
@compute @workgroup_size(64)
fn pipelines_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_pipelines_step.frame;
  pipelines_step_outb_buf[gid] = pl_render(gid, frame);
}