// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const pl_width : i32 = 1024;
fn pl_wrap(a : i32) -> i32 {
  let m = (a - ((a / 6283) * 6283));
  if ((m < 0)) {
  return (m + 6283);
  } else {
  return m;
  }
}
fn pl_sin_core(x : i32) -> i32 {
  let x2 = ((x * x) / 1000);
  let x3 = ((x2 * x) / 1000);
  let x5 = ((x3 * x2) / 1000);
  return ((x - (x3 / 6)) + (x5 / 120));
}
fn pl_sin(raw : i32) -> i32 {
  let a = pl_wrap(raw);
  if ((a <= 1570)) {
  return pl_sin_core(a);
  } else {
  if ((a <= 3141)) {
  return pl_sin_core((3141 - a));
  } else {
  if ((a <= 4712)) {
  return (0 - pl_sin_core((a - 3141)));
  } else {
  return (0 - pl_sin_core((6283 - a)));
  }
  }
  }
}
fn pl_px(gid : i32) -> i32 {
  return (gid - ((gid / pl_width) * pl_width));
}
fn pl_py(gid : i32) -> i32 {
  return (gid / pl_width);
}
fn pl_channel(wave : i32, phase : i32, t : i32) -> i32 {
  let s = pl_sin(((wave + phase) + t));
  return (128 + ((s * 118) / 1000));
}
fn pl_color(gid : i32, frame : i32) -> i32 {
  let px = pl_px(gid);
  let py = pl_py(gid);
  let t = (frame * 24);
  let r = pl_channel(((px * 11) + (py * 4)), 0, t);
  let g = pl_channel((py * 12), 2094, (t + (t / 2)));
  let b = pl_channel((((px + py) * 7) + (pl_sin(((px * 5) + t)) * 3)), 4188, t);
  return (((r * 65536) + (g * 256)) + b);
}
@group(0) @binding(0) var<storage, read_write> plasma_step_outb_buf : array<i32>;
struct U_plasma_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_plasma_step : U_plasma_step;
@compute @workgroup_size(64)
fn plasma_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_plasma_step.frame;
  plasma_step_outb_buf[gid] = pl_color(gid, frame);
}