// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const rm_width : i32 = 1024;
const rm_half_w : i32 = 512;
const rm_half_h : i32 = 384;
const rm_steps : i32 = 80;
fn rm_sphere(px : f32, py : f32, pz : f32) -> f32 {
  return (sqrt((((px * px) + (py * py)) + (pz * pz))) - bitcast<f32>(1065353216u));
}
fn rm_scene(px : f32, py : f32, pz : f32) -> f32 {
  return min(rm_sphere(px, py, pz), (py + bitcast<f32>(1066192076u)));
}
fn rm_march(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, t__a : f32, i__a : i32) -> f32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var t = t__a;
  var i = i__a;
  loop {
    if ((i >= rm_steps)) {
    return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
    } else {
    let px = (ox + (dx * t));
    let py = (oy + (dy * t));
    let pz = (oz + (dz * t));
    let d = rm_scene(px, py, pz);
    if ((d < bitcast<f32>(990057070u))) {
    return t;
    } else {
    if ((t > bitcast<f32>(1106247680u))) {
    return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (t + d);
    let _mv7 = (i + 1);
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    t = _mv6;
    i = _mv7;
    continue;
    }
    }
    }
  }
}
fn rm_clamp01(x : f32) -> f32 {
  return max(bitcast<f32>(0u), min(bitcast<f32>(1065353216u), x));
}
fn rm_pack(r : f32, g : f32, b : f32) -> i32 {
  let ri = i32((rm_clamp01(r) * bitcast<f32>(1132396544u)));
  let gi = i32((rm_clamp01(g) * bitcast<f32>(1132396544u)));
  let bi = i32((rm_clamp01(b) * bitcast<f32>(1132396544u)));
  return (((ri * 65536) + (gi * 256)) + bi);
}
fn rm_sky(fy : f32) -> i32 {
  let h = rm_clamp01(((fy * bitcast<f32>(1056964608u)) + bitcast<f32>(1056964608u)));
  return rm_pack((bitcast<f32>(1036831948u) + (h * bitcast<f32>(1036831948u))), (bitcast<f32>(1042536202u) + (h * bitcast<f32>(1047904911u))), (bitcast<f32>(1052266987u) + (h * bitcast<f32>(1054280253u))));
}
fn rm_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / rm_width) * rm_width));
  let py = (gid / rm_width);
  let fx = (f32(f32((px - rm_half_w))) / bitcast<f32>(1136656384u));
  let fy = (f32(f32((rm_half_h - py))) / bitcast<f32>(1136656384u));
  let rl = sqrt((((fx * fx) + (fy * fy)) + bitcast<f32>(1074790400u)));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (bitcast<f32>(1069547520u) / rl);
  let oz = (bitcast<f32>(0u) - bitcast<f32>(1080033280u));
  let t = rm_march(bitcast<f32>(0u), bitcast<f32>(0u), oz, dx, dy, dz, bitcast<f32>(0u), 0);
  if ((t < bitcast<f32>(0u))) {
  return rm_sky(fy);
  } else {
  let hx = (dx * t);
  let hy = (dy * t);
  let hz = (oz + (dz * t));
  let e = bitcast<f32>(990057070u);
  let nx = (rm_scene((hx + e), hy, hz) - rm_scene((hx - e), hy, hz));
  let ny = (rm_scene(hx, (hy + e), hz) - rm_scene(hx, (hy - e), hz));
  let nz = (rm_scene(hx, hy, (hz + e)) - rm_scene(hx, hy, (hz - e)));
  let nl = (sqrt((((nx * nx) + (ny * ny)) + (nz * nz))) + bitcast<f32>(953267991u));
  let ux = (nx / nl);
  let uy = (ny / nl);
  let uz = (nz / nl);
  let ang = (f32(f32(frame)) / bitcast<f32>(1103101952u));
  let ldx = cos(ang);
  let ldy = bitcast<f32>(1061158912u);
  let ldz = sin(ang);
  let ll = sqrt((((ldx * ldx) + (ldy * ldy)) + (ldz * ldz)));
  let diff = max(bitcast<f32>(0u), ((((ux * ldx) / ll) + ((uy * ldy) / ll)) + ((uz * ldz) / ll)));
  let sh = ((diff * bitcast<f32>(1062836633u)) + bitcast<f32>(1041865113u));
  if ((hy < (bitcast<f32>(0u) - bitcast<f32>(1065353216u)))) {
  return rm_pack((bitcast<f32>(1055286886u) * sh), (bitcast<f32>(1055957975u) * sh), (bitcast<f32>(1057300152u) * sh));
  } else {
  return rm_pack((bitcast<f32>(1064514355u) * sh), (bitcast<f32>(1057803468u) * sh), (bitcast<f32>(1048576000u) * sh));
  }
  }
}
@group(0) @binding(0) var<storage, read_write> raymarch_step_outb_buf : array<i32>;
struct U_raymarch_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_raymarch_step : U_raymarch_step;
@compute @workgroup_size(64)
fn raymarch_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_raymarch_step.frame;
  raymarch_step_outb_buf[gid] = rm_render(gid, frame);
}