// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const rt_width : i32 = 1024;
const rt_half_w : i32 = 512;
const rt_half_h : i32 = 384;
const rt_nobj : i32 = 4;
fn rt_cx(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(0u);
  } else {
  if ((i == 1)) {
  return (bitcast<f32>(0u) - bitcast<f32>(1071225241u));
  } else {
  return bitcast<f32>(1070386380u);
  }
  }
}
fn rt_cy(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(0u);
  } else {
  if ((i == 1)) {
  return (bitcast<f32>(0u) - bitcast<f32>(1051931443u));
  } else {
  return (bitcast<f32>(0u) - bitcast<f32>(1055286886u));
  }
  }
}
fn rt_cz(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(0u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1056964608u);
  } else {
  return (bitcast<f32>(0u) - bitcast<f32>(1053609164u));
  }
  }
}
fn rt_rad(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1065353216u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1059481190u);
  } else {
  return bitcast<f32>(1057803468u);
  }
  }
}
fn rt_col_r(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1064514355u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1045220556u);
  } else {
  return bitcast<f32>(1060320051u);
  }
  }
}
fn rt_col_g(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1055286886u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1061997772u);
  } else {
  return bitcast<f32>(1051931443u);
  }
  }
}
fn rt_col_b(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1046562734u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1061158912u);
  } else {
  return bitcast<f32>(1064514355u);
  }
  }
}
fn rt_sphere_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, i : i32) -> f32 {
  let lx = (ox - rt_cx(i));
  let ly = (oy - rt_cy(i));
  let lz = (oz - rt_cz(i));
  let b = (((dx * lx) + (dy * ly)) + (dz * lz));
  let r = rt_rad(i);
  let c = ((((lx * lx) + (ly * ly)) + (lz * lz)) - (r * r));
  let disc = ((b * b) - c);
  if ((disc < bitcast<f32>(0u))) {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  } else {
  let t = ((bitcast<f32>(0u) - b) - sqrt(disc));
  if ((t > bitcast<f32>(981668462u))) {
  return t;
  } else {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  }
  }
}
fn rt_plane_hit(oy : f32, dy : f32) -> f32 {
  if ((dy > (bitcast<f32>(0u) - bitcast<f32>(953267991u)))) {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  } else {
  let t = (((bitcast<f32>(0u) - bitcast<f32>(1065353216u)) - oy) / dy);
  if ((t > bitcast<f32>(981668462u))) {
  return t;
  } else {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  }
  }
}
fn rt_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, id : i32) -> f32 {
  if ((id == 3)) {
  return rt_plane_hit(oy, dy);
  } else {
  return rt_sphere_hit(ox, oy, oz, dx, dy, dz, id);
  }
}
fn rt_nearest(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, best_id__a : i32, best_t__a : f32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var best_id = best_id__a;
  var best_t = best_t__a;
  loop {
    if ((i >= rt_nobj)) {
    return best_id;
    } else {
    let t = rt_hit(ox, oy, oz, dx, dy, dz, i);
    let take = select(0, select(select(0, 1, (t < best_t)), 1, (best_t < bitcast<f32>(0u))), (t > bitcast<f32>(981668462u)));
    if ((take == 1)) {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = i;
    let _mv8 = t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = best_id;
    let _mv8 = best_t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    }
    }
  }
}
fn rt_shadowed(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  loop {
    if ((i >= 3)) {
    return 0;
    } else {
    let t = rt_sphere_hit(ox, oy, oz, dx, dy, dz, i);
    if ((t > bitcast<f32>(981668462u))) {
    return 1;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    continue;
    }
    }
  }
}
fn rt_clamp01(x : f32) -> f32 {
  return max(bitcast<f32>(0u), min(bitcast<f32>(1065353216u), x));
}
fn rt_pack(r : f32, g : f32, b : f32) -> i32 {
  let ri = i32((rt_clamp01(r) * bitcast<f32>(1132396544u)));
  let gi = i32((rt_clamp01(g) * bitcast<f32>(1132396544u)));
  let bi = i32((rt_clamp01(b) * bitcast<f32>(1132396544u)));
  return (((ri * 65536) + (gi * 256)) + bi);
}
fn rt_sky(dy : f32) -> i32 {
  let h = rt_clamp01(((dy * bitcast<f32>(1056964608u)) + bitcast<f32>(1056964608u)));
  return rt_pack((bitcast<f32>(1028443340u) + (h * bitcast<f32>(1031127695u))), (bitcast<f32>(1035489771u) + (h * bitcast<f32>(1041194024u))), (bitcast<f32>(1046562734u) + (h * bitcast<f32>(1051595898u))));
}
fn rt_checker(hx : f32, hz : f32) -> f32 {
  let ix = i32((hx + bitcast<f32>(1115684864u)));
  let iz = i32((hz + bitcast<f32>(1115684864u)));
  let s = (ix + iz);
  if (((s - ((s / 2) * 2)) == 0)) {
  return bitcast<f32>(1050924810u);
  } else {
  return bitcast<f32>(1058977873u);
  }
}
fn rt_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / rt_width) * rt_width));
  let py = (gid / rt_width);
  let fx = (f32(f32((px - rt_half_w))) / bitcast<f32>(1136656384u));
  let fy = (f32(f32((rt_half_h - py))) / bitcast<f32>(1136656384u));
  let rl = sqrt((((fx * fx) + (fy * fy)) + bitcast<f32>(1077474754u)));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (bitcast<f32>(1071225241u) / rl);
  let ox = bitcast<f32>(0u);
  let oy = bitcast<f32>(1060320051u);
  let oz = (bitcast<f32>(0u) - bitcast<f32>(1082130432u));
  let id = rt_nearest(ox, oy, oz, dx, dy, dz, 0, (0 - 1), (bitcast<f32>(0u) - bitcast<f32>(1065353216u)));
  if ((id < 0)) {
  return rt_sky(dy);
  } else {
  let t = rt_hit(ox, oy, oz, dx, dy, dz, id);
  let hx = (ox + (dx * t));
  let hy = (oy + (dy * t));
  let hz = (oz + (dz * t));
  let nx = select(((hx - rt_cx(id)) / rt_rad(id)), bitcast<f32>(0u), (id == 3));
  let ny = select(((hy - rt_cy(id)) / rt_rad(id)), bitcast<f32>(1065353216u), (id == 3));
  let nz = select(((hz - rt_cz(id)) / rt_rad(id)), bitcast<f32>(0u), (id == 3));
  let br = select(rt_col_r(id), rt_checker(hx, hz), (id == 3));
  let bg = select(rt_col_g(id), rt_checker(hx, hz), (id == 3));
  let bb = select(rt_col_b(id), rt_checker(hx, hz), (id == 3));
  let ang = (f32(f32(frame)) / bitcast<f32>(1103101952u));
  let lx = (cos(ang) * bitcast<f32>(1058642329u));
  let ly = bitcast<f32>(1063675494u);
  let lz = (sin(ang) * bitcast<f32>(1058642329u));
  let ll = sqrt((((lx * lx) + (ly * ly)) + (lz * lz)));
  let ux = (lx / ll);
  let uy = (ly / ll);
  let uz = (lz / ll);
  let ndl = max(bitcast<f32>(0u), (((nx * ux) + (ny * uy)) + (nz * uz)));
  let sx = (hx + (nx * bitcast<f32>(990057070u)));
  let sy = (hy + (ny * bitcast<f32>(990057070u)));
  let sz = (hz + (nz * bitcast<f32>(990057070u)));
  let sh = rt_shadowed(sx, sy, sz, ux, uy, uz, 0);
  let lit = select((bitcast<f32>(1045220556u) + (ndl * bitcast<f32>(1063675494u))), bitcast<f32>(1045220556u), (sh == 1));
  return rt_pack((br * lit), (bg * lit), (bb * lit));
  }
}
@group(0) @binding(0) var<storage, read_write> raytrace_step_outb_buf : array<i32>;
struct U_raytrace_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_raytrace_step : U_raytrace_step;
@compute @workgroup_size(64)
fn raytrace_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_raytrace_step.frame;
  raytrace_step_outb_buf[gid] = rt_render(gid, frame);
}