// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const rf_width : i32 = 1024;
const rf_half_w : i32 = 512;
const rf_half_h : i32 = 384;
const rf_nobj : i32 = 4;
fn rf_cx(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(0u);
  } else {
  if ((i == 1)) {
  return (bitcast<f32>(0u) - bitcast<f32>(1071225241u));
  } else {
  return bitcast<f32>(1070386380u);
  }
  }
}
fn rf_cy(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(0u);
  } else {
  if ((i == 1)) {
  return (bitcast<f32>(0u) - bitcast<f32>(1051931443u));
  } else {
  return (bitcast<f32>(0u) - bitcast<f32>(1055286886u));
  }
  }
}
fn rf_cz(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(0u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1056964608u);
  } else {
  return (bitcast<f32>(0u) - bitcast<f32>(1053609164u));
  }
  }
}
fn rf_rad(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1065353216u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1059481190u);
  } else {
  return bitcast<f32>(1057803468u);
  }
  }
}
fn rf_col_r(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1064514355u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1048576000u);
  } else {
  return bitcast<f32>(1061158912u);
  }
  }
}
fn rf_col_g(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1057803468u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1062836633u);
  } else {
  return bitcast<f32>(1053609164u);
  }
  }
}
fn rf_col_b(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1050253721u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1061997772u);
  } else {
  return bitcast<f32>(1065017671u);
  }
  }
}
fn rf_refl(i : i32) -> f32 {
  if ((i == 3)) {
  return bitcast<f32>(1050253721u);
  } else {
  return bitcast<f32>(1057803468u);
  }
}
fn rf_sphere_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, i : i32) -> f32 {
  let lx = (ox - rf_cx(i));
  let ly = (oy - rf_cy(i));
  let lz = (oz - rf_cz(i));
  let b = (((dx * lx) + (dy * ly)) + (dz * lz));
  let r = rf_rad(i);
  let c = ((((lx * lx) + (ly * ly)) + (lz * lz)) - (r * r));
  let disc = ((b * b) - c);
  if ((disc < bitcast<f32>(0u))) {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  } else {
  let t = ((bitcast<f32>(0u) - b) - sqrt(disc));
  if ((t > bitcast<f32>(981668462u))) {
  return t;
  } else {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  }
  }
}
fn rf_plane_hit(oy : f32, dy : f32) -> f32 {
  if ((dy > (bitcast<f32>(0u) - bitcast<f32>(953267991u)))) {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  } else {
  let t = (((bitcast<f32>(0u) - bitcast<f32>(1065353216u)) - oy) / dy);
  if ((t > bitcast<f32>(981668462u))) {
  return t;
  } else {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  }
  }
}
fn rf_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, id : i32) -> f32 {
  if ((id == 3)) {
  return rf_plane_hit(oy, dy);
  } else {
  return rf_sphere_hit(ox, oy, oz, dx, dy, dz, id);
  }
}
fn rf_nearest(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, best_id__a : i32, best_t__a : f32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var best_id = best_id__a;
  var best_t = best_t__a;
  loop {
    if ((i >= rf_nobj)) {
    return best_id;
    } else {
    let t = rf_hit(ox, oy, oz, dx, dy, dz, i);
    let take = select(0, select(select(0, 1, (t < best_t)), 1, (best_t < bitcast<f32>(0u))), (t > bitcast<f32>(981668462u)));
    if ((take == 1)) {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = i;
    let _mv8 = t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = best_id;
    let _mv8 = best_t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best_id = _mv7;
    best_t = _mv8;
    continue;
    }
    }
  }
}
fn rf_shadowed(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  loop {
    if ((i >= 3)) {
    return 0;
    } else {
    let t = rf_sphere_hit(ox, oy, oz, dx, dy, dz, i);
    if ((t > bitcast<f32>(981668462u))) {
    return 1;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    continue;
    }
    }
  }
}
fn rf_clamp01(x : f32) -> f32 {
  return max(bitcast<f32>(0u), min(bitcast<f32>(1065353216u), x));
}
fn rf_pack(r : f32, g : f32, b : f32) -> i32 {
  let ri = i32((rf_clamp01(r) * bitcast<f32>(1132396544u)));
  let gi = i32((rf_clamp01(g) * bitcast<f32>(1132396544u)));
  let bi = i32((rf_clamp01(b) * bitcast<f32>(1132396544u)));
  return (((ri * 65536) + (gi * 256)) + bi);
}
fn rf_sky(dy : f32) -> i32 {
  let h = rf_clamp01(((dy * bitcast<f32>(1056964608u)) + bitcast<f32>(1056964608u)));
  return rf_pack((bitcast<f32>(1028443340u) + (h * bitcast<f32>(1031127695u))), (bitcast<f32>(1036831948u) + (h * bitcast<f32>(1042536202u))), (bitcast<f32>(1047904911u) + (h * bitcast<f32>(1053609164u))));
}
fn rf_checker(hx : f32, hz : f32) -> f32 {
  let ix = i32((hx + bitcast<f32>(1115684864u)));
  let iz = i32((hz + bitcast<f32>(1115684864u)));
  let s = (ix + iz);
  if (((s - ((s / 2) * 2)) == 0)) {
  return bitcast<f32>(1051931443u);
  } else {
  return bitcast<f32>(1059481190u);
  }
}
fn rf_un_r(p : i32) -> f32 {
  return (f32(f32((p / 65536))) / bitcast<f32>(1132396544u));
}
fn rf_un_g(p : i32) -> f32 {
  return (f32(f32(((p / 256) - ((p / 65536) * 256)))) / bitcast<f32>(1132396544u));
}
fn rf_un_b(p : i32) -> f32 {
  return (f32(f32((p - ((p / 256) * 256)))) / bitcast<f32>(1132396544u));
}
fn rf_local(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, id : i32, frame : i32) -> i32 {
  let t = rf_hit(ox, oy, oz, dx, dy, dz, id);
  let hx = (ox + (dx * t));
  let hy = (oy + (dy * t));
  let hz = (oz + (dz * t));
  let nx = select(((hx - rf_cx(id)) / rf_rad(id)), bitcast<f32>(0u), (id == 3));
  let ny = select(((hy - rf_cy(id)) / rf_rad(id)), bitcast<f32>(1065353216u), (id == 3));
  let nz = select(((hz - rf_cz(id)) / rf_rad(id)), bitcast<f32>(0u), (id == 3));
  let br = select(rf_col_r(id), rf_checker(hx, hz), (id == 3));
  let bg = select(rf_col_g(id), rf_checker(hx, hz), (id == 3));
  let bb = select(rf_col_b(id), rf_checker(hx, hz), (id == 3));
  let ang = (f32(f32(frame)) / bitcast<f32>(1103101952u));
  let lx = (cos(ang) * bitcast<f32>(1058642329u));
  let ly = bitcast<f32>(1063675494u);
  let lz = (sin(ang) * bitcast<f32>(1058642329u));
  let ll = sqrt((((lx * lx) + (ly * ly)) + (lz * lz)));
  let ux = (lx / ll);
  let uy = (ly / ll);
  let uz = (lz / ll);
  let ndl = max(bitcast<f32>(0u), (((nx * ux) + (ny * uy)) + (nz * uz)));
  let sh = rf_shadowed((hx + (nx * bitcast<f32>(990057070u))), (hy + (ny * bitcast<f32>(990057070u))), (hz + (nz * bitcast<f32>(990057070u))), ux, uy, uz, 0);
  let lit = select((bitcast<f32>(1046562734u) + (ndl * bitcast<f32>(1063675494u))), bitcast<f32>(1046562734u), (sh == 1));
  return rf_pack((br * lit), (bg * lit), (bb * lit));
}
fn rf_render(gid : i32, frame : i32) -> i32 {
  let px = (gid - ((gid / rf_width) * rf_width));
  let py = (gid / rf_width);
  let fx = (f32(f32((px - rf_half_w))) / bitcast<f32>(1136656384u));
  let fy = (f32(f32((rf_half_h - py))) / bitcast<f32>(1136656384u));
  let rl = sqrt((((fx * fx) + (fy * fy)) + bitcast<f32>(1077474754u)));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (bitcast<f32>(1071225241u) / rl);
  let ox = bitcast<f32>(0u);
  let oy = bitcast<f32>(1060320051u);
  let oz = (bitcast<f32>(0u) - bitcast<f32>(1082130432u));
  let id0 = rf_nearest(ox, oy, oz, dx, dy, dz, 0, (0 - 1), (bitcast<f32>(0u) - bitcast<f32>(1065353216u)));
  if ((id0 < 0)) {
  return rf_sky(dy);
  } else {
  let t0 = rf_hit(ox, oy, oz, dx, dy, dz, id0);
  let hx = (ox + (dx * t0));
  let hy = (oy + (dy * t0));
  let hz = (oz + (dz * t0));
  let nx = select(((hx - rf_cx(id0)) / rf_rad(id0)), bitcast<f32>(0u), (id0 == 3));
  let ny = select(((hy - rf_cy(id0)) / rf_rad(id0)), bitcast<f32>(1065353216u), (id0 == 3));
  let nz = select(((hz - rf_cz(id0)) / rf_rad(id0)), bitcast<f32>(0u), (id0 == 3));
  let p0 = rf_local(ox, oy, oz, dx, dy, dz, id0, frame);
  let dn = (((dx * nx) + (dy * ny)) + (dz * nz));
  let rx = (dx - ((bitcast<f32>(1073741824u) * dn) * nx));
  let ry = (dy - ((bitcast<f32>(1073741824u) * dn) * ny));
  let rz = (dz - ((bitcast<f32>(1073741824u) * dn) * nz));
  let sx = (hx + (nx * bitcast<f32>(994352037u)));
  let sy = (hy + (ny * bitcast<f32>(994352037u)));
  let sz = (hz + (nz * bitcast<f32>(994352037u)));
  let id1 = rf_nearest(sx, sy, sz, rx, ry, rz, 0, (0 - 1), (bitcast<f32>(0u) - bitcast<f32>(1065353216u)));
  let pr = select(rf_local(sx, sy, sz, rx, ry, rz, id1, frame), rf_sky(ry), (id1 < 0));
  let k = rf_refl(id0);
  let cr = ((rf_un_r(p0) * (bitcast<f32>(1065353216u) - k)) + (rf_un_r(pr) * k));
  let cg = ((rf_un_g(p0) * (bitcast<f32>(1065353216u) - k)) + (rf_un_g(pr) * k));
  let cb = ((rf_un_b(p0) * (bitcast<f32>(1065353216u) - k)) + (rf_un_b(pr) * k));
  return rf_pack(cr, cg, cb);
  }
}
@group(0) @binding(0) var<storage, read_write> reflect_step_outb_buf : array<i32>;
struct U_reflect_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_reflect_step : U_reflect_step;
@compute @workgroup_size(64)
fn reflect_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_reflect_step.frame;
  reflect_step_outb_buf[gid] = rf_render(gid, frame);
}