// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const sc_width : i32 = 1024;
const sc_half_w : i32 = 512;
const sc_half_h : i32 = 384;
const sc_count : i32 = 3;
const sc_far : i32 = 8000000;
const sc_size : f32 = bitcast<f32>(1088421888u);
const sc_dist : f32 = bitcast<f32>(1088421888u);
fn sc_cx(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(0u);
  } else {
  if ((i == 1)) {
  return (bitcast<f32>(0u) - bitcast<f32>(1069547520u));
  } else {
  return bitcast<f32>(1068708659u);
  }
  }
}
fn sc_cy(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1065772646u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1058642329u);
  } else {
  return bitcast<f32>(1061158912u);
  }
  }
}
fn sc_cz(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(0u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1058642329u);
  } else {
  return (bitcast<f32>(0u) - bitcast<f32>(1056964608u));
  }
  }
}
fn sc_rad(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1062836633u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1058642329u);
  } else {
  return bitcast<f32>(1059481190u);
  }
  }
}
fn sc_colr(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1063675494u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1051931443u);
  } else {
  return bitcast<f32>(1061158912u);
  }
  }
}
fn sc_colg(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1057803468u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1061158912u);
  } else {
  return bitcast<f32>(1053609164u);
  }
  }
}
fn sc_colb(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1050253721u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1057803468u);
  } else {
  return bitcast<f32>(1064514355u);
  }
  }
}
fn sc_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, i : i32) -> f32 {
  let lx = (ox - sc_cx(i));
  let ly = (oy - sc_cy(i));
  let lz = (oz - sc_cz(i));
  let b = (((dx * lx) + (dy * ly)) + (dz * lz));
  let r = sc_rad(i);
  let c = ((((lx * lx) + (ly * ly)) + (lz * lz)) - (r * r));
  let disc = ((b * b) - c);
  if ((disc < bitcast<f32>(0u))) {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  } else {
  let t = ((bitcast<f32>(0u) - b) - sqrt(disc));
  if ((t > bitcast<f32>(981668462u))) {
  return t;
  } else {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  }
  }
}
fn sc_nearest(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, bid__a : i32, bt__a : f32) -> i32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var bid = bid__a;
  var bt = bt__a;
  loop {
    if ((i >= sc_count)) {
    return bid;
    } else {
    let t = sc_hit(ox, oy, oz, dx, dy, dz, i);
    let take = select(0, select(select(0, 1, (t < bt)), 1, (bt < bitcast<f32>(0u))), (t > bitcast<f32>(981668462u)));
    if ((take == 1)) {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = i;
    let _mv8 = t;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    bid = _mv7;
    bt = _mv8;
    continue;
    } else {
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = bid;
    let _mv8 = bt;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    bid = _mv7;
    bt = _mv8;
    continue;
    }
    }
  }
}
fn sc_clampi(v : i32, lo : i32, hi : i32) -> i32 {
  if ((v < lo)) {
  return lo;
  } else {
  if ((v > hi)) {
  return hi;
  } else {
  return v;
  }
  }
}
fn sc_pack(r : f32, g : f32, b : f32) -> i32 {
  let ri = sc_clampi(i32((r * bitcast<f32>(1132396544u))), 0, 255);
  let gi = sc_clampi(i32((g * bitcast<f32>(1132396544u))), 0, 255);
  let bi = sc_clampi(i32((b * bitcast<f32>(1132396544u))), 0, 255);
  return (((ri * 65536) + (gi * 256)) + bi);
}
fn sc_checker(x : f32, z : f32) -> f32 {
  let ix = i32((x + bitcast<f32>(1115684864u)));
  let iz = i32((z + bitcast<f32>(1115684864u)));
  let s = (ix + iz);
  if (((s - ((s / 2) * 2)) == 0)) {
  return bitcast<f32>(1050253721u);
  } else {
  return bitcast<f32>(1057803468u);
  }
}
@group(0) @binding(0) var<storage, read_write> shadowmain_step_shadowbuf_buf : array<i32>;
@group(0) @binding(1) var<storage, read_write> shadowmain_step_outb_buf : array<i32>;
struct U_shadowmain_step {
  frame : i32,
}
@group(0) @binding(2) var<uniform> u_shadowmain_step : U_shadowmain_step;
@compute @workgroup_size(64)
fn shadowmain_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_shadowmain_step.frame;
  let px = (gid - ((gid / sc_width) * sc_width));
  let py = (gid / sc_width);
  let fx = (f32(f32((px - sc_half_w))) / bitcast<f32>(1136656384u));
  let fy = ((f32(f32((sc_half_h - py))) / bitcast<f32>(1136656384u)) - bitcast<f32>(1039516303u));
  let rl = sqrt((((fx * fx) + (fy * fy)) + bitcast<f32>(1076090634u)));
  let dx = (fx / rl);
  let dy = (fy / rl);
  let dz = (bitcast<f32>(1070386380u) / rl);
  let ox = bitcast<f32>(0u);
  let oy = bitcast<f32>(1071225241u);
  let oz = (bitcast<f32>(0u) - bitcast<f32>(1086324736u));
  let sid = sc_nearest(ox, oy, oz, dx, dy, dz, 0, (0 - 1), (bitcast<f32>(0u) - bitcast<f32>(1065353216u)));
  let st = select(sc_hit(ox, oy, oz, dx, dy, dz, sid), bitcast<f32>(1148846080u), (sid < 0));
  let ft = select((bitcast<f32>(0u) - bitcast<f32>(1065353216u)), (((bitcast<f32>(0u) - bitcast<f32>(1065353216u)) - oy) / dy), (dy < (bitcast<f32>(0u) - bitcast<f32>(953267991u))));
  let usefloor = select(0, select(select(0, 1, (ft < st)), 1, (sid < 0)), (ft > bitcast<f32>(981668462u)));
  let hitany = select(select(0, 1, (sid >= 0)), 1, (usefloor == 1));
  if ((hitany == 0)) {
  _ = (((6 * 65536) + (10 * 256)) + 20);
  } else {
  let t = select(st, ft, (usefloor == 1));
  let hx = (ox + (dx * t));
  let hy = (oy + (dy * t));
  let hz = (oz + (dz * t));
  let nx = select(((hx - sc_cx(sid)) / sc_rad(sid)), bitcast<f32>(0u), (usefloor == 1));
  let ny = select(((hy - sc_cy(sid)) / sc_rad(sid)), bitcast<f32>(1065353216u), (usefloor == 1));
  let nz = select(((hz - sc_cz(sid)) / sc_rad(sid)), bitcast<f32>(0u), (usefloor == 1));
  let ar = select(sc_colr(sid), sc_checker(hx, hz), (usefloor == 1));
  let ag = select(sc_colg(sid), sc_checker(hx, hz), (usefloor == 1));
  let ab = select(sc_colb(sid), sc_checker(hx, hz), (usefloor == 1));
  let la = (f32(f32(frame)) / bitcast<f32>(1109393408u));
  let rlx = (cos(la) * bitcast<f32>(1058977873u));
  let rlz = (sin(la) * bitcast<f32>(1058977873u));
  let ll = sqrt((((rlx * rlx) + bitcast<f32>(1058783258u)) + (rlz * rlz)));
  let lx = (rlx / ll);
  let ly = ((bitcast<f32>(0u) - bitcast<f32>(1061662228u)) / ll);
  let lz = (rlz / ll);
  let rgl = sqrt(((lz * lz) + (lx * lx)));
  let rx = (lz / rgl);
  let rz = (bitcast<f32>(0u) - (lx / rgl));
  let ux = (ly * rz);
  let uy = ((lz * rx) - (lx * rz));
  let uz = (bitcast<f32>(0u) - (ly * rx));
  let rcx = (hx - bitcast<f32>(0u));
  let rcy = (hy - bitcast<f32>(1051931443u));
  let rcz = (hz - bitcast<f32>(0u));
  let lu = ((((rcx * rx) + (rcz * rz)) / sc_size) + bitcast<f32>(1056964608u));
  let lv = (((((rcx * ux) + (rcy * uy)) + (rcz * uz)) / sc_size) + bitcast<f32>(1056964608u));
  let ld = ((((rcx * lx) + (rcy * ly)) + (rcz * lz)) + sc_dist);
  let stored = shadowmain_step_shadowbuf_buf[((sc_clampi(i32((lv * bitcast<f32>(1149239296u))), 0, 1023) * 1024) + sc_clampi(i32((lu * bitcast<f32>(1149239296u))), 0, 1023))];
  let inmap = select(0, select(0, select(0, select(0, 1, (lv < bitcast<f32>(1065353216u))), (lv > bitcast<f32>(0u))), (lu < bitcast<f32>(1065353216u))), (lu > bitcast<f32>(0u)));
  let shadowed = select(0, select(0, select(0, 1, (i32((ld * bitcast<f32>(1132462080u))) > (stored + 500))), (stored < sc_far)), (inmap == 1));
  let ndl = max(bitcast<f32>(0u), (bitcast<f32>(0u) - (((nx * lx) + (ny * ly)) + (nz * lz))));
  let vis = select(bitcast<f32>(1065353216u), bitcast<f32>(1043878379u), (shadowed == 1));
  let sh = (bitcast<f32>(1045220556u) + ((ndl * bitcast<f32>(1062836633u)) * vis));
  shadowmain_step_outb_buf[gid] = sc_pack((ar * sh), (ag * sh), (ab * sh));
  }
}