// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const sm_res : i32 = 1024;
const sm_count : i32 = 3;
const sm_far : i32 = 8000000;
const sm_size : f32 = bitcast<f32>(1088421888u);
const sm_dist : f32 = bitcast<f32>(1088421888u);
fn sm_cx(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(0u);
  } else {
  if ((i == 1)) {
  return (bitcast<f32>(0u) - bitcast<f32>(1069547520u));
  } else {
  return bitcast<f32>(1068708659u);
  }
  }
}
fn sm_cy(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1065772646u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1058642329u);
  } else {
  return bitcast<f32>(1061158912u);
  }
  }
}
fn sm_cz(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(0u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1058642329u);
  } else {
  return (bitcast<f32>(0u) - bitcast<f32>(1056964608u));
  }
  }
}
fn sm_rad(i : i32) -> f32 {
  if ((i == 0)) {
  return bitcast<f32>(1062836633u);
  } else {
  if ((i == 1)) {
  return bitcast<f32>(1058642329u);
  } else {
  return bitcast<f32>(1059481190u);
  }
  }
}
fn sm_hit(ox : f32, oy : f32, oz : f32, dx : f32, dy : f32, dz : f32, i : i32) -> f32 {
  let lx = (ox - sm_cx(i));
  let ly = (oy - sm_cy(i));
  let lz = (oz - sm_cz(i));
  let b = (((dx * lx) + (dy * ly)) + (dz * lz));
  let r = sm_rad(i);
  let c = ((((lx * lx) + (ly * ly)) + (lz * lz)) - (r * r));
  let disc = ((b * b) - c);
  if ((disc < bitcast<f32>(0u))) {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  } else {
  let t = ((bitcast<f32>(0u) - b) - sqrt(disc));
  if ((t > bitcast<f32>(0u))) {
  return t;
  } else {
  return (bitcast<f32>(0u) - bitcast<f32>(1065353216u));
  }
  }
}
fn sm_nearest(ox__a : f32, oy__a : f32, oz__a : f32, dx__a : f32, dy__a : f32, dz__a : f32, i__a : i32, best__a : f32) -> f32 {
  var ox = ox__a;
  var oy = oy__a;
  var oz = oz__a;
  var dx = dx__a;
  var dy = dy__a;
  var dz = dz__a;
  var i = i__a;
  var best = best__a;
  loop {
    if ((i >= sm_count)) {
    return best;
    } else {
    let t = sm_hit(ox, oy, oz, dx, dy, dz, i);
    let nb = select(best, select(select(best, t, (t < best)), t, (best < bitcast<f32>(0u))), (t > bitcast<f32>(0u)));
    let _mv0 = ox;
    let _mv1 = oy;
    let _mv2 = oz;
    let _mv3 = dx;
    let _mv4 = dy;
    let _mv5 = dz;
    let _mv6 = (i + 1);
    let _mv7 = nb;
    ox = _mv0;
    oy = _mv1;
    oz = _mv2;
    dx = _mv3;
    dy = _mv4;
    dz = _mv5;
    i = _mv6;
    best = _mv7;
    continue;
    }
  }
}
@group(0) @binding(0) var<storage, read_write> shadowmap_step_shadowbuf_buf : array<i32>;
struct U_shadowmap_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_shadowmap_step : U_shadowmap_step;
@compute @workgroup_size(64)
fn shadowmap_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_shadowmap_step.frame;
  let tu = (f32(f32((gid - ((gid / sm_res) * sm_res)))) / bitcast<f32>(1149239296u));
  let tv = (f32(f32((gid / sm_res))) / bitcast<f32>(1149239296u));
  let la = (f32(f32(frame)) / bitcast<f32>(1109393408u));
  let rlx = (cos(la) * bitcast<f32>(1058977873u));
  let rlz = (sin(la) * bitcast<f32>(1058977873u));
  let ll = sqrt((((rlx * rlx) + bitcast<f32>(1058783258u)) + (rlz * rlz)));
  let lx = (rlx / ll);
  let ly = ((bitcast<f32>(0u) - bitcast<f32>(1061662228u)) / ll);
  let lz = (rlz / ll);
  let rgl = sqrt(((lz * lz) + (lx * lx)));
  let rx = (lz / rgl);
  let ry = bitcast<f32>(0u);
  let rz = (bitcast<f32>(0u) - (lx / rgl));
  let ux = ((ly * rz) - (lz * ry));
  let uy = ((lz * rx) - (lx * rz));
  let uz = ((lx * ry) - (ly * rx));
  let ox = (((bitcast<f32>(0u) - (lx * sm_dist)) + (((tu - bitcast<f32>(1056964608u)) * sm_size) * rx)) + (((tv - bitcast<f32>(1056964608u)) * sm_size) * ux));
  let oy = (((bitcast<f32>(1051931443u) - (ly * sm_dist)) + (((tu - bitcast<f32>(1056964608u)) * sm_size) * ry)) + (((tv - bitcast<f32>(1056964608u)) * sm_size) * uy));
  let oz = (((bitcast<f32>(0u) - (lz * sm_dist)) + (((tu - bitcast<f32>(1056964608u)) * sm_size) * rz)) + (((tv - bitcast<f32>(1056964608u)) * sm_size) * uz));
  let t = sm_nearest(ox, oy, oz, lx, ly, lz, 0, (bitcast<f32>(0u) - bitcast<f32>(1065353216u)));
  let depv = select(i32((t * bitcast<f32>(1132462080u))), sm_far, (t < bitcast<f32>(0u)));
  shadowmap_step_shadowbuf_buf[gid] = depv;
}