// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const ss_width : i32 = 1024;
const ss_taps : i32 = 24;
const ss_miss : i32 = 8000000;
fn ss_clampi(v : i32, lo : i32, hi : i32) -> i32 {
  if ((v < lo)) {
  return lo;
  } else {
  if ((v > hi)) {
  return hi;
  } else {
  return v;
  }
  }
}
fn ss_gather(buf : ptr<storage, array<i32>, read_write>, px__a : i32, py__a : i32, mydep__a : i32, k__a : i32, acc__a : i32) -> i32 {
  var px = px__a;
  var py = py__a;
  var mydep = mydep__a;
  var k = k__a;
  var acc = acc__a;
  loop {
    if ((k >= ss_taps)) {
    return acc;
    } else {
    let ang = (f32(f32(k)) * bitcast<f32>(1075415351u));
    let rad = (sqrt(f32(f32(k))) * bitcast<f32>(1083179008u));
    let sx = ss_clampi((px + i32((cos(ang) * rad))), 0, 1023);
    let sy = ss_clampi((py + i32((sin(ang) * rad))), 0, 767);
    let idx = ((sy * 1024) + sx);
    let ndep = (*buf)[idx];
    let diff = (mydep - ndep);
    let occ = select(0, select(0, 1, (diff < 520)), (diff > 22));
    let _mv1 = px;
    let _mv2 = py;
    let _mv3 = mydep;
    let _mv4 = (k + 1);
    let _mv5 = (acc + occ);
    px = _mv1;
    py = _mv2;
    mydep = _mv3;
    k = _mv4;
    acc = _mv5;
    continue;
    }
  }
}
@group(0) @binding(0) var<storage, read_write> ssao_step_gdep_buf : array<i32>;
@group(0) @binding(1) var<storage, read_write> ssao_step_galb_buf : array<i32>;
@group(0) @binding(2) var<storage, read_write> ssao_step_gnrm_buf : array<i32>;
@group(0) @binding(3) var<storage, read_write> ssao_step_outb_buf : array<i32>;
struct U_ssao_step {
  frame : i32,
}
@group(0) @binding(4) var<uniform> u_ssao_step : U_ssao_step;
@compute @workgroup_size(64)
fn ssao_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_ssao_step.frame;
  let px = (gid - ((gid / ss_width) * ss_width));
  let py = (gid / ss_width);
  let dep = ssao_step_gdep_buf[gid];
  let alb = ssao_step_galb_buf[gid];
  let nrm = ssao_step_gnrm_buf[gid];
  let occ = ss_gather(&ssao_step_gdep_buf, px, py, dep, 0, 0);
  let ao = max(bitcast<f32>(1043878379u), (bitcast<f32>(1065353216u) - (f32(f32(occ)) * bitcast<f32>(1033476505u))));
  let nx = ((f32(f32((nrm / 65536))) / bitcast<f32>(1123942400u)) - bitcast<f32>(1065353216u));
  let ny = ((f32(f32(((nrm / 256) - ((nrm / 65536) * 256)))) / bitcast<f32>(1123942400u)) - bitcast<f32>(1065353216u));
  let nz = ((f32(f32((nrm - ((nrm / 256) * 256)))) / bitcast<f32>(1123942400u)) - bitcast<f32>(1065353216u));
  let ang = (f32(f32(frame)) / bitcast<f32>(1106247680u));
  let lx = (cos(ang) * bitcast<f32>(1057803468u));
  let ly = bitcast<f32>(1056964608u);
  let lz = ((sin(ang) * bitcast<f32>(1057803468u)) - bitcast<f32>(1057803468u));
  let ll = sqrt((((lx * lx) + (ly * ly)) + (lz * lz)));
  let ndl = max(bitcast<f32>(0u), ((((nx * lx) / ll) + ((ny * ly) / ll)) + ((nz * lz) / ll)));
  let sh = ((bitcast<f32>(1051260354u) + (ndl * bitcast<f32>(1057300152u))) * ao);
  let ar = (alb / 65536);
  let ag = ((alb / 256) - ((alb / 65536) * 256));
  let ab = (alb - ((alb / 256) * 256));
  let out = select((((ss_clampi(i32((f32(f32(ar)) * sh)), 0, 255) * 65536) + (ss_clampi(i32((f32(f32(ag)) * sh)), 0, 255) * 256)) + ss_clampi(i32((f32(f32(ab)) * sh)), 0, 255)), ((16 * 256) + 26), (dep >= ss_miss));
  ssao_step_outb_buf[gid] = out;
}