// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const st_width : i32 = 1024;
fn st_atan2(y : f32, x : f32) -> f32 {
  let ax = select(x, (bitcast<f32>(0u) - x), (x < bitcast<f32>(0u)));
  let ay = select(y, (bitcast<f32>(0u) - y), (y < bitcast<f32>(0u)));
  let mn = min(ax, ay);
  let mx = max(ax, ay);
  let a = select(bitcast<f32>(0u), (mn / mx), (mx > bitcast<f32>(0u)));
  let a2 = (a * a);
  let base = ((a * (bitcast<f32>(1121058816u) + (bitcast<f32>(1113325568u) * a2))) / (bitcast<f32>(1121058816u) + (a2 * (bitcast<f32>(1119092736u) + (bitcast<f32>(1091567616u) * a2)))));
  let r1 = select(base, (bitcast<f32>(1070141402u) - base), (ay > ax));
  let r2 = select(r1, (bitcast<f32>(1078530010u) - r1), (x < bitcast<f32>(0u)));
  if ((y < bitcast<f32>(0u))) {
  return (bitcast<f32>(0u) - r2);
  } else {
  return r2;
  }
}
fn st_clamp01(x : f32) -> f32 {
  return max(bitcast<f32>(0u), min(bitcast<f32>(1065353216u), x));
}
fn st_pack(r : f32, g : f32, b : f32) -> i32 {
  return (((i32((st_clamp01(r) * bitcast<f32>(1132396544u))) * 65536) + (i32((st_clamp01(g) * bitcast<f32>(1132396544u))) * 256)) + i32((st_clamp01(b) * bitcast<f32>(1132396544u))));
}
fn st_render(gid : i32, frame : i32) -> i32 {
  let px = f32(f32((gid - ((gid / st_width) * st_width))));
  let py = f32(f32((gid / st_width)));
  let dx = (px - bitcast<f32>(1140850688u));
  let dy = (py - bitcast<f32>(1136656384u));
  let r = sqrt(((dx * dx) + (dy * dy)));
  let spin = (f32(f32(frame)) / bitcast<f32>(1108082688u));
  let a = (st_atan2(dy, dx) + spin);
  let rb = (bitcast<f32>(1129775104u) + (bitcast<f32>(1118437376u) * cos((a * bitcast<f32>(1084227584u)))));
  let d = (r - rb);
  if ((d > bitcast<f32>(1086324736u))) {
  return st_pack((bitcast<f32>(1025758986u) + (py / bitcast<f32>(1165623296u))), bitcast<f32>(1028443340u), bitcast<f32>(1034147594u));
  } else {
  if ((d > (bitcast<f32>(0u) - bitcast<f32>(1086324736u)))) {
  return st_pack(bitcast<f32>(1058642329u), bitcast<f32>(1064514355u), bitcast<f32>(1065353216u));
  } else {
  let t = (f32(f32(frame)) / bitcast<f32>(1101004800u));
  let sr = (bitcast<f32>(1056964608u) + (bitcast<f32>(1056964608u) * sin(((r * bitcast<f32>(1028443340u)) + t))));
  let sg = (bitcast<f32>(1056964608u) + (bitcast<f32>(1056964608u) * sin((((a * bitcast<f32>(1077936128u)) + (r * bitcast<f32>(1022739087u))) + (t * bitcast<f32>(1067869798u))))));
  let sb = (bitcast<f32>(1056964608u) + (bitcast<f32>(1056964608u) * sin(((a * bitcast<f32>(1084227584u)) - t))));
  return st_pack(sr, sg, sb);
  }
  }
}
@group(0) @binding(0) var<storage, read_write> stencil_step_outb_buf : array<i32>;
struct U_stencil_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_stencil_step : U_stencil_step;
@compute @workgroup_size(64)
fn stencil_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_stencil_step.frame;
  stencil_step_outb_buf[gid] = st_render(gid, frame);
}