// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const sw_width : i32 = 1024;
const sw_height : i32 = 768;
const sw_speed : i32 = 9;
fn sw_wrap(a : i32) -> i32 {
  let m = (a - ((a / 6283) * 6283));
  if ((m < 0)) {
  return (m + 6283);
  } else {
  return m;
  }
}
fn sw_sin_core(x : i32) -> i32 {
  let x2 = ((x * x) / 1000);
  let x3 = ((x2 * x) / 1000);
  let x5 = ((x3 * x2) / 1000);
  return ((x - (x3 / 6)) + (x5 / 120));
}
fn sw_sin(raw : i32) -> i32 {
  let a = sw_wrap(raw);
  if ((a <= 1570)) {
  return sw_sin_core(a);
  } else {
  if ((a <= 3141)) {
  return sw_sin_core((3141 - a));
  } else {
  if ((a <= 4712)) {
  return (0 - sw_sin_core((a - 3141)));
  } else {
  return (0 - sw_sin_core((6283 - a)));
  }
  }
  }
}
fn sw_cos(raw : i32) -> i32 {
  return sw_sin((raw + 1570));
}
fn sw_flow_ang(px : i32, py : i32, frame : i32) -> i32 {
  return sw_wrap((((sw_sin(((px * 5) + (frame * 4))) + sw_sin(((py * 5) - (frame * 3)))) * 3) + (frame * 2)));
}
fn sw_flow_vx(px : i32, py : i32, frame : i32) -> i32 {
  return ((sw_cos(sw_flow_ang(px, py, frame)) * sw_speed) / 1000);
}
fn sw_flow_vy(px : i32, py : i32, frame : i32) -> i32 {
  return ((sw_sin(sw_flow_ang(px, py, frame)) * sw_speed) / 1000);
}
fn sw_new_vx(px : i32, py : i32, vx : i32, frame : i32) -> i32 {
  return (((vx * 7) + sw_flow_vx(px, py, frame)) / 8);
}
fn sw_new_vy(px : i32, py : i32, vy : i32, frame : i32) -> i32 {
  return (((vy * 7) + sw_flow_vy(px, py, frame)) / 8);
}
fn sw_wrap_pos(v : i32, m : i32) -> i32 {
  let r = (v - ((v / m) * m));
  if ((r < 0)) {
  return (r + m);
  } else {
  return r;
  }
}
fn sw_new_px(px : i32, py : i32, vx : i32, frame : i32) -> i32 {
  return sw_wrap_pos((px + sw_new_vx(px, py, vx, frame)), sw_width);
}
fn sw_new_py(px : i32, py : i32, vy : i32, frame : i32) -> i32 {
  return sw_wrap_pos((py + sw_new_vy(px, py, vy, frame)), sw_height);
}
@group(0) @binding(0) var<storage, read_write> swarm_step_inb_buf : array<i32>;
@group(0) @binding(1) var<storage, read_write> swarm_step_outb_buf : array<i32>;
struct U_swarm_step {
  frame : i32,
}
@group(0) @binding(2) var<uniform> u_swarm_step : U_swarm_step;
@compute @workgroup_size(64)
fn swarm_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_swarm_step.frame;
  let px = swarm_step_inb_buf[(gid * 4)];
  let py = swarm_step_inb_buf[((gid * 4) + 1)];
  let vx = swarm_step_inb_buf[((gid * 4) + 2)];
  let vy = swarm_step_inb_buf[((gid * 4) + 3)];
  swarm_step_outb_buf[(gid * 4)] = sw_new_px(px, py, vx, frame);
  swarm_step_outb_buf[((gid * 4) + 1)] = sw_new_py(px, py, vy, frame);
  swarm_step_outb_buf[((gid * 4) + 2)] = sw_new_vx(px, py, vx, frame);
  swarm_step_outb_buf[((gid * 4) + 3)] = sw_new_vy(px, py, vy, frame);
}