// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const ta_width : i32 = 1024;
fn ta_clamp01(x : f32) -> f32 {
  return max(bitcast<f32>(0u), min(bitcast<f32>(1065353216u), x));
}
fn ta_pack(r : f32, g : f32, b : f32) -> i32 {
  return (((i32((ta_clamp01(r) * bitcast<f32>(1132396544u))) * 65536) + (i32((ta_clamp01(g) * bitcast<f32>(1132396544u))) * 256)) + i32((ta_clamp01(b) * bitcast<f32>(1132396544u))));
}
fn ta_layer(l : i32, lx : i32, ly : i32) -> f32 {
  let m = (l - ((l / 6) * 6));
  if ((m == 0)) {
  if (((((lx / 20) + (ly / 20)) - ((((lx / 20) + (ly / 20)) / 2) * 2)) == 0)) {
  return bitcast<f32>(1065353216u);
  } else {
  return bitcast<f32>(1041865113u);
  }
  } else {
  if ((m == 1)) {
  if (((lx - ((lx / 24) * 24)) < 12)) {
  return bitcast<f32>(1065353216u);
  } else {
  return bitcast<f32>(1045220556u);
  }
  } else {
  if ((m == 2)) {
  let cx = ((lx - ((lx / 32) * 32)) - 16);
  let cy = ((ly - ((ly / 32) * 32)) - 16);
  if ((((cx * cx) + (cy * cy)) < 90)) {
  return bitcast<f32>(1065353216u);
  } else {
  return bitcast<f32>(1043878379u);
  }
  } else {
  if ((m == 3)) {
  let cx = (lx - 170);
  let cy = (ly - 120);
  let d = sqrt(f32(f32(((cx * cx) + (cy * cy)))));
  if ((sin((d * bitcast<f32>(1043878379u))) > bitcast<f32>(0u))) {
  return bitcast<f32>(1064514355u);
  } else {
  return bitcast<f32>(1045220556u);
  }
  } else {
  if ((m == 4)) {
  if (((lx - ((lx / 22) * 22)) < 11)) {
  if (((ly - ((ly / 22) * 22)) < 11)) {
  return bitcast<f32>(1063675494u);
  } else {
  return bitcast<f32>(1050253721u);
  }
  } else {
  if (((ly - ((ly / 22) * 22)) < 11)) {
  return bitcast<f32>(1050253721u);
  } else {
  return bitcast<f32>(1063675494u);
  }
  }
  } else {
  return ta_clamp01((f32(f32((lx + ly))) / bitcast<f32>(1139146752u)));
  }
  }
  }
  }
  }
}
@group(0) @binding(0) var<storage, read_write> texarray_step_outb_buf : array<i32>;
struct U_texarray_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_texarray_step : U_texarray_step;
@compute @workgroup_size(64)
fn texarray_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_texarray_step.frame;
  let px = (gid - ((gid / ta_width) * ta_width));
  let py = (gid / ta_width);
  let col = (px / 342);
  let row = (py / 384);
  let panel = ((row * 3) + col);
  let lx = (px - (col * 342));
  let ly = (py - (row * 384));
  let border = select(select(select(select(0, 1, (ly > 380)), 1, (ly < 3)), 1, (lx > 338)), 1, (lx < 3));
  let l = (panel + (frame / 30));
  let v = ta_layer(l, lx, ly);
  let m = (l - ((l / 6) * 6));
  let tr = select(select(select(select(select(bitcast<f32>(1058642329u), bitcast<f32>(1062836633u), (m == 4)), bitcast<f32>(1056964608u), (m == 3)), bitcast<f32>(1064514355u), (m == 2)), bitcast<f32>(1053609164u), (m == 1)), bitcast<f32>(1063675494u), (m == 0));
  let tg = select(select(select(select(select(bitcast<f32>(1063675494u), bitcast<f32>(1056964608u), (m == 4)), bitcast<f32>(1060320051u), (m == 3)), bitcast<f32>(1053609164u), (m == 2)), bitcast<f32>(1062836633u), (m == 1)), bitcast<f32>(1056964608u), (m == 0));
  let tb = select(select(select(select(select(bitcast<f32>(1053609164u), bitcast<f32>(1063675494u), (m == 4)), bitcast<f32>(1064514355u), (m == 3)), bitcast<f32>(1056964608u), (m == 2)), bitcast<f32>(1056964608u), (m == 1)), bitcast<f32>(1050253721u), (m == 0));
  texarray_step_outb_buf[gid] = select(ta_pack((v * tr), (v * tg), (v * tb)), (((20 * 65536) + (24 * 256)) + 34), (border == 1));
}