// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const tm_width : i32 = 1024;
const tm_half_w : i32 = 512;
const tm_horizon : i32 = 300;
const tm_focal : i32 = 420;
const tm_scale : i32 = 52000;
fn tm_checker(u : i32, v : i32, cell : i32) -> f32 {
  let s = ((u / cell) + (v / cell));
  if (((s - ((s / 2) * 2)) == 0)) {
  return bitcast<f32>(1060655595u);
  } else {
  return bitcast<f32>(1051595898u);
  }
}
fn tm_clamp01(x : f32) -> f32 {
  return max(bitcast<f32>(0u), min(bitcast<f32>(1065353216u), x));
}
fn tm_pack(r : f32, g : f32, b : f32) -> i32 {
  return (((i32((tm_clamp01(r) * bitcast<f32>(1132396544u))) * 65536) + (i32((tm_clamp01(g) * bitcast<f32>(1132396544u))) * 256)) + i32((tm_clamp01(b) * bitcast<f32>(1132396544u))));
}
@group(0) @binding(0) var<storage, read_write> texmipmap_step_outb_buf : array<i32>;
struct U_texmipmap_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_texmipmap_step : U_texmipmap_step;
@compute @workgroup_size(64)
fn texmipmap_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_texmipmap_step.frame;
  let px = (gid - ((gid / tm_width) * tm_width));
  let py = (gid / tm_width);
  let sy = (py - tm_horizon);
  if ((sy <= 0)) {
  texmipmap_step_outb_buf[gid] = (((18 * 65536) + (26 * 256)) + 48);
  } else {
  let d = (tm_scale / sy);
  let wx = ((((px - tm_half_w) * d) / tm_focal) + (frame * 2));
  let wz = d;
  let u = (wx - ((wx / 4096) * 4096));
  let uu = select(u, (u + 4096), (u < 0));
  let vv = (wz - ((wz / 4096) * 4096));
  let lod = select(select(select(select(4, 3, (sy > 30)), 2, (sy > 60)), 1, (sy > 120)), 0, (sy > 220));
  let cell = (32 * (lod + 1));
  let base = tm_checker(uu, vv, cell);
  let fade = select((base + (f32(f32(lod)) * bitcast<f32>(1017370378u))), base, (base > bitcast<f32>(1056964608u)));
  let tintr = (bitcast<f32>(1065353216u) + (f32(f32(lod)) * bitcast<f32>(0u)));
  let tintg = (bitcast<f32>(1065353216u) - (f32(f32(lod)) * bitcast<f32>(1031127695u)));
  let tintb = (bitcast<f32>(1065353216u) - (f32(f32(lod)) * bitcast<f32>(1038174126u)));
  texmipmap_step_outb_buf[gid] = tm_pack((fade * tintr), (fade * tintg), (fade * tintb));
  }
}