// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const tx_width : i32 = 1024;
const tx_cellw : i32 = 104;
const tx_rowh : i32 = 22;
const tx_nchar : i32 = 9;
fn tx_row(ch : i32, row : i32) -> i32 {
  if ((ch == 0)) {
  if ((row == 0)) {
  return 14;
  } else {
  if ((row == 1)) {
  return 17;
  } else {
  if ((row == 5)) {
  return 17;
  } else {
  if ((row == 6)) {
  return 14;
  } else {
  return 16;
  }
  }
  }
  }
  } else {
  if ((ch == 1)) {
  if ((row == 0)) {
  return 14;
  } else {
  if ((row == 6)) {
  return 14;
  } else {
  return 17;
  }
  }
  } else {
  if ((ch == 2)) {
  if ((row == 0)) {
  return 30;
  } else {
  if ((row == 6)) {
  return 30;
  } else {
  return 17;
  }
  }
  } else {
  if ((ch == 3)) {
  if ((row == 0)) {
  return 31;
  } else {
  if ((row == 3)) {
  return 30;
  } else {
  if ((row == 6)) {
  return 31;
  } else {
  return 16;
  }
  }
  }
  } else {
  if ((ch == 4)) {
  if ((row == 2)) {
  return 10;
  } else {
  if ((row == 3)) {
  return 4;
  } else {
  if ((row == 4)) {
  return 10;
  } else {
  return 17;
  }
  }
  }
  } else {
  if ((ch == 6)) {
  if ((row == 0)) {
  return 14;
  } else {
  if ((row == 1)) {
  return 17;
  } else {
  if ((row == 2)) {
  return 16;
  } else {
  if ((row == 3)) {
  return 23;
  } else {
  if ((row == 6)) {
  return 15;
  } else {
  return 17;
  }
  }
  }
  }
  }
  } else {
  if ((ch == 7)) {
  if ((row == 0)) {
  return 30;
  } else {
  if ((row == 1)) {
  return 17;
  } else {
  if ((row == 2)) {
  return 17;
  } else {
  if ((row == 3)) {
  return 30;
  } else {
  return 16;
  }
  }
  }
  }
  } else {
  if ((ch == 8)) {
  if ((row == 6)) {
  return 14;
  } else {
  return 17;
  }
  } else {
  return 0;
  }
  }
  }
  }
  }
  }
  }
  }
}
fn tx_pow2(n : i32) -> i32 {
  if ((n <= 0)) {
  return 1;
  } else {
  if ((n == 1)) {
  return 2;
  } else {
  if ((n == 2)) {
  return 4;
  } else {
  if ((n == 3)) {
  return 8;
  } else {
  if ((n == 4)) {
  return 16;
  } else {
  return 32;
  }
  }
  }
  }
  }
}
fn tx_char(i : i32) -> i32 {
  let m = (i - ((i / tx_nchar) * tx_nchar));
  if ((m == 0)) {
  return 0;
  } else {
  if ((m == 1)) {
  return 1;
  } else {
  if ((m == 2)) {
  return 2;
  } else {
  if ((m == 3)) {
  return 3;
  } else {
  if ((m == 4)) {
  return 4;
  } else {
  if ((m == 5)) {
  return 5;
  } else {
  if ((m == 6)) {
  return 6;
  } else {
  if ((m == 7)) {
  return 7;
  } else {
  return 8;
  }
  }
  }
  }
  }
  }
  }
  }
}
fn tx_bit(ch : i32, col : i32, row : i32) -> i32 {
  if ((col < 0)) {
  return 0;
  } else {
  if ((col > 4)) {
  return 0;
  } else {
  if ((row < 0)) {
  return 0;
  } else {
  if ((row > 6)) {
  return 0;
  } else {
  let rv = tx_row(ch, row);
  return ((rv / tx_pow2((4 - col))) - ((rv / tx_pow2((5 - col))) * 2));
  }
  }
  }
  }
}
fn tx_ison(px : i32, py : i32, frame : i32) -> i32 {
  let sx = (px + (frame * 2));
  let ci = (sx / tx_cellw);
  let cx = (sx - (ci * tx_cellw));
  let col = ((cx - 12) / 16);
  let ry = (py - 250);
  let row = (ry / tx_rowh);
  if ((cx < 12)) {
  return 0;
  } else {
  if ((cx > 92)) {
  return 0;
  } else {
  if ((ry < 0)) {
  return 0;
  } else {
  if ((row > 6)) {
  return 0;
  } else {
  return tx_bit(tx_char(ci), col, row);
  }
  }
  }
  }
}
@group(0) @binding(0) var<storage, read_write> text_step_outb_buf : array<i32>;
struct U_text_step {
  frame : i32,
}
@group(0) @binding(1) var<uniform> u_text_step : U_text_step;
@compute @workgroup_size(64)
fn text_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_text_step.frame;
  let px = (gid - ((gid / tx_width) * tx_width));
  let py = (gid / tx_width);
  let on = tx_ison(px, py, frame);
  let shadow = tx_ison((px - 4), (py - 4), frame);
  let bgb = (30 + (py / 12));
  text_step_outb_buf[gid] = select(select((((22 * 65536) + (26 * 256)) + bgb), (((8 * 65536) + (10 * 256)) + 16), (shadow == 1)), (((255 * 65536) + (245 * 256)) + 200), (on == 1));
}