// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const tx_width : i32 = 1024;
const tx_half_w : i32 = 512;
const tx_horizon : i32 = 300;
const tx_focal : i32 = 420;
const tx_scale : i32 = 52000;
fn tx_tile(w : i32) -> i32 {
  let m = (w - ((w / 256) * 256));
  if ((m < 0)) {
  return (m + 256);
  } else {
  return m;
  }
}
fn tx_sky(py : i32) -> i32 {
  let h = ((py * 255) / tx_horizon);
  let r = (20 + ((h * 20) / 255));
  let g = (30 + ((h * 40) / 255));
  let b = (60 + ((h * 120) / 255));
  return (((r * 65536) + (g * 256)) + b);
}
fn tx_shade(texel : i32, fog : i32) -> i32 {
  let r = (texel / 65536);
  let g = ((texel / 256) - ((texel / 65536) * 256));
  let b = (texel - ((texel / 256) * 256));
  let hr = 60;
  let hg = 70;
  let hb = 95;
  let sr = (((r * fog) + (hr * (256 - fog))) / 256);
  let sg = (((g * fog) + (hg * (256 - fog))) / 256);
  let sb = (((b * fog) + (hb * (256 - fog))) / 256);
  return (((sr * 65536) + (sg * 256)) + sb);
}
@group(0) @binding(0) var<storage, read_write> texture_step_texbuf_buf : array<i32>;
@group(0) @binding(1) var<storage, read_write> texture_step_outb_buf : array<i32>;
struct U_texture_step {
  frame : i32,
}
@group(0) @binding(2) var<uniform> u_texture_step : U_texture_step;
@compute @workgroup_size(64)
fn texture_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_texture_step.frame;
  let px = (gid - ((gid / tx_width) * tx_width));
  let py = (gid / tx_width);
  let sy = (py - tx_horizon);
  let sky = (sy <= 0);
  let d = select((tx_scale / sy), 1, sky);
  let wx = (((px - tx_half_w) * d) / tx_focal);
  let wz = (d + (frame * 3));
  let u = tx_tile(wx);
  let v = tx_tile(wz);
  let idx = select(((v * 256) + u), 0, sky);
  let fog = select(sy, 256, (sy > 256));
  let texel = texture_step_texbuf_buf[idx];
  let out = select(tx_shade(texel, fog), tx_sky(py), sky);
  texture_step_outb_buf[gid] = out;
}