// How each game is played, lifted from the hand-written rules panels in
// apps/games/classic/web/*.html rather than restated, so the arcade and the
// original shells cannot drift into describing the same game differently.
// Backgammon and Sudoku had no panel there and are written here.
//
// A leading **bolded phrase** opens most entries; the page renders that.
export const RULES = {
  backgammon: [
    '**Goal:** Bring all fifteen of your checkers around to your home board, then bear them off. First side to bear all fifteen off wins.',
    '**The opening:** two checkers on your 24-point, five on your 13, three on your 8 and five on your 6 -- 167 pips of travel each, the standard position.',
    '**Moving:** Throw two dice and move a checker that many points for each, or four moves when the two match. The dice show on the throwing side, White on the left and Black on the right, and go flat as they are spent. The two sides run in opposite directions.',
    '**The doubling cube:** shown on the bar for completeness and inert. This engine implements no doubling, so nothing here offers or takes one.',
    '**Blots and the bar:** A point held by a single checker is a blot. Land on it and that checker goes to the bar, and must re-enter before its owner may move anything else.',
    '**Blocked points:** You may not land on a point held by two or more enemy checkers.',
    '**Playing:** press Roll, then click a point to pick a checker up and a point to put it down; legal points are ringed. The bar and the bear-off tray are clickable in their own right. A die with no legal move anywhere is forfeit, and the pass button appears when that happens.',
  ],
  battleship: [
    '**Goal:** Sink all of your opponent\'s ships before they sink yours.',
    '**Setup:** Each fleet hides 5 ships on a 10x10 grid: Carrier (5), Battleship (4), Cruiser (3), Submarine (3), Destroyer (2) -- 17 cells in all.',
    '**Playing:** Click a square on YOUR grid to fire at it. A dot is a miss, a filled circle a hit. They fire back in the same turn, so both grids move at once.',
    '**Hunting:** A hit tells you a hull runs through that square, but not which way. The squares beside it are where the rest of it is.',
    '**Victory:** First fleet to land 17 hits has sunk everything.',
  ],
  blackjack: [
    '**Goal:** Get a hand value closer to 21 than the dealer without going over (busting).',
    '**Card values:** Number cards = face value. Face cards (J/Q/K) = 10. Ace = 11 or 1.',
    '**Deal:** Player and dealer each get 2 cards. Dealer\'s second card is face-down (the "hole card").',
    '**Player turn:** Hit (take a card) or Stand. Bust if over 21.',
    '**Dealer turn:** Hole card revealed. Dealer must hit until reaching 17+.',
    '**Result:** Closest to 21 wins. Bust = automatic loss. Tie = push (no winner).',
  ],
  bridge: [
    '**Goal:** Take the tricks your side committed to in the bidding.',
    '**Teams:** North/South vs East/West. You are South and North is your partner.',
    '**Playing:** Click a card in your hand. Follow the suit that was led if you hold it, and the board rings the cards the rules allow rather than letting you revoke. The opening lead belongs to the declarer\'s left, so when your side bought the contract the first cards are on the table before your turn.',
    '**No dummy:** Real bridge lays the declarer\'s partner face up and the declarer plays both hands. This does not model a dummy: North is played for you, and that is the one rule a bridge player will miss here.',
    '**Bidding:** Teams bid to set a contract -- the number of tricks (above 6) they commit to win, and the trump suit.',
    '**Trump suits:** ♠ Spades, ♥ Hearts, ♦ Diamonds, ♣ Clubs.',
    '**Tricks:** 13 tricks per hand. Highest card of led suit wins unless trumped.',
    '**Scoring:** Make your contract = score points. Fall short = opponents score penalties.',
  ],
  checkers: [
    '**Goal:** Capture all of your opponent\'s pieces or block them so they can\'t move.',
    '**Movement:** Pieces move diagonally forward one square. Kings can move diagonally in any direction.',
    '**Captures:** Jump over an adjacent opponent piece to an empty square beyond it. Multiple jumps are allowed in one turn.',
    '**Kings:** When a piece reaches the opposite end of the board, it becomes a king (shown with a crown).',
    '**This simulation:** AI plays both sides using minimax with depth-3 search.',
  ],
  connect4: [
    '**Goal:** Be the first to connect four of your discs in a row -- horizontally, vertically, or diagonally.',
    '**Play:** Players take turns dropping one disc into any column. The disc falls to the lowest available row.',
    '**Strategy:** Block your opponent while building your own connections. Control the center column for maximum options.',
    '**This simulation:** AI plays both sides, taking a win where there is one, blocking one where there is not, and otherwise favouring the centre columns.',
  ],
  crazyeights: [
    '**Goal:** Be the first to empty your hand. Three players.',
    '**Playing:** Click a card in your hand that matches the top card\'s suit or rank. Playable cards are ringed, so the board will not let you make an illegal play.',
    '**Eights are wild:** An 8 goes on anything, and the player who lays it NAMES the suit -- click the 8, then click the suit. That is the whole reason to keep one back.',
    '**Twos bite:** A 2 leaves the next player two cards to draw. While a penalty stands the only legal turn is to take it.',
    '**Stuck:** If nothing in your hand will go, draw one and the turn passes. The button is only offered when you genuinely cannot play.',
    '**Hands:** You see your own cards. The others show a count, because that is all you would know.',
  ],
  dotsandboxes: [
    '**Goal:** Complete more boxes than your opponent on a 4x4 dot grid.',
    '**Play:** Take turns drawing one line between adjacent dots. When you complete the 4th side of a box, you score it and go again.',
    '**Strategy:** Avoid giving your opponent chains of boxes. Force them to open chains for you to claim.',
    '**End:** Game ends when all 24 lines are drawn (9 boxes total). Most boxes wins.',
  ],
  game2048: [
    '**Goal:** Slide and merge tiles to create a 2048 tile (or higher).',
    '**Play:** Each turn, all tiles slide in one direction. When two tiles of the same value collide, they merge into one tile with double the value.',
    '**Spawning:** After each move, a new tile (2 or 4) appears in a random empty cell.',
    '**End:** The game ends when no more moves are possible (board full, no adjacent matches).',
    '**This simulation:** AI picks the best direction each move using a heuristic strategy.',
  ],
  go: [
    '**Goal:** Control more territory than your opponent on a 9x9 board.',
    '**Play:** Players alternate placing stones. Black goes first. Stones are placed on intersections, not squares.',
    '**Capture:** Surround an opponent\'s group (remove all its liberties) to capture it. Captured stones are removed from the board.',
    '**Ko rule:** You cannot immediately recapture a stone that just captured yours (prevents infinite loops).',
    '**Passing:** A player may pass instead of placing a stone. Two consecutive passes end the game.',
    '**Scoring:** Count surrounded empty points (territory) + captured stones. Highest total wins.',
    '**Note:** This AI sometimes passes early, resulting in short games.',
  ],
  hexgame: [
    '**Goal:** Connect your two opposite edges of the board with an unbroken chain of your stones.',
    '**Board:** 11x11 rhombus of hexagonal cells.',
    '**Turns:** Players alternate placing one stone on any empty hex. Black goes first.',
    '**Black** wins by connecting the top edge to the bottom edge.',
    '**White** wins by connecting the left edge to the right edge.',
    '**No draws:** The board must always produce a winner -- it is mathematically impossible to fill the board without one player completing a connection.',
  ],
  hexwar: [
    '**Scenario:** Stalingrad. A hex-based wargame where two sides fight for control of the city.',
    '**Flow:** Each turn, units move across the hex grid, attack enemy positions, and try to capture key objectives.',
    '**Combat:** Units have attack and defense values. Terrain modifies combat outcomes. Supply lines matter.',
    '**Victory:** The game runs for a set number of turns. Victory is determined by objectives held at the end.',
    '**This simulation:** AI plays both sides. The progress bar shows how far into the battle we are.',
  ],
  liarsdice: [
    '**Playing:** Pick a face, then say a number: that is your bid, and the number click commits it. Only quantities that would be a legal raise are offered. Or call the last bid a lie.',
    '**A raise:** more dice than the standing bid, or the same number of a higher face. You are bidding on ALL the dice on the table, not just your own.',
    '**Calling:** If the dice really are there, you lose one for doubting. If they are not, the bidder loses one. Either way everything is rerolled and the bidding starts again.',
    '**You see your own five and nobody else\'s**, which is the whole game: everyone is bidding on a count no one can verify.',
    '**Goal:** Be the last player with dice remaining.',
    '**Each round:** All players secretly roll their dice. Players take turns bidding on the total number of a specific face value among ALL dice on the table.',
    '**Bidding:** Each bid must raise the quantity or the face value. A player may challenge the previous bid by calling "Liar!"',
    '**Challenge:** All dice are revealed. If the bid was too high, the bidder loses a die. If the bid was valid, the challenger loses a die.',
    '**End:** When a player loses all their dice, they\'re eliminated. Last player standing wins.',
  ],
  life: [
    'Conway\'s Game of Life. Each cell is alive or dead. A dead cell with exactly 3 alive neighbors becomes alive. An alive cell with 2 or 3 alive neighbors survives, otherwise it dies. 20x20 toroidal grid (edges wrap). The AI seeds an initial pattern and steps through generations.',
  ],
  mancala: [
    'Mancala (Kalah variant). Two players, 6 pits each plus a store. On your turn, pick up all stones from one of your pits and sow them counter-clockwise, one per pit. If your last stone lands in your store, go again. If it lands in an empty pit on your side, capture that stone plus the opposite pit\'s stones. Game ends when one side is empty; remaining stones go to the other player\'s store. Most stones wins.',
  ],
  war: [
    '**Goal:** Win all 52 cards.',
    '**Setup:** The deck is split evenly, 26 cards each, face down. Nobody can see any of it.',
    '**Each round:** Both sides turn their top card. The higher takes both. Equal cards mean war: more cards are wagered and the next turn decides it.',
    '**Card ranks:** 2 low through Ace high. Suits do not matter.',
    '**Playing:** Click your deck to turn the next card. There is nothing else to decide -- War has no choices in it at all, which is exactly why it is worth having: the deal and the bookkeeping are the only things that can be wrong.',
    '**End:** One side runs out of cards. It can take several hundred rounds.',
  ],
  mastermind: [
    '**Goal:** Guess the secret 4-color code in 10 guesses or fewer.',
    '**Colors:** Red, Blue, Green, Yellow, Purple, Orange (6 colors, 4 positions).',
    '**Feedback:** After each guess, you receive feedback pegs:',
    '● **Black peg** = right colour in the right position.',
    '○ **White peg** = right colour in the wrong position.',
    '**Playing:** Click a colour to set the peg you are on; the cursor walks to the next, so four colour clicks make a whole guess. Click a peg to go back to it. Then press Guess.',
    '**The hard part:** the pegs are counted, not placed. Two black and one white tells you nothing about WHICH two are right, and every past guess on the board is evidence for the next one.',
    '**Strategy:** The AI keeps only codes consistent with every score so far, and your guesses narrow that pool too, so handing the game back to it mid-way is fair.',
    '**This simulation:** AI codebreaker tries to crack the secret in 10 guesses using elimination strategy.',
  ],
  minesweeper: [
    'Minesweeper. 9x9 grid with 10 hidden mines. Reveal cells to find safe ground. Numbers show how many adjacent cells contain mines. The AI picks safe cells using zero-risk deduction. Hit a mine = game over. Clear all 71 safe cells to win.',
  ],
  monopoly: [
    '**Goal:** Be the last player with cash. All other players go bankrupt.',
    '**Flow:** Roll dice, move around the 40-space board. Land on unowned property to buy it. Land on owned property to pay rent. Pass Go to collect $200.',
    '**Special spaces:** Go (collect $200), Jail (just visiting or sent), Free Parking, Go To Jail (sent directly to Jail).',
    '**Elimination:** If you cannot pay rent or taxes, you are bankrupt and eliminated.',
    '**Playing:** You are player one. Roll, and when you land on a property nobody owns that you can afford, buy it or leave it. That is the only decision in this game: everything else about a turn is forced, and there is no trading, so a colour group is only ever assembled by the luck of the dice.',
    '**Buying:** Click the ringed square or use the button. A whole colour group charges twenty-five times the base rent, which is where the real board\'s hotels sit and what makes the game finish at all.',
    '**Bankruptcy is rare here.** Passing Go pays from the bank while rent only moves money between players, so most sittings end on the turn cap with the richest player ahead rather than with anyone broke.',
  ],
  othello: [
    '**Board:** 8x8 grid. Each player has a disc color (black or white).',
    '**Moves:** Place a disc to outflank opponent discs -- trap them in a straight line (horizontal, vertical, or diagonal) between your new disc and an existing one of yours. Outflanked discs flip to your color.',
    '**Valid moves:** Every move must flip at least one opponent disc. If you cannot move, you pass.',
    '**End:** The game ends when neither player can move. The player with the most discs wins.',
  ],
  pinochle: [
    '**Goal:** Be the first team to reach a target score by winning tricks and forming melds.',
    '**The deck:** Pinochle uses a special 48-card deck with two copies of each card from 9 through Ace in all four suits (no 2-8 cards). Card ranking from high to low: A, 10, K, Q, J, 9.',
    '**Teams:** Four players in two partnerships of two. Partners sit across from each other.',
    '**Melds:** After the deal, players score points for specific card combinations (melds) in their hand. Common melds include: Pinochle (Jack of Diamonds + Queen of Spades), Marriage (King + Queen of same suit), and Runs (A-10-K-Q-J of trump).',
    '**Trick-taking:** After melding, players take turns playing cards. You must follow suit if possible; otherwise you must play trump if possible. The highest trump wins, or the highest card of the led suit if no trump is played.',
    '**Scoring:** Points come from melds and from capturing certain cards in tricks (Aces=11, Tens=10, Kings=4, Queens=3, Jacks=2). Last trick is worth an extra 10 points.',
    '**Playing:** You are seat 1 and you lead the first trick. Click a card in your hand; the ones the rules allow are ringed, so the board will not let you revoke. Follow the suit led if you hold it and head the trick if you can, and when you are void you must trump.',
    '**Your side:** Your partner sits opposite. You see your own cards, and everyone else shows a count, because that is all you would know at the table.',
  ],
  poker: [
    '**Goal:** Make the best five-card hand to beat your opponent.',
    '**Hand rankings (low to high):** High Card, Pair, Two Pair, Three of a Kind, Straight, Flush, Full House, Four of a Kind, Straight Flush.',
    '**Flow:** Five cards each, a round of betting, one draw, a second round of betting, then the showdown.',
    '**The stakes:** Two hundred chips each, an ante of five, and a bet of ten. A fixed limit rather than no limit, and a round is capped at four raises so it cannot go round for ever.',
    '**Betting:** Check or call costs you whatever is in front of you, which is nothing when the stakes are level. Raise puts in ten more. Fold gives up the pot, and it is the one way to lose without showing your hand -- or to win one.',
    '**The draw:** Click the cards you want rid of and then Draw. A click only ever marks a card; Start the marks again clears them. The new cards come off the undealt part of the deck, so nothing you are handed is already in play.',
    '**Their cards:** Face down until the hand is over. The module refuses to answer what they are holding rather than the page choosing not to look.',
  ],
  pokervariants: [
    '**Goal:** Make the best five-card poker hand to beat your opponent.',
    '**The deal:** Each player is dealt five cards face down from a standard 52-card deck.',
    '**The draw:** After looking at their hand, each player may discard up to three cards (or four if holding an Ace) and receive replacements from the deck. This is the chance to improve your hand.',
    '**The showdown:** After the draw, hands are revealed and compared. The player with the best poker hand wins.',
    '**Hand rankings (low to high):** High Card, Pair, Two Pair, Three of a Kind, Straight, Flush, Full House, Four of a Kind, Straight Flush.',
    '**Strategy:** Keep strong combinations (pairs, three of a kind) and discard weak cards hoping to draw better ones. Knowing when to hold and when to draw is the key skill.',
    '**This simulation:** AI plays 8 hands of Five Card Draw. Each step shows one completed hand with the result.',
  ],
  risk: [
    '**Goal:** Conquer all 12 territories. Last player standing wins.',
    '**Flow:** Each turn, the current player deploys reinforcement armies, then attacks neighboring territories. Combat is dice-based: attacker and defender each roll, highest die wins.',
    '**Elimination:** When a player loses all territories, they are eliminated. This is the one game here you can be knocked out of while it carries on, and when that happens your game is over even though theirs is not.',
    '**Your turn, part one:** You are player one. Click your own territories to put the reinforcement down, one army per click. How many you get is your territory count divided by three, never fewer than three, plus two for each continent you hold whole.',
    '**Your turn, part two:** Then up to three attacks. Click a territory of yours to attack FROM, then an adjacent enemy to attack. An army has to stay behind, so a territory holding one cannot attack out of. Stop attacking ends the turn early, which is often the right move.',
    '**Combat:** Attacker rolls up to three dice, defender up to two, sorted and compared. Ties go to the defender.',
  ],
  royalur: [
    '**Goal:** Be the first player to move all 7 pieces off the board.',
    '**Dice:** Roll 4 binary dice (each 0 or 1) for a total of 0-4 pips.',
    '**Movement:** Each piece travels along a fixed path. P1 (blue) enters from the top, P2 (red) from the bottom. Both share the middle row.',
    '**Rosettes (✦):** Landing on a rosette grants an extra turn. Pieces on rosettes are safe from capture.',
    '**Capture:** Landing on an opponent\'s piece in the shared row sends it back to the start.',
    '**Scoring:** A piece that moves past the last square is scored. First to score all 7 wins.',
  ],
  setgame: [
    '**A set:** three cards where each of the four attributes -- number, shape, shading, colour -- is either all the same or all different across the three. No two-and-one on any attribute.',
    '**Playing:** Click three cards. A wrong three keeps the last one you clicked and drops the other two, so a bad guess costs one click. Click a picked card again to take it back.',
    '**Stuck:** If no set is on the table, deal three more. The table grows to fifteen and stays there until a set is taken.',
    '**End:** No set on the table and nothing left to deal.',
  ],
  gofish: [
    '**Goal:** Make the most books. A book is all four of a rank.',
    '**Your turn:** Pick a rank you HOLD, then pick who to ask. You may only ask for a rank already in your hand -- that is a real rule, and the board only offers the ranks you have.',
    '**Hit:** They hand over every card of that rank. **Miss:** go fish, you draw from the pond.',
    '**This simulation:** The turn passes after every question, hit or miss. The other two players ask for the rank they hold most of.',
  ],
  mahjong: [
    '**Goal:** Clear all 144 tiles by taking matching pairs.',
    '**Free tiles:** A tile can only be taken when it is FREE -- nothing on top of it and one side clear. That is the whole difficulty: the match you want is usually buried under something.',
    '**Playing:** Click a free tile, then its match. Free tiles are marked, and once you pick one, everything it can pair with is marked too.',
    '**Stuck:** If no two free tiles match, the board is dead even with tiles left. Hint points at a pair when one exists.',
  ],
  sudoku: [
    '**Goal:** Fill every blank so each row, column and 3x3 box holds 1 to 9 once.',
    '**Playing:** Pick a digit from the row above the grid, then click a blank square. Squares where that digit can legally go are outlined, so the board answers "where does this go" before you commit.',
    '**Undo a square:** Click a digit you wrote to clear it. The given squares are bold and cannot be changed.',
    '**The puzzle:** The grid is solved first and then holes are punched in it, so every blank has a digit that belongs there.',
    '**This simulation:** Watch mode hands it to the backtracking solver, which fills the whole grid in one step.',
  ],
  yahtzee: [
    '**Goal:** Fill all thirteen boxes with the best scores you can. Every box is spent once and once only.',
    '**A turn:** Roll five dice. Click the dice you want to KEEP, then Roll again -- up to three rolls in all. Then click a box to score the dice into it.',
    '**Upper section:** 1s through 6s score the total of that face. Sixty-three or more across the six earns a bonus in the real game.',
    '**Lower section:** three and four of a kind score all five dice; full house 25; small run 30; large run 40; YAHTZEE (five alike) 50; chance the sum of everything.',
    '**The squeeze:** every box shows what it WOULD score with the dice on the table. A bad roll still has to go somewhere, and choosing where is the whole game.',
    '**This simulation:** Watch mode plays a whole turn at a time with the engine\'s own keep-and-choose strategy.',
  ],
  rps: [
    '**Goal:** Win more of twenty rounds than your opponent.',
    '**Rules:** Rock blunts scissors, scissors cut paper, paper wraps rock.',
    '**The opponent:** It is not random. It counts what you have thrown and leans toward the throw that beats your favourite, so a habit is punished. Its own history is on the board for you to read back.',
  ],
  klondike: [
    '**Goal:** Build all four foundations from Ace up to King, one suit each. Fifty-two cards up and the game is won.',
    '**Tableau:** Seven columns, one to seven cards, only the last of each face up. Build DOWN in alternating colour -- a red six goes on a black seven. A run built that way moves as a group.',
    '**Spaces:** An empty column takes a King and nothing else.',
    '**Stock:** Click the stock to turn a card (or three). When it runs out, gather the waste back up and go round again.',
    '**Face down:** Take the last face-up card off a column and the next one turns over. That is the whole game: everything else is in service of turning cards over.',
    '**Splitting:** Click a card rather than the column to move that card and everything on top of it, leaving the rest behind.',
    '**This simulation:** The opponent plays a priority order, not a search -- foundations first, then a move that turns a card over, then the waste. It wins about one game in seven at turn one.',
  ],
  spider: [
    '**Goal:** Clear all 8 suits by building complete King-to-Ace descending sequences of the same suit.',
    '**Tableau:** 10 columns of cards. Move cards between columns to build descending sequences. Only same-suit sequences can be moved as a group.',
    '**Stock:** When stuck, deal one card to each column from the stock pile.',
    '**Completion:** A complete K-A same-suit run is automatically removed. Clear all 8 to win.',
    '**This simulation:** AI plays automatically, making moves and dealing from stock.',
  ],
  tictactoe: [
    '**Board:** 3x3 grid. Players alternate placing X and O.',
    '**Goal:** Be the first to get 3 of your marks in a row -- horizontal, vertical, or diagonal.',
    '**Draw:** If all 9 cells are filled with no winner, it\'s a draw.',
    '**AI:** Uses perfect-play minimax -- it will never lose.',
  ],
};


