// How each game is played, lifted from the hand-written rules panels in
// apps/games/classic/web/*.html rather than restated, so the arcade and the
// original shells cannot drift into describing the same game differently.
// Backgammon and Sudoku had no panel there and are written here.
//
// A leading **bolded phrase** opens most entries; the page renders that.
export const RULES = {
  backgammon: [
    '**Goal:** Bring all fifteen of your checkers around to your home board, then bear them off. First side to bear all fifteen off wins.',
    '**The opening:** two checkers on your 24-point, five on your 13, three on your 8 and five on your 6 -- 167 pips of travel each, the standard position.',
    '**Moving:** Throw two dice and move a checker that many points for each, or four moves when the two match. The dice show on the throwing side, White on the left and Black on the right, and go flat as they are spent. The two sides run in opposite directions.',
    '**The doubling cube:** the game starts worth 1, with the cube in the middle showing 64. At the start of your turn, before you roll, you may offer to double if the cube is in the middle or yours. The other side takes, and play goes on at twice the value with the cube now theirs, or drops and loses at the value before the offer. The opponent doubles and answers doubles too; when it offers, Take and Drop appear.',
    '**Scoring:** a win is worth the cube\'s value; a gammon, where the loser has borne off no checker, twice that; a backgammon, where the loser has borne off none and still has a checker on the bar or in the winner\'s home board, three times.',
    '**Using the dice:** You must play both dice when you can. When only one can be played you play it, and when either could be played but not both, you must play the larger. With a double, play as many of the four as you can. A die that cannot be played is lost.',
    '**Blots and the bar:** A point held by a single checker is a blot. Land on it and that checker goes to the bar. A checker on the bar enters on the point in the opponent\'s home board that a die names, and its owner moves nothing else until every checker on the bar has entered.',
    '**Blocked points:** You may not land on a point held by two or more enemy checkers.',
    '**Bearing off:** Once all fifteen are in your home board, a die bears off a checker from the point it names. A die higher than your highest occupied point bears off from that highest point; a die naming an empty point with checkers above it must be played by moving one of those. You never have to bear off while another legal move exists.',
    '**Playing:** press Roll, then click a checker to pick it up and a point to put it down; only moves the rules allow are ringed. To enter from the bar, click the bar and then the entry point, so you choose the die. When two dice could bear the same checker off, click the die you mean to spend. When no die can be played, the pass button appears.',
  ],
  battleship: [
    '**Goal:** Sink all of your opponent\'s ships before they sink yours.',
    '**Setup:** Each fleet hides 5 ships on a 10x10 grid: Carrier (5), Battleship (4), Cruiser (3), Submarine (3), Destroyer (2) -- 17 cells in all.',
    '**Playing:** Click a square on YOUR grid to fire at it. A dot is a miss, a filled circle a hit. They fire back in the same turn, so both grids move at once.',
    '**Hunting:** A hit tells you a hull runs through that square, but not which way. The squares beside it are where the rest of it is.',
    '**Victory:** First fleet to land 17 hits has sunk everything.',
  ],
  blackjack: [
    '**Goal:** Get a hand value closer to 21 than the dealer without going over (busting).',
    '**Card values:** Number cards = face value. Face cards (J/Q/K) = 10. Ace = 11 or 1.',
    '**Deal:** Player and dealer each get 2 cards. Dealer\'s second card is face-down (the "hole card").',
    '**Naturals:** An ace and a ten-valued card as your first two cards is a natural (blackjack). It beats every other hand and pays 3:2; against a dealer natural it pushes.',
    '**Insurance:** When the dealer shows an ace you may insure for half your bet, paid 2:1 if the dealer has a natural. The dealer then checks the hole card, and a dealer natural ends the round.',
    '**Your turn:** Hit (take a card) or Stand. A hand that reaches 21 stands by itself; over 21 busts.',
    '**Double down:** On your first two cards totalling 9, 10 or 11, double your bet and take exactly one more card.',
    '**Split:** Two cards of the same rank split into two hands with a bet each, up to four hands. Split aces take one card each, and a 21 after a split is an ordinary 21. No surrender.',
    '**Dealer turn:** The hole card is revealed and the dealer draws to 17, hitting a soft 17. If every hand busted, the dealer does not draw.',
    '**Result:** A hand closer to 21 than the dealer, or against a dealer bust, wins its bet; a lower total or a bust loses it; equal totals push.',
  ],
  bridge: [
    '**Goal:** Take the tricks your side committed to in the bidding.',
    '**Teams:** North/South vs East/West. You are South and North is your partner.',
    '**The board:** One duplicate board. Its number sets the dealer and who is vulnerable.',
    '**Bidding:** The dealer calls first and the call goes clockwise. A bid names a number of tricks over six and a denomination (clubs lowest, then diamonds, hearts, spades, no trumps) and must beat the last bid. You may double the opponents\' last bid, and redouble your side\'s bid if they doubled it. Three passes after a bid end the auction; four passes at the start pass the board out.',
    '**Declarer and dummy:** The declarer is the first of the winning side to have named the denomination. The declarer\'s left leads, then the declarer\'s partner lays the hand face up as dummy and the declarer plays it. When you declare you play North\'s cards too.',
    '**Playing:** Click a card to play it. Follow the suit that was led if you hold it; the board rings the cards the rules allow. Highest card of the suit led wins unless trumped.',
    '**Scoring:** Duplicate scoring: 20 a trick in the minors, 30 in the majors, 40 then 30 in no trumps; a game bonus of 300 or 500 (vulnerable) at 100 contract points, 50 for a part score, slam bonuses, and penalties for each trick short.',
  ],
  checkers: [
    '**Goal:** Capture all of your opponent\'s pieces or block them so they can\'t move.',
    '**Movement:** You are South, the red pieces, and move first. A man moves one square diagonally forward; a king one square diagonally in any direction.',
    '**Captures:** Jump over an adjacent opponent piece to the empty square beyond it; men capture forward only, kings either way. Capturing is compulsory: while any capture is available, nothing else may be played, but you choose which capture.',
    '**Chains:** A piece that can capture again from where it landed must go on capturing in the same turn, and only that piece may move until the chain ends.',
    '**Kings:** A man reaching the far row becomes a king (shown with a crown), and that ends the move even if the new king could capture again.',
    '**The end:** A side with no pieces, or no legal move, loses. Forty moves each with no capture and no crowning is a draw.',
    '**This simulation:** AI plays both sides using minimax with depth-3 search.',
  ],
  chess: [
    '**Goal:** Checkmate: attack the enemy king so that no legal move takes it out of attack. You are White and move first.',
    '**Playing:** Click one of your pieces to pick it up and the board rings every square it may legally go to; click one of those to move, or click the piece again to put it back. A move that would leave your own king in check is not offered, so a pinned piece shows no destinations at all.',
    '**Castling:** Click the king and then the square two files along. It is offered only with the right unspent, the rook still home, the squares between empty, and the king neither in check nor passing through nor landing on an attacked square.',
    '**En passant:** A pawn that has just gone two squares may be taken by an enemy pawn beside it as though it had gone one. The window is a single move and closes whether or not it is taken.',
    '**Promotion:** A pawn reaching the far rank must become a queen, rook, bishop or knight, your choice: move the pawn, then press the Promote button for the piece you want.',
    '**Draws:** Stalemate, where the side to move is not in check and has no legal move; fifty moves by each side with no pawn move and no capture; the same position a third time, with the same side to move, castling rights and en passant chance; and a dead position, where neither side has the material to mate (bare kings, a single minor piece, or bishops all on one colour). This page applies the fifty-move and repetition draws at once rather than waiting for a claim, and a mate delivered on the move that would draw still wins.',
    '**This opponent:** alpha-beta search over material in centipawns, two ply deep, preferring the sooner mate. It sees a hanging piece and a mate in one; it does not see a plan.',
  ],
  connect4: [
    '**Goal:** Be the first to connect four of your discs in a row -- horizontally, vertically, or diagonally.',
    '**Play:** Players take turns dropping one disc into any column. The disc falls to the lowest available row.',
    '**Strategy:** Block your opponent while building your own connections. Control the center column for maximum options.',
    '**This simulation:** AI plays both sides, taking a win where there is one, blocking one where there is not, and otherwise favouring the centre columns.',
  ],
  crazyeights: [
    '**Goal:** Be the first to empty your hand. Three players.',
    '**Playing:** Click a card in your hand that matches the top card\'s suit or rank. Playable cards are ringed, so the board will not let you make an illegal play.',
    '**Eights are wild:** An 8 goes on anything, and the player who lays it NAMES the suit -- click the 8, then click the suit. That is the whole reason to keep one back.',
    '**Deal:** Five cards each (seven each with two players); the next card starts the pile, and a starting eight calls its own suit.',
    '**After an eight:** Only another eight or the named suit goes.',
    '**Drawing:** A turn is one card played OR one card drawn, and you may draw even with a card to play. An empty stock is remade from the pile under the top card.',
    '**Scoring:** The first out wins; the others count penalty points, 50 for an eight, 10 for a picture, the rest at face value (ace 1). If nobody can play or draw, the fewest points wins.',
    '**Hands:** You see your own cards. The others show a count, because that is all you would know.',
  ],
  dotsandboxes: [
    '**Goal:** Complete more boxes than your opponent on a 4x4 dot grid.',
    '**Play:** Take turns drawing one line between adjacent dots. When you complete the 4th side of a box, you score it and go again.',
    '**Strategy:** Avoid giving your opponent chains of boxes. Force them to open chains for you to claim.',
    '**End:** Game ends when all 24 lines are drawn (9 boxes total). Most boxes wins.',
  ],
  game2048: [
    '**Goal:** Slide and merge tiles to create a 2048 tile (or higher).',
    '**Play:** Each turn, all tiles slide in one direction. When two tiles of the same value collide, they merge into one tile with double the value.',
    '**Merging:** A tile merges at most once per move, and the pair nearest the side you slide toward merges first: four 2s slid left make two 4s, not one 8.',
    '**Scoring:** Your score rises by the value of every tile a merge makes.',
    '**Spawning:** After each move that changes the board, a new tile (2 or 4) appears in a random empty cell; a move that changes nothing is not a move.',
    '**End:** The game ends when no more moves are possible (board full, no adjacent matches).',
    '**This simulation:** AI picks the best direction each move using a heuristic strategy.',
  ],
  go: [
    '**Goal:** Hold more of the 9x9 board than your opponent, by the Chinese rules with area scoring.',
    '**Play:** Black (you) goes first; players alternate placing a stone on an empty intersection, or passing.',
    '**Capture:** After a stone is placed, every opposing group with no liberty left is removed. Captures are resolved first, so a stone that fills its own last liberty is legal when it captures.',
    '**Suicide:** A stone whose own group has no liberty after the captures may not be played.',
    '**Ko (superko):** No move may recreate any earlier board position of the game. The basic ko, retaking a single stone at once, is the commonest case; after a move elsewhere the retake is legal again.',
    '**The end:** Two passes in a row end the game. Every stone still on the board counts as alive, so capture dead groups before you pass.',
    '**Scoring:** Your area is your stones plus every empty region that touches only your stones. White adds a komi of 7.5, so there are no ties.',
  ],
  hexgame: [
    '**Goal:** Connect your two opposite edges of the board with an unbroken chain of your stones.',
    '**Board:** 11x11 rhombus of hexagonal cells.',
    '**Turns:** Players alternate placing one stone on any empty hex. Black goes first.',
    '**Black** wins by connecting the top edge to the bottom edge.',
    '**White** wins by connecting the left edge to the right edge.',
    '**No draws:** The board must always produce a winner -- it is mathematically impossible to fill the board without one player completing a connection.',
    '**The swap rule:** Once, instead of making the second move, White may take over Black\'s first stone: it becomes a White stone on the mirror-image cell (row and column exchanged), and Black moves again. It evens out the first move\'s advantage, so a very central opening is likely to be taken.',
  ],
  hexwar: [
    '**Scenario:** Stalingrad. A hex-based wargame where two sides fight for control of the city.',
    '**Flow:** Each turn, units move across the hex grid, attack enemy positions, and try to capture key objectives.',
    '**Combat:** Units have attack and defense values. Terrain modifies combat outcomes. Supply lines matter.',
    '**Victory:** The game runs for a set number of turns. Victory is determined by objectives held at the end.',
    '**This simulation:** AI plays both sides. The progress bar shows how far into the battle we are.',
  ],
  liarsdice: [
    '**Playing:** Pick a face, then say a number: that is your bid, and the number click commits it. Only quantities that would be a legal raise are offered. Or call the last bid a lie.',
    '**A raise:** more dice than the standing bid, or the same number of a higher face. You are bidding on ALL the dice on the table, not just your own.',
    '**Calling:** If the dice really are there, you lose one for doubting. If they are not, the bidder loses one. Either way everything is rerolled and the bidding starts again.',
    '**You see your own five and nobody else\'s**, which is the whole game: everyone is bidding on a count no one can verify.',
    '**Goal:** Be the last player with dice remaining.',
    '**Each round:** All players secretly roll their dice. Players take turns bidding on the total number of a specific face value among ALL dice on the table.',
    '**Bidding:** Each bid must raise the quantity or the face value. A player may challenge the previous bid by calling "Liar!"',
    '**Challenge:** All dice are revealed. If the bid was too high, the bidder loses a die. If the bid was valid, the challenger loses a die.',
    '**End:** When a player loses all their dice, they\'re eliminated. Last player standing wins.',
  ],
  life: [
    'Conway\'s Game of Life. Each cell is alive or dead. A dead cell with exactly 3 alive neighbors becomes alive. An alive cell with 2 or 3 alive neighbors survives, otherwise it dies. 20x20 toroidal grid (edges wrap). The AI seeds an initial pattern and steps through generations.',
  ],
  mancala: [
    'Mancala (Kalah variant). Two players, 6 pits each plus a store. On your turn, pick up all stones from one of your pits and sow them counter-clockwise, one per pit. If your last stone lands in your store, go again. If it lands in an empty pit on your side, capture that stone plus the opposite pit\'s stones. Game ends when one side is empty; remaining stones go to the other player\'s store. Most stones wins.',
  ],
  war: [
    '**Goal:** Win all 52 cards.',
    '**Setup:** The deck is split evenly, 26 cards each, face down. Nobody can see any of it.',
    '**Each round:** Both sides turn their top card. The higher takes both, to the bottom of the taker\'s deck.',
    '**War:** Equal cards stay on the table and each side plays one card face down and one face up; the higher face-up card takes everything on the table. Equal face-up cards mean another war, the same way.',
    '**Running short:** A side that cannot play both the face-down and the face-up card of a war loses at once. If both run short in the same war, each takes back its own cards.',
    '**Card ranks:** 2 low through Ace high. Suits do not matter.',
    '**Playing:** Click your deck to turn the next card. There is nothing else to decide -- War has no choices in it at all, which is exactly why it is worth having: the deal and the bookkeeping are the only things that can be wrong.',
    '**End:** One side runs out of cards. It can take several hundred rounds.',
  ],
  mastermind: [
    '**Goal:** Guess the secret 4-color code in 10 guesses or fewer.',
    '**Colors:** Red, Blue, Green, Yellow, Purple, Orange (6 colors, 4 positions).',
    '**Feedback:** After each guess, you receive feedback pegs:',
    '● **Black peg** = right colour in the right position.',
    '○ **White peg** = right colour in the wrong position.',
    '**Playing:** Click a colour to set the peg you are on; the cursor walks to the next, so four colour clicks make a whole guess. Click a peg to go back to it. Then press Guess.',
    '**The hard part:** the pegs are counted, not placed. Two black and one white tells you nothing about WHICH two are right, and every past guess on the board is evidence for the next one.',
    '**Strategy:** The AI keeps only codes consistent with every score so far, and your guesses narrow that pool too, so handing the game back to it mid-way is fair.',
    '**This simulation:** AI codebreaker tries to crack the secret in 10 guesses using elimination strategy.',
  ],
  minesweeper: [
    'Minesweeper. 9x9 grid with 10 hidden mines. Reveal cells to find safe ground. Numbers show how many adjacent cells contain mines. The AI picks safe cells using zero-risk deduction. Hit a mine = game over. Clear all 71 safe cells to win.',
    'Your first reveal is never a mine: a mine there is moved to the first free cell from the top left. Press Flag a mine and click a hidden cell to flag it (or click a flag to clear it); a flagged cell cannot be opened, by a click or by a flood, until you clear the flag.',
  ],
  monopoly: [
    '**Goal:** Be the last player not bankrupt. Everyone starts on GO with $1500.',
    '**A turn:** Throw two dice and move. Doubles throw again, and a third doubles in one turn goes straight to Jail. Passing GO pays $200.',
    '**Deeds:** Land on an unowned street, railroad or utility and you may buy it at its price. Leave it and the Bank auctions it at once to everyone, you included: bid more than the standing bid or drop out, and the last bidder left buys it.',
    '**Rent:** A street charges its deed rent, double when its owner holds the whole colour group, and more with houses or a hotel. Railroads charge 25, 50, 100 or 200 as their owner holds 1 to 4; utilities 4 times the dice, or 10 times when both are held. A mortgaged deed charges nothing.',
    '**Building:** With a whole colour group, none of it mortgaged, buy houses at the deed\'s house price, evenly across the group, up to four and then a hotel. The Bank has 32 houses and 12 hotels, and when they are gone there are none. Buildings sell back at half price.',
    '**Mortgages:** An unbuilt deed mortgages for half its price and is lifted for that plus 10%.',
    '**Squares:** Income Tax $200, Luxury Tax $100. Chance and Community Chest cards pay you, charge you, move you, send you to Jail or give you a Get Out of Jail Free card.',
    '**Jail:** Leave by throwing doubles on one of your next three turns, by using a card, or by paying $50 before throwing on either of the first two. After a third failed throw you pay $50 and move.',
    '**Debt:** Owe more than your cash and you must sell buildings and mortgage until you can pay. If even that is not enough you are bankrupt: to a player, they take everything you have; to the Bank, your deeds are auctioned.',
    '**Playing:** You are P1. Roll, buy or leave a deed, bid, and answer trade offers with the buttons; click the ringed square to buy. To build, sell a building, mortgage or lift a mortgage, press its button and click a ringed deed. The other seats trade for colour groups and may offer you a swap or a price.',
  ],
  othello: [
    '**Board:** 8x8 grid. Each player has a disc color (black or white).',
    '**Moves:** Place a disc to outflank opponent discs -- trap them in a straight line (horizontal, vertical, or diagonal) between your new disc and an existing one of yours. Outflanked discs flip to your color.',
    '**Valid moves:** Every move must flip at least one opponent disc. If you cannot move, you pass.',
    '**End:** The game ends when neither player can move. The player with the most discs wins.',
  ],
  pinochle: [
    '**Goal:** Be the first team to reach a target score by winning tricks and forming melds.',
    '**The deck:** Pinochle uses a special 48-card deck with two copies of each card from 9 through Ace in all four suits (no 2-8 cards). Card ranking from high to low: A, 10, K, Q, J, 9.',
    '**Teams:** Four players in two partnerships of two. Partners sit across from each other.',
    '**The auction:** Bidding opens at the dealer\'s left at 250 and rises by at least 10. A player who passes is out; three passes end it. If the three before the dealer all pass, the dealer takes it at 250. The winner is the declarer and names trump.',
    '**The pass:** The declarer\'s partner passes four cards across, and the declarer passes four back.',
    '**Melds:** Run of trump (A-10-K-Q-J) 150, with an extra king or queen 190, with an extra marriage 230, double run 1500; royal marriage 40, common marriage 20; the nine of trump 10; pinochle (Jack of Diamonds + Queen of Spades) 40, double 300; aces, kings, queens, jacks around 100, 80, 60, 40, and ten times that for both of each suit.',
    '**Trick-taking:** The declarer leads. You must follow suit if possible and head the trick if you can; otherwise you must trump, and overtrump a trumped trick if you can. Of two identical cards the first played wins.',
    '**Scoring:** Aces, tens and kings in tricks are worth 10 each, and the last trick 10. The declaring team scores its meld and counters if together they reach the bid, and otherwise goes set: it scores nothing and loses the bid. The other team\'s meld counts only if it takes a counter or the last trick. Game is 1500.',
    '**Playing:** You are seat 1 and open the first auction. Use the buttons to bid, pass and name trump; click four cards and pass them when it is your turn to pass; click a card to play it, and the ones the rules allow are ringed, so the board will not let you revoke.',
    '**Your side:** Your partner sits opposite. You see your own cards, and everyone else shows a count, because that is all you would know at the table.',
  ],
  poker: [
    '**Goal:** Make the best five-card hand to beat your opponent.',
    '**Hand rankings (low to high):** High Card, Pair, Two Pair, Three of a Kind, Straight, Flush, Full House, Four of a Kind, Straight Flush. Equal hands are compared card by card on all five, the pairs first; A-2-3-4-5 is the lowest straight; an exact tie splits the pot.',
    '**Flow:** Five cards each, a round of betting, one draw, a second round of betting, then the showdown.',
    '**The stakes:** Two hundred chips each, an ante of five, a bet of ten before the draw and twenty after it. A fixed limit: a round allows one bet and at most three raises.',
    '**Who speaks:** You (left of the dealer) begin the first round and draw first; the second round is begun by whoever made the first bet, or by you if nobody bet.',
    '**Betting:** Check or call costs you whatever is in front of you, which is nothing when the stakes are level. Raise puts in one more bet. Fold gives up the pot, and it is the one way to lose without showing your hand -- or to win one.',
    '**The draw:** Up to three cards. Click the cards you want rid of and then Draw. A click only ever marks a card; Start the marks again clears them. The new cards come off the undealt part of the deck, so nothing you are handed is already in play.',
    '**Their cards:** Face down until the hand is over. The module refuses to answer what they are holding rather than the page choosing not to look.',
  ],
  pokervariants: [
    '**Goal:** Make the best five-card poker hand to beat your opponent.',
    '**The deal:** Each player is dealt five cards face down from a standard 52-card deck.',
    '**The draw:** After looking at their hand, each player may discard up to three cards (or four if holding an Ace) and receive replacements from the deck. This is the chance to improve your hand.',
    '**The showdown:** After the draw, hands are revealed and compared. The player with the best poker hand wins.',
    '**Hand rankings (low to high):** High Card, Pair, Two Pair, Three of a Kind, Straight, Flush, Full House, Four of a Kind, Straight Flush.',
    '**Strategy:** Keep strong combinations (pairs, three of a kind) and discard weak cards hoping to draw better ones. Knowing when to hold and when to draw is the key skill.',
    '**This simulation:** AI plays 8 hands of Five Card Draw. Each step shows one completed hand with the result.',
  ],
  risk: [
    '**Goal:** Hold all 42 territories of the classic board. Last player standing wins.',
    '**Setting up:** The territories are dealt round the table with one army each; then everyone places the rest of their starting armies (40 for two players, 35 for three, 30 for four) one at a time, in turn. Click your own territories.',
    '**Reinforcing:** Each turn starts with armies: your territories divided by three, never fewer than three, plus a bonus for each continent you hold whole (North America 5, South America 2, Europe 5, Africa 3, Asia 7, Australia 2), plus any card set you trade. Click your own territories to place them one at a time.',
    '**Cards:** Conquer at least one territory in a turn and you draw a card. Three of a kind, one of each, or any two with a wild trade for 4, 6, 8, 10, 12, 15 armies, then 5 more each time, counted over every trade anyone makes; a traded card showing a territory of yours puts 2 armies on it. With five or more cards you must trade before placing.',
    '**Attacking:** Click a territory of yours, then an enemy beside it. You roll up to three dice (set with the Dice buttons, at most one fewer than your armies there) and the defender up to two; the highest dice are compared in pairs, and ties go to the defender. Attack as often as you like, then Stop attacking.',
    '**Conquering:** Take a territory and you must move in at least as many armies as dice you rolled, and may move in all but one. Knock a player out and you take their cards; holding six or more, you trade at once and place those armies before attacking on.',
    '**Fortifying:** End your turn with one move of armies from a territory of yours to another joined to it through your own territories, or End turn without it.',
    '**Elimination:** This is the one game here you can be knocked out of while it carries on, and when that happens your game is over even though theirs is not.',
  ],
  royalur: [
    '**Goal:** Be the first player to move all 7 pieces off the board.',
    '**Dice:** Roll 4 binary dice (each 0 or 1) for a total of 0-4 pips.',
    '**Movement:** Each piece travels along a fixed path. P1 (blue) enters from the top, P2 (red) from the bottom. Both share the middle row.',
    '**Rosettes (✦):** Landing on a rosette grants an extra turn. Pieces on rosettes are safe from capture.',
    '**Capture:** Landing on an opponent\'s piece in the shared row sends it back to the start.',
    '**Scoring:** A piece that moves past the last square is scored. First to score all 7 wins.',
  ],
  setgame: [
    '**A set:** three cards where each of the four attributes -- number, shape, shading, colour -- is either all the same or all different across the three. No two-and-one on any attribute.',
    '**Playing:** Click three cards. A wrong three keeps the last one you clicked and drops the other two, so a bad guess costs one click. Click a picked card again to take it back.',
    '**Stuck:** Only when no set is on the table, deal three more, and again while there is still none. A set taken while more than twelve cards are out is not replaced, so the table shrinks back to twelve.',
    '**End:** No set on the table and nothing left to deal.',
  ],
  gofish: [
    '**Goal:** Make the most books. A book is all four of a rank.',
    '**Your turn:** Pick a rank you HOLD, then pick who to ask. You may only ask for a rank already in your hand -- that is a real rule, and the board only offers the ranks you have.',
    '**Deal:** Five cards each (seven each with two players); the rest is the pond.',
    '**Hit:** They hand over every card of that rank, and you ask again.',
    '**Miss:** Go fish: draw from the pond. If you draw the rank you asked for, show it and ask again; otherwise the turn passes to the left.',
    '**Books:** Four of a rank are laid down at once.',
    '**End:** As soon as anyone has no cards, or the pond is empty. The most books wins; equal most is a tie. The other players ask for the rank they hold most of, of whoever holds the most cards.',

  ],
  mahjong: [
    '**Goal:** Clear all 144 tiles by taking matching pairs.',
    '**Free tiles:** A tile can only be taken when it is FREE -- nothing on top of it and one side clear. That is the whole difficulty: the match you want is usually buried under something.',
    '**Playing:** Click a free tile, then its match. Free tiles are marked, and once you pick one, everything it can pair with is marked too.',
    '**Stuck:** If no two free tiles match, the board is dead even with tiles left. Hint points at a pair when one exists.',
  ],
  sudoku: [
    '**Goal:** Fill every blank so each row, column and 3x3 box holds 1 to 9 once.',
    '**Playing:** Pick a digit from the row above the grid, then click a blank square. Squares where that digit can legally go are outlined, so the board answers "where does this go" before you commit.',
    '**Undo a square:** Click a digit you wrote to clear it. The given squares are bold and cannot be changed.',
    '**The puzzle:** The grid is solved first and then holes are punched in it, and a hole is kept only while the puzzle still has exactly one solution, as in every published sudoku.',
    '**Stuck:** Digits that break no rule can still lead nowhere. If a blank has no digit left that fits, clear one of yours.',
    '**This simulation:** Watch mode hands it to the backtracking solver, which fills the whole grid in one step, or stops if the digits you wrote leave no solution.',
  ],
  yahtzee: [
    '**Goal:** Fill all thirteen boxes with the best scores you can. Every box is spent once and once only.',
    '**A turn:** Roll five dice. Click the dice you want to KEEP, then Roll again -- up to three rolls in all. Then click a box to score the dice into it.',
    '**Upper section:** 1s through 6s score the total of that face. Sixty-three or more across the six earns a bonus in the real game.',
    '**Lower section:** three and four of a kind score all five dice; full house 25; small run 30; large run 40; YAHTZEE (five alike) 50; chance the sum of everything.',
    '**The squeeze:** every box shows what it WOULD score with the dice on the table. A bad roll still has to go somewhere, and choosing where is the whole game.',
    '**This simulation:** Watch mode plays a whole turn at a time with the engine\'s own keep-and-choose strategy.',
  ],
  rps: [
    '**Goal:** Win more of twenty rounds than your opponent.',
    '**Rules:** Rock blunts scissors, scissors cut paper, paper wraps rock.',
    '**The opponent:** It is not random. It counts what you have thrown and leans toward the throw that beats your favourite, so a habit is punished. Its own history is on the board for you to read back.',
  ],
  klondike: [
    '**Goal:** Build all four foundations from Ace up to King, one suit each. Fifty-two cards up and the game is won.',
    '**Tableau:** Seven columns, one to seven cards, only the last of each face up. Build DOWN in alternating colour -- a red six goes on a black seven. A run built that way moves as a group.',
    '**Spaces:** An empty column takes a King and nothing else.',
    '**Stock:** Click the stock to turn a card (or three). When it runs out, gather the waste back up and go round again, as often as you like.',
    '**Foundations:** Built up in suit from the Ace. A card on a foundation may come back down onto the tableau when it fits there.',
    '**Face down:** Take the last face-up card off a column and the next one turns over. That is the whole game: everything else is in service of turning cards over.',
    '**Splitting:** Click a card rather than the column to move that card and everything on top of it, leaving the rest behind.',
    '**This simulation:** The opponent plays a priority order, not a search -- foundations first, then a move that turns a card over, then the waste. It wins about one game in seven at turn one.',
  ],
  spider: [
    '**Goal:** Clear all 8 suits by building complete King-to-Ace descending sequences of the same suit.',
    '**Tableau:** 10 columns, all face down but the last card of each. Any card goes on a card one rank higher; only a same-suit descending run moves as a group, and only face-up cards move. An uncovered card turns face up, and an empty column takes anything.',
    '**Stock:** Deal one card to each column from the stock, but only when no column is empty.',
    '**Completion:** A complete K-A same-suit run is automatically removed. Clear all 8 to win.',
    '**This simulation:** AI plays automatically, making moves and dealing from stock.',
  ],
  tictactoe: [
    '**Board:** 3x3 grid. Players alternate placing X and O.',
    '**Goal:** Be the first to get 3 of your marks in a row -- horizontal, vertical, or diagonal.',
    '**Draw:** If all 9 cells are filled with no winner, it\'s a draw.',
    '**AI:** Uses perfect-play minimax -- it will never lose.',
  ],
};


