// How each game is played, lifted from the hand-written rules panels in
// apps/games/classic/web/*.html rather than restated, so the arcade and the
// original shells cannot drift into describing the same game differently.
// Backgammon and Sudoku had no panel there and are written here.
//
// A leading **bolded phrase** opens most entries; the page renders that.
export const RULES = {
  backgammon: [
    '**Goal:** Bring all fifteen of your checkers around to your home board, then bear them off. First side to bear all fifteen off wins.',
    '**The opening:** two checkers on your 24-point, five on your 13, three on your 8 and five on your 6 -- 167 pips of travel each, the standard position.',
    '**Moving:** Throw two dice and move a checker that many points for each, or four moves when the two match. The dice show on the throwing side, White on the left and Black on the right, and go flat as they are spent. The two sides run in opposite directions.',
    '**The doubling cube:** shown on the bar for completeness and inert. This engine implements no doubling, so nothing here offers or takes one.',
    '**Blots and the bar:** A point held by a single checker is a blot. Land on it and that checker goes to the bar, and must re-enter before its owner may move anything else.',
    '**Blocked points:** You may not land on a point held by two or more enemy checkers.',
    '**Playing:** press Roll, then click a point to pick a checker up and a point to put it down; legal points are ringed. The bar and the bear-off tray are clickable in their own right. A die with no legal move anywhere is forfeit, and the pass button appears when that happens.',
  ],
  sudoku: [
    '**Goal:** Fill the grid so that every row, every column and every three-by-three box holds one to nine exactly once.',
    '**Givens:** The digits already on the grid are the puzzle. They never change and they are enough to determine one answer.',
    '**This solver:** the engine generates a full grid, removes cells, and solves the result by backtracking. Press the step and it fills the whole thing, reporting how many placements the search had to try.',
  ],
  battleship: [
    '**Goal:** Sink all of your opponent\'s ships before they sink yours.',
    '**Setup:** Each fleet places 5 ships on a 10x10 grid. Ships cannot overlap.',
    '**Firing:** Each turn, both fleets fire one salvo at a grid coordinate. A hit is marked with an explosion, a miss with a dot.',
    '**Ships:** Carrier (5), Battleship (4), Cruiser (3), Submarine (3), Destroyer (2) = 17 cells total.',
    '**Victory:** First fleet to score 17 hits (sinking all enemy ships) wins.',
    '**This simulation:** AI plays both fleets. Watch the grids fill with hits and misses until one fleet is destroyed.',
  ],
  blackjack: [
    '**Goal:** Get a hand value closer to 21 than the dealer without going over (busting).',
    '**Card values:** Number cards = face value. Face cards (J/Q/K) = 10. Ace = 11 or 1.',
    '**Deal:** Player and dealer each get 2 cards. Dealer\'s second card is face-down (the "hole card").',
    '**Player turn:** Hit (take a card) or Stand. Bust if over 21.',
    '**Dealer turn:** Hole card revealed. Dealer must hit until reaching 17+.',
    '**Result:** Closest to 21 wins. Bust = automatic loss. Tie = push (no winner).',
  ],
  bridge: [
    '**Goal:** Score more points than the opposing partnership over 8 hands.',
    '**Teams:** North/South vs East/West.',
    '**Bidding:** Teams bid to set a contract -- the number of tricks (above 6) they commit to win, and the trump suit.',
    '**Trump suits:** ♠ Spades, ♥ Hearts, ♦ Diamonds, ♣ Clubs.',
    '**Tricks:** 13 tricks per hand. Highest card of led suit wins unless trumped.',
    '**Scoring:** Make your contract = score points. Fall short = opponents score penalties.',
  ],
  checkers: [
    '**Goal:** Capture all of your opponent\'s pieces or block them so they can\'t move.',
    '**Movement:** Pieces move diagonally forward one square. Kings can move diagonally in any direction.',
    '**Captures:** Jump over an adjacent opponent piece to an empty square beyond it. Multiple jumps are allowed in one turn.',
    '**Kings:** When a piece reaches the opposite end of the board, it becomes a king (shown with a crown).',
    '**This simulation:** AI plays both sides using minimax with depth-3 search.',
  ],
  connect4: [
    '**Goal:** Be the first to connect four of your discs in a row -- horizontally, vertically, or diagonally.',
    '**Play:** Players take turns dropping one disc into any column. The disc falls to the lowest available row.',
    '**Strategy:** Block your opponent while building your own connections. Control the center column for maximum options.',
    '**This simulation:** AI plays both sides, taking a win where there is one, blocking one where there is not, and otherwise favouring the centre columns.',
  ],
  crazyeights: [
    '**Goal:** Be the first player to empty your hand.',
    '**Play:** On your turn, play a card that matches the rank or suit of the top discard card. If you can\'t play, draw from the pile.',
    '**Eights are wild:** An 8 can be played on anything. The player who plays an 8 declares the new suit.',
    '**End:** First player to play all their cards wins.',
  ],
  dotsandboxes: [
    '**Goal:** Complete more boxes than your opponent on a 4x4 dot grid.',
    '**Play:** Take turns drawing one line between adjacent dots. When you complete the 4th side of a box, you score it and go again.',
    '**Strategy:** Avoid giving your opponent chains of boxes. Force them to open chains for you to claim.',
    '**End:** Game ends when all 24 lines are drawn (9 boxes total). Most boxes wins.',
  ],
  game2048: [
    '**Goal:** Slide and merge tiles to create a 2048 tile (or higher).',
    '**Play:** Each turn, all tiles slide in one direction. When two tiles of the same value collide, they merge into one tile with double the value.',
    '**Spawning:** After each move, a new tile (2 or 4) appears in a random empty cell.',
    '**End:** The game ends when no more moves are possible (board full, no adjacent matches).',
    '**This simulation:** AI picks the best direction each move using a heuristic strategy.',
  ],
  go: [
    '**Goal:** Control more territory than your opponent on a 9x9 board.',
    '**Play:** Players alternate placing stones. Black goes first. Stones are placed on intersections, not squares.',
    '**Capture:** Surround an opponent\'s group (remove all its liberties) to capture it. Captured stones are removed from the board.',
    '**Ko rule:** You cannot immediately recapture a stone that just captured yours (prevents infinite loops).',
    '**Passing:** A player may pass instead of placing a stone. Two consecutive passes end the game.',
    '**Scoring:** Count surrounded empty points (territory) + captured stones. Highest total wins.',
    '**Note:** This AI sometimes passes early, resulting in short games.',
  ],
  gofish: [
    '**Goal:** Collect the most "books" (four cards of the same rank).',
    '**Play:** On your turn, ask another player for a specific rank. If they have it, they hand it over. If not -- "Go Fish!" -- draw from the pond.',
    '**Books:** When you collect all 4 cards of a rank, that\'s a book.',
    '**End:** Game ends when all 13 books are completed. Most books wins.',
    '**Spectator mode:** You can see every player\'s cards as the AI plays.',
  ],
  hexgame: [
    '**Goal:** Connect your two opposite edges of the board with an unbroken chain of your stones.',
    '**Board:** 11x11 rhombus of hexagonal cells.',
    '**Turns:** Players alternate placing one stone on any empty hex. Black goes first.',
    '**Black** wins by connecting the top edge to the bottom edge.',
    '**White** wins by connecting the left edge to the right edge.',
    '**No draws:** The board must always produce a winner -- it is mathematically impossible to fill the board without one player completing a connection.',
  ],
  hexwar: [
    '**Scenario:** Stalingrad. A hex-based wargame where two sides fight for control of the city.',
    '**Flow:** Each turn, units move across the hex grid, attack enemy positions, and try to capture key objectives.',
    '**Combat:** Units have attack and defense values. Terrain modifies combat outcomes. Supply lines matter.',
    '**Victory:** The game runs for a set number of turns. Victory is determined by objectives held at the end.',
    '**This simulation:** AI plays both sides. The progress bar shows how far into the battle we are.',
  ],
  liarsdice: [
    '**Goal:** Be the last player with dice remaining.',
    '**Each round:** All players secretly roll their dice. Players take turns bidding on the total number of a specific face value among ALL dice on the table.',
    '**Bidding:** Each bid must raise the quantity or the face value. A player may challenge the previous bid by calling "Liar!"',
    '**Challenge:** All dice are revealed. If the bid was too high, the bidder loses a die. If the bid was valid, the challenger loses a die.',
    '**End:** When a player loses all their dice, they\'re eliminated. Last player standing wins.',
  ],
  life: [
    'Conway\'s Game of Life. Each cell is alive or dead. A dead cell with exactly 3 alive neighbors becomes alive. An alive cell with 2 or 3 alive neighbors survives, otherwise it dies. 20x20 toroidal grid (edges wrap). The AI seeds an initial pattern and steps through generations.',
  ],
  mahjong: [
    'Mahjong Solitaire (Shanghai). 144 tiles arranged in layers. Match and remove pairs of identical free tiles. A tile is free if it has no tile on top and at least one side (left or right) is open. Game ends when no more pairs can be found or all tiles are cleared.',
  ],
  mancala: [
    'Mancala (Kalah variant). Two players, 6 pits each plus a store. On your turn, pick up all stones from one of your pits and sow them counter-clockwise, one per pit. If your last stone lands in your store, go again. If it lands in an empty pit on your side, capture that stone plus the opposite pit\'s stones. Game ends when one side is empty; remaining stones go to the other player\'s store. Most stones wins.',
  ],
  mastermind: [
    '**Goal:** Guess the secret 4-color code in 10 guesses or fewer.',
    '**Colors:** Red, Blue, Green, Yellow, Purple, Orange (6 colors, 4 positions).',
    '**Feedback:** After each guess, you receive feedback pegs:',
    '● **Black peg** = right colour in the right position.',
    '○ **White peg** = right colour in the wrong position.',
    '**Strategy:** The AI uses the remaining candidate pool to narrow down possibilities each guess.',
    '**This simulation:** AI codebreaker tries to crack the secret in 10 guesses using elimination strategy.',
  ],
  minesweeper: [
    'Minesweeper. 9x9 grid with 10 hidden mines. Reveal cells to find safe ground. Numbers show how many adjacent cells contain mines. The AI picks safe cells using zero-risk deduction. Hit a mine = game over. Clear all 71 safe cells to win.',
  ],
  monopoly: [
    '**Goal:** Be the last player with cash. All other players go bankrupt.',
    '**Flow:** Roll dice, move around the 40-space board. Land on unowned property to buy it. Land on owned property to pay rent. Pass Go to collect $200.',
    '**Special spaces:** Go (collect $200), Jail (just visiting or sent), Free Parking, Go To Jail (sent directly to Jail).',
    '**Elimination:** If you cannot pay rent or taxes, you are bankrupt and eliminated.',
    '**This simulation:** AI plays up to 200 turns. Last player standing wins.',
  ],
  othello: [
    '**Board:** 8x8 grid. Each player has a disc color (black or white).',
    '**Moves:** Place a disc to outflank opponent discs -- trap them in a straight line (horizontal, vertical, or diagonal) between your new disc and an existing one of yours. Outflanked discs flip to your color.',
    '**Valid moves:** Every move must flip at least one opponent disc. If you cannot move, you pass.',
    '**End:** The game ends when neither player can move. The player with the most discs wins.',
  ],
  pinochle: [
    '**Goal:** Be the first team to reach a target score by winning tricks and forming melds.',
    '**The deck:** Pinochle uses a special 48-card deck with two copies of each card from 9 through Ace in all four suits (no 2-8 cards). Card ranking from high to low: A, 10, K, Q, J, 9.',
    '**Teams:** Four players in two partnerships of two. Partners sit across from each other.',
    '**Melds:** After the deal, players score points for specific card combinations (melds) in their hand. Common melds include: Pinochle (Jack of Diamonds + Queen of Spades), Marriage (King + Queen of same suit), and Runs (A-10-K-Q-J of trump).',
    '**Trick-taking:** After melding, players take turns playing cards. You must follow suit if possible; otherwise you must play trump if possible. The highest trump wins, or the highest card of the led suit if no trump is played.',
    '**Scoring:** Points come from melds and from capturing certain cards in tricks (Aces=11, Tens=10, Kings=4, Queens=3, Jacks=2). Last trick is worth an extra 10 points.',
    '**This simulation:** AI plays 6 hands of pinochle. Each step shows one completed hand with running team scores.',
  ],
  poker: [
    '**Goal:** Make the best five-card hand to beat your opponent.',
    '**Hand rankings (low to high):** High Card, Pair, Two Pair, Three of a Kind, Straight, Flush, Full House, Four of a Kind, Straight Flush.',
    '**Flow:** Each player is dealt five cards. Players may discard and redraw to improve. Best hand wins.',
    '**This simulation:** AI plays 10 hands. Each deal shows face-down cards, then reveals hand rankings one at a time.',
  ],
  pokervariants: [
    '**Goal:** Make the best five-card poker hand to beat your opponent.',
    '**The deal:** Each player is dealt five cards face down from a standard 52-card deck.',
    '**The draw:** After looking at their hand, each player may discard up to three cards (or four if holding an Ace) and receive replacements from the deck. This is the chance to improve your hand.',
    '**The showdown:** After the draw, hands are revealed and compared. The player with the best poker hand wins.',
    '**Hand rankings (low to high):** High Card, Pair, Two Pair, Three of a Kind, Straight, Flush, Full House, Four of a Kind, Straight Flush.',
    '**Strategy:** Keep strong combinations (pairs, three of a kind) and discard weak cards hoping to draw better ones. Knowing when to hold and when to draw is the key skill.',
    '**This simulation:** AI plays 8 hands of Five Card Draw. Each step shows one completed hand with the result.',
  ],
  risk: [
    '**Goal:** Conquer all 12 territories. Last player standing wins.',
    '**Flow:** Each turn, the current player deploys reinforcement armies, then attacks neighboring territories. Combat is dice-based: attacker and defender each roll, highest die wins.',
    '**Elimination:** When a player loses all territories, they are eliminated.',
    '**This simulation:** AI plays up to 100 turns with 4 commanders fighting over 12 territories.',
  ],
  royalur: [
    '**Goal:** Be the first player to move all 7 pieces off the board.',
    '**Dice:** Roll 4 binary dice (each 0 or 1) for a total of 0-4 pips.',
    '**Movement:** Each piece travels along a fixed path. P1 (blue) enters from the top, P2 (red) from the bottom. Both share the middle row.',
    '**Rosettes (✦):** Landing on a rosette grants an extra turn. Pieces on rosettes are safe from capture.',
    '**Capture:** Landing on an opponent\'s piece in the shared row sends it back to the start.',
    '**Scoring:** A piece that moves past the last square is scored. First to score all 7 wins.',
  ],
  rps: [
    '**Goal:** Win the most rounds out of 20.',
    '**Each round:** Both players simultaneously choose Rock, Paper, or Scissors.',
    '**Rock** beats Scissors. **Scissors** beats Paper. **Paper** beats Rock.',
    '**End:** After 20 rounds, the player with more wins takes the match. Ties are possible.',
  ],
  setgame: [
    '**Goal:** Find all valid sets among the cards on the table.',
    '**Cards:** Each card has 4 attributes: **Number** (1/2/3), **Shape** (diamond/oval/squiggle), **Color** (red/green/purple), and **Shading** (empty/striped/solid).',
    '**Valid set:** 3 cards where, for each of the 4 attributes, the values are either ALL the same or ALL different across the 3 cards.',
    '**Example:** 1-red-solid-diamond + 2-green-striped-oval + 3-purple-empty-squiggle is a valid set (all attributes are all-different).',
    '**This simulation:** AI finds sets automatically. When a set is found, those 3 cards are replaced from the deck.',
  ],
  spider: [
    '**Goal:** Clear all 8 suits by building complete King-to-Ace descending sequences of the same suit.',
    '**Tableau:** 10 columns of cards. Move cards between columns to build descending sequences. Only same-suit sequences can be moved as a group.',
    '**Stock:** When stuck, deal one card to each column from the stock pile.',
    '**Completion:** A complete K-A same-suit run is automatically removed. Clear all 8 to win.',
    '**This simulation:** AI plays automatically, making moves and dealing from stock.',
  ],
  tictactoe: [
    '**Board:** 3x3 grid. Players alternate placing X and O.',
    '**Goal:** Be the first to get 3 of your marks in a row -- horizontal, vertical, or diagonal.',
    '**Draw:** If all 9 cells are filled with no winner, it\'s a draw.',
    '**AI:** Uses perfect-play minimax -- it will never lose.',
  ],
  war: [
    '**Goal:** Win all 52 cards.',
    '**Setup:** The deck is split evenly between two players (26 cards each).',
    '**Each round:** Both players flip their top card. The higher card wins both cards. If tied, it\'s "war" -- extra cards are wagered and the next flip decides.',
    '**Card ranks:** 2 (low) through Ace (high). Suits don\'t matter.',
    '**End:** The game ends when one player runs out of cards. The other player wins.',
  ],
  yahtzee: [
    '**Dice:** Roll 5 dice up to 3 times per turn, keeping any between rolls.',
    '**Scoring:** After rolling, score in one of 13 categories: Ones through Sixes (sum of matching dice), Three/Four of a Kind, Full House, Small/Large Straight, Yahtzee (five of a kind), or Chance (sum of all dice).',
    '**Categories:** Each category can only be used once per game.',
    '**End:** After 13 turns (all categories filled), highest total score wins.',
  ],
};


