// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
const fw_k_dead : i32 = 0;
const fw_k_shell : i32 = 2;
const fw_k_willow : i32 = 3;
const fw_k_glitter : i32 = 4;
const fw_k_smoke : i32 = 5;
const fw_k_trail : i32 = 6;
fn fw_floor(x : f32) -> f32 {
  let t = f32(f32(i32(x)));
  if ((t > x)) {
  return (t - bitcast<f32>(1065353216u));
  } else {
  return t;
  }
}
fn fw_fract(x : f32) -> f32 {
  return (x - fw_floor(x));
}
fn fw_rand(x : f32) -> f32 {
  return fw_fract((sin((x * bitcast<f32>(1095751224u))) * bitcast<f32>(1193995915u)));
}
fn fw_drag(kind : i32) -> f32 {
  if ((kind == fw_k_shell)) {
  return bitcast<f32>(1065336438u);
  } else {
  if ((kind == fw_k_willow)) {
  return bitcast<f32>(1065084780u);
  } else {
  if ((kind == fw_k_glitter)) {
  return bitcast<f32>(1065151889u);
  } else {
  if ((kind == fw_k_smoke)) {
  return bitcast<f32>(1064682127u);
  } else {
  if ((kind == fw_k_trail)) {
  return bitcast<f32>(1064313028u);
  } else {
  return bitcast<f32>(1065185443u);
  }
  }
  }
  }
  }
}
fn fw_grav(kind : i32) -> f32 {
  if ((kind == fw_k_smoke)) {
  return (bitcast<f32>(0u) - bitcast<f32>(1011129253u));
  } else {
  if ((kind == fw_k_willow)) {
  return bitcast<f32>(1025222115u);
  } else {
  if ((kind == fw_k_glitter)) {
  return bitcast<f32>(1028443340u);
  } else {
  if ((kind == fw_k_trail)) {
  return bitcast<f32>(1020591603u);
  } else {
  return bitcast<f32>(1027101163u);
  }
  }
  }
  }
}
fn fw_wind_take(kind : i32) -> f32 {
  if ((kind == fw_k_smoke)) {
  return bitcast<f32>(1075419545u);
  } else {
  if ((kind == fw_k_willow)) {
  return bitcast<f32>(1067030937u);
  } else {
  if ((kind == fw_k_glitter)) {
  return bitcast<f32>(1061997772u);
  } else {
  return bitcast<f32>(1057803468u);
  }
  }
  }
}
fn fw_turb(fg : f32, px : f32, py : f32, t : f32) -> f32 {
  return ((sin((((px * bitcast<f32>(1012202995u)) + (t * bitcast<f32>(1017907249u))) + (fg * bitcast<f32>(1086918649u)))) * bitcast<f32>(1019517861u)) + (sin((((py * bitcast<f32>(1005747122u)) - (t * bitcast<f32>(1015383955u))) + (fg * bitcast<f32>(1078530041u)))) * bitcast<f32>(1014887350u)));
}
fn fw_new_vx(vx : f32, px : f32, py : f32, fg : f32, t : f32, kind : i32, wind : f32) -> f32 {
  return (((vx + (wind * fw_wind_take(kind))) + fw_turb(fg, px, py, t)) * fw_drag(kind));
}
fn fw_new_vy(vy : f32, px : f32, py : f32, fg : f32, t : f32, kind : i32) -> f32 {
  return (((vy + fw_grav(kind)) + (fw_turb((fg + bitcast<f32>(1052602531u)), py, px, t) * bitcast<f32>(1057803468u))) * fw_drag(kind));
}
fn fw_red(c : i32) -> f32 {
  return (f32(f32((c / 65536))) / bitcast<f32>(1132396544u));
}
fn fw_green(c : i32) -> f32 {
  return (f32(f32(((c / 256) - ((c / 65536) * 256)))) / bitcast<f32>(1132396544u));
}
fn fw_blue(c : i32) -> f32 {
  return (f32(f32((c - ((c / 256) * 256)))) / bitcast<f32>(1132396544u));
}
fn fw_sat8(v : f32) -> i32 {
  return i32(max(bitcast<f32>(0u), min(bitcast<f32>(1132396544u), (v * bitcast<f32>(1132396544u)))));
}
fn fw_pack(r : f32, g : f32, b : f32) -> i32 {
  return (((fw_sat8(r) * 65536) + (fw_sat8(g) * 256)) + fw_sat8(b));
}
fn fw_hot(fade : f32) -> f32 {
  let a = ((fade - bitcast<f32>(1063675494u)) / bitcast<f32>(1036831948u));
  if ((a < bitcast<f32>(0u))) {
  return bitcast<f32>(0u);
  } else {
  return ((a * a) * bitcast<f32>(1060655595u));
  }
}
fn fw_cool(fade : f32) -> f32 {
  return min(bitcast<f32>(1065353216u), (fade * bitcast<f32>(1076258406u)));
}
fn fw_shade_r(col : i32, fade : f32) -> f32 {
  let h = fw_hot(fade);
  return ((fw_red(col) * (bitcast<f32>(1065353216u) - h)) + h);
}
fn fw_shade_g(col : i32, fade : f32) -> f32 {
  let h = fw_hot(fade);
  return (((fw_green(col) * (bitcast<f32>(1065353216u) - h)) + (h * bitcast<f32>(1064682127u))) * (bitcast<f32>(1051595898u) + (bitcast<f32>(1059648962u) * fw_cool(fade))));
}
fn fw_shade_b(col : i32, fade : f32) -> f32 {
  let h = fw_hot(fade);
  return (((fw_blue(col) * (bitcast<f32>(1065353216u) - h)) + (h * bitcast<f32>(1063004405u))) * (bitcast<f32>(1036831948u) + (bitcast<f32>(1063675494u) * fw_cool(fade))));
}
fn fw_twinkle(fg : f32, t : f32, kind : i32) -> f32 {
  if ((kind == fw_k_glitter)) {
  let r = fw_rand(((fg * bitcast<f32>(1119315558u)) + (fw_floor((t * bitcast<f32>(1056964608u))) * bitcast<f32>(1060840144u))));
  if ((r > bitcast<f32>(1058977873u))) {
  return (bitcast<f32>(1065353216u) + (r * bitcast<f32>(1075419545u)));
  } else {
  return (bitcast<f32>(1036831948u) + (r * bitcast<f32>(1048576000u)));
  }
  } else {
  if ((kind == fw_k_willow)) {
  return (bitcast<f32>(1060655595u) + (bitcast<f32>(1049582632u) * fw_rand(((fg * bitcast<f32>(1095866777u)) + (fw_floor((t * bitcast<f32>(1051595898u))) * bitcast<f32>(1054179590u))))));
  } else {
  return bitcast<f32>(1065353216u);
  }
  }
}
fn fw_decay(fade : f32, a : f32, b : f32) -> f32 {
  let e = (bitcast<f32>(1065353216u) - fade);
  return (bitcast<f32>(1065353216u) / ((bitcast<f32>(1065353216u) + (a * e)) + ((b * e) * e)));
}
fn fw_bright(fade : f32, fg : f32, t : f32, kind : i32) -> f32 {
  if ((kind == fw_k_dead)) {
  return bitcast<f32>(0u);
  } else {
  if ((kind == fw_k_shell)) {
  return (bitcast<f32>(1064514355u) + (bitcast<f32>(1050253721u) * fw_rand((fg + (fw_floor((t * bitcast<f32>(1056964608u))) * bitcast<f32>(1038174126u))))));
  } else {
  if ((kind == fw_k_smoke)) {
  return (bitcast<f32>(1022739087u) * fade);
  } else {
  if ((kind == fw_k_trail)) {
  return (bitcast<f32>(1061997772u) * fw_decay(fade, bitcast<f32>(1088421888u), bitcast<f32>(1104150528u)));
  } else {
  let base = (bitcast<f32>(1064011038u) * fw_decay(fade, bitcast<f32>(1079613849u), bitcast<f32>(1091567616u)));
  let birth = select(bitcast<f32>(0u), bitcast<f32>(1063675494u), (fade > bitcast<f32>(1065101557u)));
  return ((base + birth) * fw_twinkle(fg, t, kind));
  }
  }
  }
  }
}
fn fw_size(fade : f32, kind : i32) -> f32 {
  if ((kind == fw_k_dead)) {
  return bitcast<f32>(0u);
  } else {
  if ((kind == fw_k_shell)) {
  return bitcast<f32>(1076258406u);
  } else {
  if ((kind == fw_k_smoke)) {
  return (bitcast<f32>(1091567616u) + (bitcast<f32>(1106247680u) * (bitcast<f32>(1065353216u) - fade)));
  } else {
  if ((kind == fw_k_trail)) {
  return (bitcast<f32>(1057803468u) + (bitcast<f32>(1067869798u) * fade));
  } else {
  if ((kind == fw_k_willow)) {
  return (bitcast<f32>(1066611507u) + (bitcast<f32>(1069966950u) * fade));
  } else {
  if ((kind == fw_k_glitter)) {
  return (bitcast<f32>(1064514355u) + (bitcast<f32>(1067869798u) * fade));
  } else {
  return (bitcast<f32>(1069128089u) + (bitcast<f32>(1075000115u) * fade));
  }
  }
  }
  }
  }
  }
}
fn fw_fade(life : i32, maxl : i32) -> f32 {
  if ((maxl <= 0)) {
  return bitcast<f32>(0u);
  } else {
  return max(bitcast<f32>(0u), min(bitcast<f32>(1065353216u), (f32(f32(life)) / f32(f32(maxl)))));
  }
}
fn fw_next_life(life : i32, kind : i32) -> i32 {
  if ((kind == fw_k_dead)) {
  return 0;
  } else {
  return (life - 1);
  }
}
fn fw_next_kind(life : i32, kind : i32) -> i32 {
  if ((kind == fw_k_dead)) {
  return fw_k_dead;
  } else {
  if ((life <= 1)) {
  return fw_k_dead;
  } else {
  return kind;
  }
  }
}
fn fw_out_pos(v : f32) -> i32 {
  return i32((v * bitcast<f32>(1098907648u)));
}
fn fw_out_attr(size : f32, bright : f32, kind : i32) -> i32 {
  let s = i32(max(bitcast<f32>(0u), min(bitcast<f32>(1132396544u), (size * bitcast<f32>(1090519040u)))));
  let b = i32(max(bitcast<f32>(0u), min(bitcast<f32>(1132396544u), (bright * bitcast<f32>(1107296256u)))));
  return (((s * 65536) + (b * 256)) + kind);
}
@group(0) @binding(0) var<storage, read_write> fw_sim_step_state_buf : array<i32>;
@group(0) @binding(1) var<storage, read_write> fw_sim_step_out_buf : array<i32>;
struct U_fw_sim_step {
  frame : i32,
  wind : i32,
}
@group(0) @binding(2) var<uniform> u_fw_sim_step : U_fw_sim_step;
@compute @workgroup_size(64)
fn fw_sim_step_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let frame = u_fw_sim_step.frame;
  let wind = u_fw_sim_step.wind;
  let ipx = fw_sim_step_state_buf[(gid * 8)];
  let ipy = fw_sim_step_state_buf[((gid * 8) + 1)];
  let ivx = fw_sim_step_state_buf[((gid * 8) + 2)];
  let ivy = fw_sim_step_state_buf[((gid * 8) + 3)];
  let life = fw_sim_step_state_buf[((gid * 8) + 4)];
  let maxl = fw_sim_step_state_buf[((gid * 8) + 5)];
  let col = fw_sim_step_state_buf[((gid * 8) + 6)];
  let kind = fw_sim_step_state_buf[((gid * 8) + 7)];
  let t = f32(f32(frame));
  let fg = fw_rand((f32(f32(gid)) * bitcast<f32>(1015920826u)));
  let wf = (f32(f32(wind)) / bitcast<f32>(1148846080u));
  let px = (f32(f32(ipx)) / bitcast<f32>(1132462080u));
  let py = (f32(f32(ipy)) / bitcast<f32>(1132462080u));
  let vx = (f32(f32(ivx)) / bitcast<f32>(1132462080u));
  let vy = (f32(f32(ivy)) / bitcast<f32>(1132462080u));
  let held = select(select(0, 1, (kind == fw_k_dead)), 1, (kind == fw_k_shell));
  let nvx = select(fw_new_vx(vx, px, py, fg, t, kind, wf), vx, (held == 1));
  let nvy = select(fw_new_vy(vy, px, py, fg, t, kind), vy, (held == 1));
  let npx = select((px + nvx), px, (held == 1));
  let npy = select((py + nvy), py, (held == 1));
  let nlife = select(fw_next_life(life, kind), life, (held == 1));
  let nkind = select(fw_next_kind(life, kind), kind, (held == 1));
  let fade = fw_fade(life, maxl);
  let bright = fw_bright(fade, fg, t, kind);
  fw_sim_step_state_buf[(gid * 8)] = i32((npx * bitcast<f32>(1132462080u)));
  fw_sim_step_state_buf[((gid * 8) + 1)] = i32((npy * bitcast<f32>(1132462080u)));
  fw_sim_step_state_buf[((gid * 8) + 2)] = i32((nvx * bitcast<f32>(1132462080u)));
  fw_sim_step_state_buf[((gid * 8) + 3)] = i32((nvy * bitcast<f32>(1132462080u)));
  fw_sim_step_state_buf[((gid * 8) + 4)] = nlife;
  fw_sim_step_state_buf[((gid * 8) + 7)] = nkind;
  fw_sim_step_out_buf[(gid * 4)] = fw_out_pos(npx);
  fw_sim_step_out_buf[((gid * 4) + 1)] = fw_out_pos(npy);
  fw_sim_step_out_buf[((gid * 4) + 2)] = fw_pack(fw_shade_r(col, fade), fw_shade_g(col, fade), fw_shade_b(col, fade));
  fw_sim_step_out_buf[((gid * 4) + 3)] = fw_out_attr(fw_size(fade, kind), bright, kind);
}