// Generated by Codex WGSL Plug
// Compute shaders lowered from Codex [Device] kernels.
fn clamp_int(v : i32, lo : i32, hi : i32) -> i32 {
  if ((v < lo)) {
  return lo;
  } else {
  if ((v > hi)) {
  return hi;
  } else {
  return v;
  }
  }
}
fn cordic_atan2(y : f32, x : f32) -> f32 {
  let ax = abs(x);
  let ay = abs(y);
  let mn = min(ax, ay);
  let mx = max(ax, ay);
  let a = select(bitcast<f32>(0u), (mn / mx), (mx > bitcast<f32>(0u)));
  let a2 = (a * a);
  let numer = (bitcast<f32>(1121058816u) + (bitcast<f32>(1113325568u) * a2));
  let denom = (bitcast<f32>(1121058816u) + (a2 * (bitcast<f32>(1119092736u) + (bitcast<f32>(1091567616u) * a2))));
  let t = (a * numer);
  let base = (t / denom);
  let r1 = select(base, (bitcast<f32>(1070141402u) - base), (ay > ax));
  let r2 = select(r1, (bitcast<f32>(1078530010u) - r1), (x < bitcast<f32>(0u)));
  if ((y < bitcast<f32>(0u))) {
  return (bitcast<f32>(0u) - r2);
  } else {
  return r2;
  }
}
fn earth_shade_pixel(framebuf : ptr<storage, array<i32>, read_write>, tex : ptr<storage, array<i32>, read_write>, gid : i32, ti : i32, hx : f32, hy : f32, hz : f32, sx : f32, sy : f32, sz : f32) -> i32 {
  let tr = (*tex)[ti];
  let tg = (*tex)[(ti + 1)];
  let tb = (*tex)[(ti + 2)];
  let dot = (((hx * sx) + (hy * sy)) + (hz * sz));
  let sun = max(bitcast<f32>(0u), dot);
  let diff = (bitcast<f32>(1039516303u) + (sun * bitcast<f32>(1067869798u)));
  let rim = sqrt(((hx * hx) + (hy * hy)));
  let atmo = (((rim * rim) * rim) * bitcast<f32>(1058642329u));
  let cr = clamp_int(i32(((f32(f32(tr)) * diff) + (atmo * bitcast<f32>(1116471296u)))), 0, 255);
  let cg = clamp_int(i32(((f32(f32(tg)) * diff) + (atmo * bitcast<f32>(1124204544u)))), 0, 255);
  let cb = clamp_int(i32(((f32(f32(tb)) * diff) + (atmo * bitcast<f32>(1132396544u)))), 0, 255);
  let pixel = ((((cr * 65536) + (cg * 256)) + cb) + bitcast<i32>(4278190080u));
  (*framebuf)[gid] = pixel;
  return 0;
}
fn earth_sky_pixel(framebuf : ptr<storage, array<i32>, read_write>, gid : i32, miss : f32) -> i32 {
  let glow = max(bitcast<f32>(0u), (bitcast<f32>(1065353216u) - (miss * bitcast<f32>(1094713344u))));
  let g2 = (glow * glow);
  let cr = clamp_int(i32((g2 * bitcast<f32>(1103626240u))), 0, 255);
  let cg = clamp_int(i32((g2 * bitcast<f32>(1112014848u))), 0, 255);
  let cb = clamp_int(i32((g2 * bitcast<f32>(1126170624u))), 0, 255);
  let pixel = ((((cr * 65536) + (cg * 256)) + cb) + bitcast<i32>(4278190080u));
  (*framebuf)[gid] = pixel;
  return 0;
}
fn atan2_approx(y : f32, x : f32) -> f32 {
  return cordic_atan2(y, x);
}
fn gamma_byte(v : f32) -> i32 {
  let clamped = max(bitcast<f32>(0u), v);
  let g = (sqrt(sqrt(clamped)) * sqrt(clamped));
  return clamp_int(i32((g * bitcast<f32>(1132396544u))), 0, 255);
}
fn bh_write(framebuf : ptr<storage, array<i32>, read_write>, gid : i32, cr : f32, cg : f32, cb : f32, opacity : f32, vx : f32, vy : f32, vz : f32) -> i32 {
  let gr = gamma_byte(cr);
  let gg = gamma_byte(cg);
  let gb = gamma_byte(cb);
  let pixel = ((((gr * 65536) + (gg * 256)) + gb) + bitcast<i32>(4278190080u));
  (*framebuf)[gid] = pixel;
  return 0;
}
fn asin_approx(x : f32) -> f32 {
  let clamped = min(bitcast<f32>(1065336438u), max((bitcast<f32>(0u) - bitcast<f32>(1065336438u)), x));
  return atan2_approx(clamped, sqrt((bitcast<f32>(1065353216u) - (clamped * clamped))));
}
fn bh_march(framebuf : ptr<storage, array<i32>, read_write>, gid__a : i32, px__a : f32, py__a : f32, pz__a : f32, vx__a : f32, vy__a : f32, vz__a : f32, time__a : f32, step__a : i32, cr__a : f32, cg__a : f32, cb__a : f32, opacity__a : f32) -> i32 {
  var gid = gid__a;
  var px = px__a;
  var py = py__a;
  var pz = pz__a;
  var vx = vx__a;
  var vy = vy__a;
  var vz = vz__a;
  var time = time__a;
  var step = step__a;
  var cr = cr__a;
  var cg = cg__a;
  var cb = cb__a;
  var opacity = opacity__a;
  loop {
    if ((step >= 250)) {
    return bh_write(framebuf, gid, cr, cg, cb, opacity, vx, vy, vz);
    } else {
    if ((opacity > bitcast<f32>(1065185443u))) {
    return bh_write(framebuf, gid, cr, cg, cb, opacity, vx, vy, vz);
    } else {
    let r = sqrt((((px * px) + (py * py)) + (pz * pz)));
    if ((r < bitcast<f32>(1050924810u))) {
    return bh_write(framebuf, gid, cr, cg, cb, bitcast<f32>(1065353216u), vx, vy, vz);
    } else {
    if ((r > bitcast<f32>(1112014848u))) {
    return bh_write(framebuf, gid, cr, cg, cb, opacity, vx, vy, vz);
    } else {
    let dt = min(bitcast<f32>(1039516303u), max(bitcast<f32>(994352037u), (r * bitcast<f32>(1025758986u))));
    let hcx = ((py * vz) - (pz * vy));
    let hcy = ((pz * vx) - (px * vz));
    let hcz = ((px * vy) - (py * vx));
    let h2 = (((hcx * hcx) + (hcy * hcy)) + (hcz * hcz));
    let r5 = ((((r * r) * r) * r) * r);
    let gm = (((bitcast<f32>(0u) - bitcast<f32>(1056293519u)) * h2) / r5);
    let gx = ((px / r) * gm);
    let gy = ((py / r) * gm);
    let gz = ((pz / r) * gm);
    let nvx = (vx + (gx * dt));
    let nvy = (vy + (gy * dt));
    let nvz = (vz + (gz * dt));
    let vl = sqrt((((nvx * nvx) + (nvy * nvy)) + (nvz * nvz)));
    let nvx2 = (nvx / vl);
    let nvy2 = (nvy / vl);
    let nvz2 = (nvz / vl);
    let npx = (px + (nvx2 * dt));
    let npy = (py + (nvy2 * dt));
    let npz = (pz + (nvz2 * dt));
    let crossed = select(bitcast<f32>(0u), bitcast<f32>(1065353216u), ((py * npy) < bitcast<f32>(0u)));
    if ((crossed > bitcast<f32>(1056964608u))) {
    let tc = (py / (py - npy));
    let cx = (px + ((npx - px) * tc));
    let cz = (pz + ((npz - pz) * tc));
    let disk_r = sqrt(((cx * cx) + (cz * cz)));
    let inner_fade = min(bitcast<f32>(1065353216u), max(bitcast<f32>(0u), ((disk_r - bitcast<f32>(1060320051u)) / bitcast<f32>(1050253721u))));
    let outer_fade = min(bitcast<f32>(1065353216u), max(bitcast<f32>(0u), ((bitcast<f32>(1074580684u) - disk_r) / bitcast<f32>(1053609164u))));
    let in_ring = (inner_fade * outer_fade);
    if ((in_ring > bitcast<f32>(1008981770u))) {
    let angle = atan2_approx(cz, cx);
    let orbit = (angle + ((time * bitcast<f32>(1069547520u)) / (disk_r * disk_r)));
    let n1 = sin(((orbit * bitcast<f32>(1077936128u)) + (disk_r * bitcast<f32>(1073741824u))));
    let n2 = sin((((orbit * bitcast<f32>(1088421888u)) + (disk_r * bitcast<f32>(1056964608u))) + bitcast<f32>(1067869798u)));
    let turb = ((bitcast<f32>(1059481190u) + (n1 * bitcast<f32>(1048576000u))) + (n2 * bitcast<f32>(1036831948u)));
    let density = ((in_ring * bitcast<f32>(1056964608u)) * turb);
    let temp = max(bitcast<f32>(0u), (bitcast<f32>(1065353216u) - ((disk_r - bitcast<f32>(1056293519u)) / bitcast<f32>(1074748456u))));
    let grav = sqrt(max(bitcast<f32>(0u), (bitcast<f32>(1065353216u) - (bitcast<f32>(1050924810u) / r))));
    let side = sin(angle);
    let doppler = select((bitcast<f32>(1053609164u) + ((bitcast<f32>(1065353216u) + side) * bitcast<f32>(1050253721u))), (bitcast<f32>(1067869798u) + (side * bitcast<f32>(1056964608u))), (side > bitcast<f32>(0u)));
    let bright = ((grav * doppler) * density);
    let t2 = (temp * temp);
    let rem = (bitcast<f32>(1065353216u) - opacity);
    let ncr = (cr + ((bright * (bitcast<f32>(1067030937u) + (t2 * bitcast<f32>(1058642329u)))) * rem));
    let ncg = (cg + ((bright * (bitcast<f32>(1063675494u) + (temp * bitcast<f32>(1056964608u)))) * rem));
    let ncb = (cb + ((bright * (bitcast<f32>(1056964608u) + (t2 * bitcast<f32>(1053609164u)))) * rem));
    let nop = min((opacity + (density * bitcast<f32>(1056964608u))), bitcast<f32>(1065353216u));
    let _mv1 = gid;
    let _mv2 = npx;
    let _mv3 = npy;
    let _mv4 = npz;
    let _mv5 = nvx2;
    let _mv6 = nvy2;
    let _mv7 = nvz2;
    let _mv8 = time;
    let _mv9 = (step + 1);
    let _mv10 = ncr;
    let _mv11 = ncg;
    let _mv12 = ncb;
    let _mv13 = nop;
    gid = _mv1;
    px = _mv2;
    py = _mv3;
    pz = _mv4;
    vx = _mv5;
    vy = _mv6;
    vz = _mv7;
    time = _mv8;
    step = _mv9;
    cr = _mv10;
    cg = _mv11;
    cb = _mv12;
    opacity = _mv13;
    continue;
    } else {
    let _mv1 = gid;
    let _mv2 = npx;
    let _mv3 = npy;
    let _mv4 = npz;
    let _mv5 = nvx2;
    let _mv6 = nvy2;
    let _mv7 = nvz2;
    let _mv8 = time;
    let _mv9 = (step + 1);
    let _mv10 = cr;
    let _mv11 = cg;
    let _mv12 = cb;
    let _mv13 = opacity;
    gid = _mv1;
    px = _mv2;
    py = _mv3;
    pz = _mv4;
    vx = _mv5;
    vy = _mv6;
    vz = _mv7;
    time = _mv8;
    step = _mv9;
    cr = _mv10;
    cg = _mv11;
    cb = _mv12;
    opacity = _mv13;
    continue;
    }
    } else {
    let _mv1 = gid;
    let _mv2 = npx;
    let _mv3 = npy;
    let _mv4 = npz;
    let _mv5 = nvx2;
    let _mv6 = nvy2;
    let _mv7 = nvz2;
    let _mv8 = time;
    let _mv9 = (step + 1);
    let _mv10 = cr;
    let _mv11 = cg;
    let _mv12 = cb;
    let _mv13 = opacity;
    gid = _mv1;
    px = _mv2;
    py = _mv3;
    pz = _mv4;
    vx = _mv5;
    vy = _mv6;
    vz = _mv7;
    time = _mv8;
    step = _mv9;
    cr = _mv10;
    cg = _mv11;
    cb = _mv12;
    opacity = _mv13;
    continue;
    }
    }
    }
    }
    }
  }
}
@group(0) @binding(0) var<storage, read_write> earth_pixel_params_buf : array<i32>;
@group(0) @binding(1) var<storage, read_write> earth_pixel_framebuf_buf : array<i32>;
@group(0) @binding(2) var<storage, read_write> earth_pixel_tex_buf : array<i32>;
struct U_earth_pixel {
  tw : i32,
  th : i32,
  w : i32,
  h : i32,
}
@group(0) @binding(3) var<uniform> u_earth_pixel : U_earth_pixel;
@compute @workgroup_size(64)
fn earth_pixel_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let tw = u_earth_pixel.tw;
  let th = u_earth_pixel.th;
  let w = u_earth_pixel.w;
  let h = u_earth_pixel.h;
  let i_aspect = earth_pixel_params_buf[0];
  let i_zoom = earth_pixel_params_buf[1];
  let i_cam_pitch = earth_pixel_params_buf[2];
  let i_earth_yaw = earth_pixel_params_buf[3];
  let i_earth_pitch = earth_pixel_params_buf[4];
  let i_sun_x = earth_pixel_params_buf[5];
  let i_sun_y = earth_pixel_params_buf[6];
  let i_sun_z = earth_pixel_params_buf[7];
  let px = (gid - ((gid / w) * w));
  let py = (gid / w);
  let aspect = (f32(f32(i_aspect)) / bitcast<f32>(1148846080u));
  let zoom = (f32(f32(i_zoom)) / bitcast<f32>(1148846080u));
  let cam_pitch = (f32(f32(i_cam_pitch)) / bitcast<f32>(1148846080u));
  let earth_yaw = (f32(f32(i_earth_yaw)) / bitcast<f32>(1148846080u));
  let earth_pitch = (f32(f32(i_earth_pitch)) / bitcast<f32>(1148846080u));
  let sun_x = (f32(f32(i_sun_x)) / bitcast<f32>(1148846080u));
  let sun_y = (f32(f32(i_sun_y)) / bitcast<f32>(1148846080u));
  let sun_z = (f32(f32(i_sun_z)) / bitcast<f32>(1148846080u));
  let ndx = ((((f32(f32(px)) / f32(f32(w))) - bitcast<f32>(1056964608u)) * bitcast<f32>(1073741824u)) * aspect);
  let ndy = ((bitcast<f32>(1056964608u) - (f32(f32(py)) / f32(f32(h)))) * bitcast<f32>(1073741824u));
  let rlen = sqrt((((ndx * ndx) + (ndy * ndy)) + bitcast<f32>(1065353216u)));
  let rdx = (ndx / rlen);
  let rdy = (ndy / rlen);
  let rdz = (bitcast<f32>(1065353216u) / rlen);
  let cos_cp = cos(cam_pitch);
  let sin_cp = sin(cam_pitch);
  let dx = rdx;
  let dy = ((cos_cp * rdy) - (sin_cp * rdz));
  let dz = ((sin_cp * rdy) + (cos_cp * rdz));
  let neg_zoom = (bitcast<f32>(0u) - zoom);
  let oy = (bitcast<f32>(0u) - (sin_cp * neg_zoom));
  let oz = (cos_cp * neg_zoom);
  let b = (bitcast<f32>(1073741824u) * ((oy * dy) + (oz * dz)));
  let c = (((oy * oy) + (oz * oz)) - bitcast<f32>(1065353216u));
  let disc = ((b * b) - (bitcast<f32>(1082130432u) * c));
  let t = select(select((bitcast<f32>(0u) - bitcast<f32>(1065353216u)), (((bitcast<f32>(0u) - b) - sqrt(disc)) / bitcast<f32>(1073741824u)), ((((bitcast<f32>(0u) - b) - sqrt(disc)) / bitcast<f32>(1073741824u)) > bitcast<f32>(981668462u))), (bitcast<f32>(0u) - bitcast<f32>(1065353216u)), (disc < bitcast<f32>(0u)));
  if ((t > bitcast<f32>(981668462u))) {
  let hx = (t * dx);
  let hy = (oy + (t * dy));
  let hz = (oz + (t * dz));
  let cos_ey = cos(earth_yaw);
  let sin_ey = sin(earth_yaw);
  let cos_ep = cos(earth_pitch);
  let sin_ep = sin(earth_pitch);
  let ry = ((cos_ep * hy) - (sin_ep * hz));
  let rz = ((sin_ep * hy) + (cos_ep * hz));
  let gx = ((cos_ey * hx) + (sin_ey * rz));
  let gy = ry;
  let gz = ((bitcast<f32>(0u) - (sin_ey * hx)) + (cos_ey * rz));
  let lat = asin_approx(gy);
  let lon = atan2_approx(gx, gz);
  let pi = bitcast<f32>(1078530010u);
  let u = (bitcast<f32>(1065353216u) - (((lon / pi) + bitcast<f32>(1065353216u)) * bitcast<f32>(1056964608u)));
  let v = (bitcast<f32>(1056964608u) - (lat / pi));
  let tx_raw = i32((u * f32(f32(tw))));
  let tx_idx = (tx_raw - ((tx_raw / tw) * tw));
  let ty_idx = clamp_int(i32((v * f32(f32(th)))), 0, (th - 1));
  let ti = (((ty_idx * tw) + tx_idx) * 3);
  _ = earth_shade_pixel(&earth_pixel_framebuf_buf, &earth_pixel_tex_buf, gid, ti, hx, hy, hz, sun_x, sun_y, sun_z);
  } else {
  let miss = (sqrt(max(bitcast<f32>(0u), ((c + bitcast<f32>(1065353216u)) - ((b * b) / bitcast<f32>(1082130432u))))) - bitcast<f32>(1065353216u));
  _ = earth_sky_pixel(&earth_pixel_framebuf_buf, gid, miss);
  }
}
@group(0) @binding(0) var<storage, read_write> bh_pixel_params_buf : array<i32>;
@group(0) @binding(1) var<storage, read_write> bh_pixel_framebuf_buf : array<i32>;
struct U_bh_pixel {
  w : i32,
  h : i32,
}
@group(0) @binding(2) var<uniform> u_bh_pixel : U_bh_pixel;
@compute @workgroup_size(64)
fn bh_pixel_main(@builtin(global_invocation_id) gid_vec : vec3<u32>) {
  let gid = i32(gid_vec.x);
  let w = u_bh_pixel.w;
  let h = u_bh_pixel.h;
  let i_aspect = bh_pixel_params_buf[0];
  let i_zoom = bh_pixel_params_buf[1];
  let i_cam_pitch = bh_pixel_params_buf[2];
  let i_cam_yaw = bh_pixel_params_buf[3];
  let i_bh_time = bh_pixel_params_buf[4];
  let px = (gid - ((gid / w) * w));
  let py = (gid / w);
  let aspect = (f32(f32(i_aspect)) / bitcast<f32>(1148846080u));
  let zoom = (f32(f32(i_zoom)) / bitcast<f32>(1148846080u));
  let cp = (f32(f32(i_cam_pitch)) / bitcast<f32>(1148846080u));
  let cy = (f32(f32(i_cam_yaw)) / bitcast<f32>(1148846080u));
  let time = (f32(f32(i_bh_time)) / bitcast<f32>(1148846080u));
  let ndx = ((((f32(f32(px)) / f32(f32(w))) - bitcast<f32>(1056964608u)) * bitcast<f32>(1073741824u)) * aspect);
  let ndy = ((bitcast<f32>(1056964608u) - (f32(f32(py)) / f32(f32(h)))) * bitcast<f32>(1073741824u));
  let rlen = sqrt((((ndx * ndx) + (ndy * ndy)) + bitcast<f32>(1085821419u)));
  let rdx = (ndx / rlen);
  let rdy = (ndy / rlen);
  let rdz = (bitcast<f32>(1075419545u) / rlen);
  let cos_y = cos(cy);
  let sin_y = sin(cy);
  let cos_p = cos(cp);
  let sin_p = sin(cp);
  let d1x = ((cos_y * rdx) + (sin_y * rdz));
  let d1z = ((bitcast<f32>(0u) - (sin_y * rdx)) + (cos_y * rdz));
  let vx = d1x;
  let vy = ((cos_p * rdy) - (sin_p * d1z));
  let vz = ((sin_p * rdy) + (cos_p * d1z));
  let neg_zoom = (bitcast<f32>(0u) - zoom);
  let o1x = (sin_y * neg_zoom);
  let o1z = (cos_y * neg_zoom);
  let posX = o1x;
  let posY = (bitcast<f32>(0u) - (sin_p * o1z));
  let posZ = (cos_p * o1z);
  _ = bh_march(&bh_pixel_framebuf_buf, gid, posX, posY, posZ, vx, vy, vz, time, 0, bitcast<f32>(0u), bitcast<f32>(0u), bitcast<f32>(0u), bitcast<f32>(0u));
}